### ISSUE TITLE
Amount of ingredients truncated to two decimal places

### ISSUE THREAD

**Issue by RustyRin** [vabene1111/recipes#104]
Amount of ingredient gets truncated to 2 decimal places, which is a bit inconvenient when a recipe calls for 1/8 of an teaspoon 😔

**Comment by vabene1111** [comment]
who has recipes with this amount of percision in decimals 😂 i guess i could add a config option, i basically never have decimals if i dont scale to any weird amounts so having 3 ore more decimals would probably be annoying for many people.

**Comment by RustyRin** [comment]
I can't wait for america to go metric. But [this](https://www.kingarthurflour.com/recipes/chocolate-cream-pie-recipe) is a worst case scenario with 1/8 of a cup of water and 1/8 of a teaspoon of salt.

But this is not an amazingly terrible bug since its pretty obvious what it should be when you see 0.12 in the amount

**Comment by vabene1111** [comment]
haha ok, i will add a setting for that :)

**Comment by vabene1111** [comment]
ok i have added a setting for the upcoming release. i also added a little indication (`~`) for when stuff gets rounded so that if you for example enter 0,5050 kg you dont lose the last 50 grams.

**Comment by lustiq** [comment]
Hey,
it seems that the issue of truncated decmials is relevant in the newer version again. Everything from the third place on is cut off even with decimal places set to > 3.
I'd like to argue for the relevance of a reliable third decimal place as in professional recipes the amounts are often in kg only. That's not an precison issue but for consistency and structure. Furthermore the setting is misleading and doesn't live up to its promise.

**Comment by vabene1111** [comment]
please open a new issue for this and I can take a look in a future update :)
