### ISSUE TITLE
Search tags in qucksearch

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#105]
Can search please also work on tags?

**Comment by vabene1111** [comment]
you mean the quick search bar ? because the advanced search already has tag support ?

**Comment by therealschimmi** [comment]
never noticed there was a advanced search bar... but yes, why not make it optional what quick search will do for you :)

**Comment by vabene1111** [comment]
i might take a look at this at some point. The problem is that this would require a much more complicated search algorithm as some kind of weighting must happend to determine the sorting order but since search is a very fundamental tool this is something i wanted to do anyway at some point

**Comment by smilerz** [comment]
this is included in #658
