### ISSUE TITLE
Customization recipe page

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#106]
- Make commenting optional (I don't need it in my household at all)
 - Make the set of buttons at the top customizable, I just need "add to meal plan" and "export shopping list" there. BTW: I noticed those icons get stacked in a weird way on mobile, are they all the same width?
 - It would be nice to add "Share" if you like to share a recipe with someone, e.g. through PDF

**Comment by vabene1111** [comment]
i like these ideas. Sharing is probably a seperate topic which i wanted to look at anyway but i will leave it in this issue for now.
