### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#107]
Can you add more detailed user permissions?
I would like to have a dedicated tablet for the kitchen and a user that can only read and write recipes, plan meals, make a shopping list, and has a simple interface with everything deactivated for him being invisible.

**Comment by vabene1111** [comment]
i think what you are looking for is a guest user or maybe a normal user (see https://github.com/vabene1111/recipes/wiki/Permission-System , normal users cannot really do anything harmful). Is that sufficent ? This application was specifically designed for use cases where fine grained permissions don't matter and has only recently started adopting some of its features so feedback here  is very welcome.

The other thing you mention is some kind of "distraction free mode". I think its a feature worth adding but will probably take some time as its not a very high priority and also possibly requires some major restructuring work.

**Comment by therealschimmi** [comment]
Distraction free mode describes it perfectly :)

**Comment by vabene1111** [comment]
ok but the permission problem is sorted out ? because i will create a seperate issue then?

**Comment by therealschimmi** [comment]
yeah, alright
