### ISSUE TITLE
Meal planning sharing

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#110]
How is this supposed to work? Default sharing settings don't work, settings upon creation of a meal plan entry don't work. What works for me is when I add a meal to the plan and then edit to add users to share with.

**Comment by vabene1111** [comment]
the meal plan has been reworked completly with the upcoming release. Sharing was fixed as well. It would be really great to get some feedback on that before releasing it. as mentioned in #98 feel free to update to the development version but dont downgrade until the version is release to master. 

The worst that could (hopefully) happen is that meal planning breaks for a few days but for me its working perfectly fine. As always a DB backup is strongly recommended before updating.

**Comment by therealschimmi** [comment]
I want to set up a second container for the development version, but how do I do that? Probably need to modify docker-compose.yml to point to development instead of latest master?

**Comment by therealschimmi** [comment]
got it running, will have a look

**Comment by therealschimmi** [comment]
Awesome, you did a fantastic job! some things I noticed:
- If you add the same recipe twice for a single day, addition of ingredients is broken, last ingredient in recipe affected
- If I added a weekdays recipes to the shopping list with the little shopping cart icon, the symbol should change visually. At the moment its possible to click the same day several times and you won't notice
- the shopping list preview and data transfer if you click open shopping list is broken in the way it handles duplicates
- is it possible to remove recipes from the plan by drag-and drop?

**Comment by vabene1111** [comment]
Thank you very much, feedback for big changes like this one is always very helpful before releasing to everyone. I will take a look at it the next few days and fix/comment on it. A little busy right now so might take a few days, sry

**Comment by vabene1111** [comment]
Ok so regarding your feedback

1. Shopping list same recipes: The shopping list wasn't really build with the idea in mind that one would add the same recipe twice. It also does not really support scaling. I have opened a new issue as this will be a complete rewrite at some point when i find time for it #114

2. each plan item can only be added once to the shopping list so clicking it multiple times should not change anything (that is how it behaves in my tests, if thats not the case for you its definitly a bug)

3. i do not fully understand what you mean here, is it related to 1. and #104 ?

4. that is something i had initally planned but then did not do. i will open an issue and maybe implement it when i have time

**Comment by therealschimmi** [comment]
1. Addition of ingredients is still broken in 0.9, if i have the same recipe twice in one week
2. idk how i did it, cant replicate it either. 
3. put the same recipe on a plan twice within a week, add those days to the shopping list. on the same page on the left bottom you put a "preview" of the shopping list, the recipe should appear there twice. now when you poen the shopping list you should see that although the quantities are correct (although issue 1.), the recipe has only been added to the list once. when you click the load button, the shopping list changes and loads the ingredients only for one meal

**Comment by vabene1111** [comment]
will be fixed with #114
