### ISSUE TITLE
chowdown import/export

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#113]
add import export for chowdown recipes https://chowdown.io/

**Comment by PureLoneWolf** [comment]
Hi - I was just about to post and ask about this because the Chowdown recipe .md files aren't importable currently - This would be fantastic.  Is this still something you are hoping to implement?

**Comment by vabene1111** [comment]
definitly! I am not very good at writing parsers so there are a lot of open issues regarding importing functionality but it is one of the bigger topics i want to accomplish in the near future to have proper importing and exporting.

But dont get your hopes up too fast, this will definitely take a while since everyone uses different formats thus and as far as i remember chowdown was unformatted as well which makes it extra hard.

**Comment by PureLoneWolf** [comment]
Fantastic - Although the recipes are definitely formatted - I think they are a variation on Recipe microdata:

https://raw.githubusercontent.com/clarklab/chowdown/gh-pages/_recipes/broccoli-cheese-soup.md

:)

**Comment by vabene1111** [comment]
they are formatted but not easily machine readable (like e.g. a json or xml would be). But you are right, they are in a standardized format that can be imported, just need to write a parser (help is very welcome here if anyone is an expert at writing parsers :D)

**Comment by vabene1111** [comment]
chowdown import support has been added, export is still open
