### ISSUE TITLE
Meal Plan remove via drag&drop

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#115]
remove recipes from plan via drag and drop

**Comment by PTST** [comment]
Hi, great app you have made! 👍 

While i can see that i cannot delete a recipe from a mealplan via drag and drop, i can for the life of me not figure out any other ways to remove a recipe from a mealplan?

**Comment by vabene1111** [comment]
haha, i guess its not really intuitive ... if you click on an entry a little popup should open. There you can delete the entry.

Not really nice but needs to do for now. improving this is planned

**Comment by PTST** [comment]
Well, i guess i should have tried that 😅 

I just assumed that it would take me to the recipe if i tried that

**Comment by vabene1111** [comment]
no worries, if you dont understand it right a way its simply not intuitive enough

**Comment by Kaibu** [comment]
Present in the meal plan refactor
