### ISSUE TITLE
Shopping List always duplicates the first item

### ISSUE THREAD

**Issue by rrash283** [vabene1111/recipes#121]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 

### Bug description
The first ingredient added to the `ingredient` list will have an index of 0. If that same ingredient is used again in it assigns `index = 0`
`if index:` when index = 0 returns False so the ingredient is added to the list again.
The code needs to be changed to something like `if index is not None:`

The code below is from the shopping list view.

```python
for r in recipes:
        for ri in RecipeIngredient.objects.filter(recipe=r).exclude(unit__name__contains='Special:').all():
            index = None
            for x, ig in enumerate(ingredients):
                if ri.ingredient == ig.ingredient and ri.unit == ig.unit:
                    index = x

            if index:
                ingredients[index].amount = ingredients[index].amount + ri.amount
            else:
                ingredients.append(ri)
```

**Comment by vabene1111** [comment]
thanks for the detailed report! the shopping list really need a rework, this is another reason why #114
