### ISSUE TITLE
Safron import

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#122]
import for safron exports

**Comment by himankpathak** [comment]
Hey @vabene1111, Can you describe in detail what needs to be done?

**Comment by vabene1111** [comment]
There are many different providers for recipes and recipe related things. i want to add an import/export module where all different kinds of third party formats can be imported and exported. Obviously importing is of higher priority than exporting.

i have honestly not really looked at the format that safron exports but i guess it should be possible to import that somehow.

i guess the following needs to be done

1. create a page (or better even a general architecture) where importers and exporters can live
2. create something that can read safron type exports and import them 
(2.1. create something that can create safron type exports)
3. write some tests

**Comment by vabene1111** [comment]
import done, export missing

**Comment by vabene1111** [comment]
[saffron-recipes.zip](https://github.com/vabene1111/recipes/files/5952748/saffron-recipes.zip)
example file
