### ISSUE TITLE
Com is not available.... Android version is 8.1.0

### ISSUE THREAD

**Issue by sum4015** [vabene1111/recipes#126]
![Screenshot_20200625-212020_Termux](https://user-images.githubusercontent.com/67430927/85758448-f6c8fd80-b72d-11ea-9c17-fe5281846897.jpg)

### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 

### Issue
Please describe your problem here

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
env content
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
docker-compose.yml content
```

**Comment by sum4015** [comment]
8.1.0 this is my android version...

**Comment by vabene1111** [comment]
i am afraid their is no android version of this application thus i think you have mistaken this repository for something else
