### ISSUE TITLE
Export of notes from plan to shopping list

### ISSUE THREAD

**Issue by Virtex6** [vabene1111/recipes#131]
Entry of type "only note" are not added to shopping list.

The entries are passed as null value via GET Parameter. I mostly use it to define additional ingredients to the main dishes. It would be nice if the title is added to the shopping list or if there is a export checkbox to enable/disable the export.

Tested with version 525ad6dd9842e21e57ae0383eeeffdd98fbf83fd

**Comment by vabene1111** [comment]
thats a good idea, i will include it in the shopping list rewrite #114 once i finish rewriting recipe steps #127
