### ISSUE TITLE
Ingredient quantity regression - commit 9b9fbd5 

### ISSUE THREAD

**Issue by Penquincoder** [vabene1111/recipes#134]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.9.2 ??  ( System version says 0.0.0)  commit 9b9fbd5 

### Bug description
Previous versions allowed fractions of units for ingredients, EG 0.5, or 0.25. Most recent commit regresses this ability, and only accepts full integer values (0, or 1) etc. 

Please allow decimals or fractions of units for ingredients between 0 and 1.

**Comment by vabene1111** [comment]
hmm this is weired, i specifically added features to allow more decimal places than before. Can you please look at your preferences and tell me what the ingredient decimals setting is set to for you 

![image](https://user-images.githubusercontent.com/6819595/87253755-f050ba80-c47d-11ea-946b-309e9b270108.png)

**Comment by Penquincoder** [comment]
Ingredient decimals* shows exactly how it does on your example picture. It is set to 2.

**Comment by vabene1111** [comment]
hmm ok, i wanted to support both comma and dot as a decimal seperator but in doing so i might have broken the dot. I will fix that soon.

**Comment by vabene1111** [comment]
ok so the issue was that firefox does not (by default) allow decimals for number inputs. Its fixed with 4d08477b235a290c92e77e2879556084334df6f9

while i greatly appreciate feedback from people using the development build i cant recommend you to use it for production. 
But since you are already using it it would be really great to hear some feedback on the new recipe editing and viewing ui .. i guess you cant compare it to the previous one since you haven't used it but general feedback is very welcome as well.

**Comment by Penquincoder** [comment]
Thank you very much for that fix. I don't particularity like the 'recent' view for the search page, but you do have an option to turn that off which is good. The additions of 'steps' I can see being useful, but it is a little confusing coming from the previous incarnation. I like the simplicity of just writing the recipes in markdown, adding my own steps or notes. I am just keeping it as 'step 1' (without a name) and adding all my instructions, which seems to work fine for on screen and print. 

Thank you.

**Comment by vabene1111** [comment]
Thanks for the feedback. I tried leaving all options open to the user (having 1 or many steps, using just markdown or using ingredients, using timers or not using them). If it works fine for you without using many steps than thats exactly how i wanted it to be. 

If you have any ideas or particular things that were not obvious at first let me know so i might be able to make them more intuitive or add some help texts here and there.
