### ISSUE TITLE
Installation Instructions w/o Docker

### ISSUE THREAD

**Issue by soapee01** [vabene1111/recipes#139]
Are there any installation instructions to install this without docker that I've missed somewhere?

Thanks!

**Comment by vabene1111** [comment]
In the readme under Installation > Manual there are some small hints and a link to this general django setup tutorial which should work https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html

You can generally follow every django setup tutorial out there as this application is just a standard django app

**Comment by Mwoua** [comment]
Im currently doing it on my raspberry, so here are the steps I followed (inspired from the provided link )

Create virtual env and activate it
clone project from git and cd into it
pip install -r requirements.txt

Here I had an error about psycopg2-binary, I had to install "sudo apt install libpq-dev"

pip install -r requirements.txt
again 

Copy .env.template to .env, and follow instructions in the file

run server: python manage.py runserver 0.0.0.0:8000

See that there are missing migration, so follow instructions:
python manage.py migrate

run server again
It should work


Thats a really basic setup, to test that it works. After that you should install nginx to have a web server, and plug django into it. I'll try to reply here again with my next step

**Comment by vabene1111** [comment]
this sounds about right! I will include the libpq-dev requirement in the normal instructions so that does not have to be found out by error :)

**Comment by Mwoua** [comment]
I just started again where I left off. I dont have any postgres installed on my distribution, so I guess I need to install
'sudo apt-get install postgresql postgresql-contrib'
Is 'postgresql-contrib' necessary?

(I'm keeping notes of what I do so I can provide setup instructions after)

**Comment by vabene1111** [comment]
You can write it up into a instructions file an PR it or just post it in this issue. Did you manage to get postgresql working ?

**Comment by vabene1111** [comment]
The setup docs have been reworked on the new documentation page. If anyone feels like somthing is missing please create a PR or submit an issue with the required information
