### ISSUE TITLE
[feature] recipe scaling - Answered and Already included

### ISSUE THREAD

**Issue by Leopere** [vabene1111/recipes#14]
I won’t ask for conversations because there’s a thousand tools for that but I will ask for recipe scaling.

**Comment by vabene1111** [comment]
what do you mean by scaling ? it is possible to multiply all ingredients in a recipe by a factor (the little calculator in the top left of a recipe list). Or do you mean something different ?

Simply enter a number and the ingredients will multiply
![image](https://user-images.githubusercontent.com/6819595/72291339-6e5b1280-364f-11ea-9e8e-6a9871a5698d.png)

**Comment by Leopere** [comment]
Oh wonderful! Feel free to close this!

**Comment by dennorske** [comment]
Awesome! Was just going to ask the same. Please add to the readme! 🙏
