### ISSUE TITLE
500 when creating a shopping list from Meal-Plan

### ISSUE THREAD

**Issue by mikes02** [vabene1111/recipes#141]
On version 0.10.0 I receive a 500 when 'Open Shopping List' on the 'Meal-Plan' page.

Example from chrome debugger.  I have also tried other recipes and multiple recipes at the same time.
![image](https://user-images.githubusercontent.com/47875101/88665204-e21cb400-d0a3-11ea-8623-5775ff7362ac.png)

I was hoping to provide additional data from logs.  After a quick search I didn't see anything in /var/logs other than the 500 in nginx.  Are there logs setup anywhere else that I can grab?

**Comment by vabene1111** [comment]
what you can do is set`DEBUG=1` in the `.env` file but i was already able to reproduce the error so i should be able to fix it. I thought i tested this but must have apparently missed an edge case.

**Comment by vabene1111** [comment]
this should be fixed with the recent rework of the shopping list but i am not 100% sure. If it comes up again please reopen this issue or create a new one
