### ISSUE TITLE
.env not taken into account

### ISSUE THREAD

**Issue by Mwoua** [vabene1111/recipes#151]
### Version
Version: 
0.10.1

### Bug description
Fresh manual install, logged in, created the first user (admin) then went to system page:

Here I have 'Current Version: 0.0.0', 'Media Serving Warning', 'Secret Key Warning' and 'Debug Mode Warning'

But I have moved the .env.template to .env

I guess it's an issue loading info from the .env file.

**Comment by vabene1111** [comment]
When you setup without docker you need to make sure that the .env variables are actually exported/made available to the gunicorn instance. For example if you have a systemd service running gunicorn you can point that to the .env file using the `EnvironmentFile=` directive.

**Comment by Mwoua** [comment]
I added the .env file to the systemd service, it definitly had an effect. Now I have an error 500

So, I tried to set DEBUG to 1 to have more information, but it works with debug = 1 (But current version is still 0.0.0)

>  DEBUG=0
>
>ALLOWED_HOSTS=*
>
>SECRET_KEY=XXXX
>
>#DB_ENGINE=django.db.backends.postgresql_psycopg2
>POSTGRES_HOST=db_recipes
>POSTGRES_PORT=5432
>POSTGRES_USER=djangodb
>POSTGRES_PASSWORD=
>#POSTGRES_DB=djangodb
>
>GUNICORN_MEDIA=0
>
>REVERSE_PROXY_AUTH=0
>
>COMMENT_PREF_DEFAULT=1

I have commented out `DB_ENGINE` and `POSTGRES_DB` to first setup it with sqlite3 (because it should be simpler)

**Comment by vabene1111** [comment]
Hmm the version number is packaged into the docker containers whenever they are deployed so it is expected to be 0.0.0. This is not perfect but for the moment there are more important things i want to fix first. 

Regarding the 500 error: Here i will need more information about your setup. Do you run a properly configured nginx in front of your container ? Have you checked the system logs (`journalctl`) ? 

To be completly honest i do the docker deploy as the recommended default setup partially because its just much easier for me to support this installation method as many variables are controlled and its much easier for me to diagnose problems.

**Comment by Mwoua** [comment]
No problem about the 0.0.0, it was to tell you in case you didnt know.

I doubt nginx is the issue, because when I set the `DEBUG`  to 1 in `.env` file, it works. And I have never used django, so I dont know how to debug it. I hoped that setting DEBUG to 1 would help me, but it just fixed it. I guess I could stay with DEBUG=1 if you have no idea.

About docker, I originally tried with it, but I had the same issue (error 500) so I supposed it was linked to docker not being able to use my python 3.8 install (system python is 3.7), but maybe not

**Comment by Mwoua** [comment]
I have added nginx error and access log

> 192.168.2.18 - - [17/Aug/2020:11:35:37 -0400] "GET / HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.108 Safari/537.36"
> 192.168.2.18 - - [17/Aug/2020:11:35:37 -0400] "GET /favicon.ico HTTP/1.1" 500 145 "http://192.168.2.23:8002/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.108 Safari/537.36"


And gunicorn error log `--error-logfile /tmp/gunicorn_err.log --log-level debug --capture-output`

> [2020-08-17 11:34:50 -0400] [6281] [DEBUG] Current configuration:
>   config: None
>   bind: ['unix:/media/data/recipes/recipes.sock']
>   backlog: 2048
>   workers: 1
>   worker_class: sync
>   threads: 1
>   worker_connections: 1000
>   max_requests: 0
>   max_requests_jitter: 0
>   timeout: 30
>   graceful_timeout: 30
>   keepalive: 2
>   limit_request_line: 4094
>   limit_request_fields: 100
>   limit_request_field_size: 8190
>   reload: False
>   reload_engine: auto
>   reload_extra_files: []
>   spew: False
>   check_config: False
>   preload_app: False
>   sendfile: None
>   reuse_port: False
>   chdir: /media/data/recipes
>   daemon: False
>   raw_env: []
>   pidfile: None
>   worker_tmp_dir: None
>   user: 0
>   group: 33
>   umask: 0
>   initgroups: False
>   tmp_upload_dir: None
>   secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
>   forwarded_allow_ips: ['127.0.0.1']
>   accesslog: None
>   disable_redirect_access_to_syslog: False
>   access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
>   errorlog: /tmp/gunicorn_err.log
>   loglevel: debug
>   capture_output: True
>   logger_class: gunicorn.glogging.Logger
>   logconfig: None
>   logconfig_dict: {}
>   syslog_addr: udp://localhost:514
>   syslog: False
>   syslog_prefix: None
>   syslog_facility: user
>   enable_stdio_inheritance: False
>   statsd_host: None
>   dogstatsd_tags:
>   statsd_prefix:
>   proc_name: None
>   default_proc_name: recipes.wsgi:application
>   pythonpath: None
>   paste: None
>   on_starting: <function OnStarting.on_starting at 0x75f0f538>
>   on_reload: <function OnReload.on_reload at 0x75f0f5c8>
>   when_ready: <function WhenReady.when_ready at 0x75f0f658>
>   pre_fork: <function Prefork.pre_fork at 0x75f0f730>
>   post_fork: <function Postfork.post_fork at 0x75f0f7c0>
>   post_worker_init: <function PostWorkerInit.post_worker_init at 0x75f0f898>
>   worker_int: <function WorkerInt.worker_int at 0x75f0f928>
>   worker_abort: <function WorkerAbort.worker_abort at 0x75f0f9b8>
>   pre_exec: <function PreExec.pre_exec at 0x75f0fa48>
>   pre_request: <function PreRequest.pre_request at 0x75f0fad8>
>   post_request: <function PostRequest.post_request at 0x75f0fb20>
>   child_exit: <function ChildExit.child_exit at 0x75f0fbf8>
>   worker_exit: <function WorkerExit.worker_exit at 0x75f0fc88>
>   nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x75f0fd18>
>   on_exit: <function OnExit.on_exit at 0x75f0fda8>
>   proxy_protocol: False
>   proxy_allow_ips: ['127.0.0.1']
>   keyfile: None
>   certfile: None
>   ssl_version: 2
>   cert_reqs: 0
>   ca_certs: None
>   suppress_ragged_eofs: True
>   do_handshake_on_connect: False
>   ciphers: None
>   raw_paste_global_conf: []
>   strip_header_spaces: False
> [2020-08-17 11:34:50 -0400] [6281] [INFO] Starting gunicorn 20.0.4
> [2020-08-17 11:34:50 -0400] [6281] [DEBUG] Arbiter booted
> [2020-08-17 11:34:50 -0400] [6281] [INFO] Listening at: unix:/media/data/recipes/recipes.sock (6281)
> [2020-08-17 11:34:50 -0400] [6281] [INFO] Using worker: sync
> [2020-08-17 11:34:50 -0400] [6310] [INFO] Booting worker with pid: 6310
> [2020-08-17 11:34:50 -0400] [6281] [DEBUG] 1 workers
> [2020-08-17 17:35:33 +0200] [6310] [DEBUG] GET /
> [2020-08-17 17:35:37 +0200] [6310] [DEBUG] GET /favicon.ico

I dont know how to add log to the django app

**Comment by vabene1111** [comment]
i am not entirely sure as it has been a long time since i setup a django project without docker but you might run `journalctl` to see if your service posted above throws any errors.

Setting debug to 1 changes some key behaviors in the way django runs, for example that django is allowed to server media/static files (as can be seen in the last line of the gunicorn log, at least thats what i think).

Please try if it works with gunicorn_media set to 1 and debug set to 0. If so please refer to the nginx config samples provided with the docker files in order to setup proper media/static file serving trough nginx

**Comment by Mwoua** [comment]
(tldr at the end)
No info in journalctl
`GUNICORN_MEDIA=1` doesnt fix it.

But I found out how to add error logs, and here is what I have:
(To note, im correctly redirected to the search page)

> [17/Aug/2020 19:13:31] ERROR [django.request:222] Internal Server Error: /search/
> Traceback (most recent call last):
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/media/data/recipes/cookbook/views/views.py", line 72, in search
>     return render(request, 'index.html')
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
>     content = loader.render_to_string(template_name, context, request, using=using)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
>     return template.render(context, request)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
>     return self.template.render(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/base.py", line 171, in render
>     return self._render(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
>     return self.nodelist.render(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/base.py", line 936, in render
>     bit = node.render_annotated(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
>     return self.render(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
>     return compiled_parent._render(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
>     return self.nodelist.render(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/base.py", line 936, in render
>     bit = node.render_annotated(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
>     return self.render(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/templatetags/static.py", line 106, in render
>     url = self.url(context)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/templatetags/static.py", line 103, in url
>     return self.handle_simple(path)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/templatetags/static.py", line 118, in handle_simple
>     return staticfiles_storage.url(path)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
>     return self._url(self.stored_name, name, force)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
>     hashed_name = hashed_name_func(*args)
>   File "/opt/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 423, in stored_name
>     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
> ValueError: Missing staticfiles manifest entry for 'favicon.png'
> [17/Aug/2020 19:13:31] ERROR [django.request:222] Internal Server Error: /static/favicon.png
> [17/Aug/2020 19:13:31] ERROR [django.request:222] Internal Server Error: /favicon.ico

So, it looks like its an issue with static files indeed.

I updated my nginx configuration file to serve static files and still had an error `ValueError: Missing staticfiles manifest entry for 'favicon.png'`

Found out I need to run `python3.8 manage.py collectstatic` and update nginx conf to point to the new folder with static files

**Too long didnt read**:
I needed to run `python3.8 manage.py collectstatic` and update nginx conf file with the new folder with the static files. 
No idea why `GUNICORN_MEDIA=1` didnt fix it.

Now I need to switch to postgresql and see if everything works

**Comment by vabene1111** [comment]
perfect! Good to know that forgetting collectstatic might result in 500 errors ... will keep that in mind for future cases
