### ISSUE TITLE
Synolgy setup not correct

### ISSUE THREAD

**Issue by Nailik** [vabene1111/recipes#153]
Hello,
today i tried to set it up on my synology nas and it looks like there is sth missing in the instructions.

The database container shows an error when i try to open the webpage:

```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.

See PostgreSQL documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
```

So i got a `500 internal server error` when i tried to open webpage.

I found out that in the `.env` file, the password for postgres is empty so i had to add a passoword, this should be added to the documentation. Also in the docs it says "save as **`env`** file without extension" but it should be "save as **`.env`** file" (with a dot)

Also i would really like to know how to set it up for https?

### SSL Setup

I got my setup working with `https`

- create folder "ssl" inside nginx folder
- copy ssl certificates into folder
- change `Recepies.conf` :
`listen 80;` to `listen 80 ssl;`
and add
```
ssl_certificate /etc/nginx/certs/fullchain.pem;
ssl_certificate_key /etc/nginx/certs/privkey.pem;
```

- change `docker-compose.yml`
add  `- ./nginx/ssl:/etc/nginx/certs` to the `volumes` of` nginx_recipes`

Now you can use **https** (when you have setup the synology cert etc)

**Comment by vabene1111** [comment]
Thanks for the info! I personally do not have a synology docker host so the documentation was provided by another user. If you want feel free to open a pull request to incorporate your changes into the instructions. If not i will do my best to write down what you have written here so others can find it easily.

**Comment by Nailik** [comment]
PR: https://github.com/vabene1111/recipes/pull/267

**Comment by Nailik** [comment]
#267

**Comment by vabene1111** [comment]
thanks for fixing it :)
