### ISSUE TITLE
Move docker files out of web root 

### ISSUE THREAD

**Issue by Leopere** [vabene1111/recipes#16]
https://github.com/vabene1111/recipes/blob/develop/docker-compose.yml#L19-L20
```yaml
    volumes:
    - .:/Recipes
```
would contain the `docker-compose.yml` and the `Dockerfile` if a hacker compromises the webapp and gains filesystem access they could modify the `Dockerfile` to contain anything or worse the `docker-compose.yml` could be modified to contain anything.

**Comment by vabene1111** [comment]
Do you have a suggestion or a template on how you setup docker/compose with Django? 

I did it like this honestly because it has the most ease of use for deployment and since I always use git to override all local changes when updating the container but now that this gained some interest this should probably be looked at...

**Comment by Leopere** [comment]
I just thought of a possibly simple solution would be to use a
.dockerignore to ignore the patterns I mentioned.  Ignore the Dockerfile
and the docker-compose.yml that may make a difference but who knows?

**Comment by vabene1111** [comment]
docker file has been removed from git tracking and several examples of compose files have been given. Now any of them can be adapted to fit the need of having it outside the web root. 

If you create an example feel free to open a PR so i can include it

**Comment by Leopere** [comment]
I didn’t mean to suggest to remove the dockerfile from git just add a
.dockerignore file to ignore the Dockerfile in the build otherwise it could
be problematic.

**Comment by vabene1111** [comment]
but its better like this as anyone can change their docker files to their liking without loosing their changes on every update. Also the whole installation has/will be moved to a image based one so its even faster and easier.
