### ISSUE TITLE
Ingredient amount / quantity isn't shown when unit is empty

### ISSUE THREAD

**Issue by LBBO** [vabene1111/recipes#161]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.1

### Bug description
Some recipes call for quantities without units (such as "6 eggs"). However, if I leave the unit empty, the following bug appears:
![image](https://user-images.githubusercontent.com/8076094/91287631-48beeb80-e790-11ea-8bd5-17c29c0094a7.png)

After inspecting the element, it seems like the amount is hidden (probably, because the unit is empty). That causes the label and its parent nodes up to the element in the `td` to have a height of 0, thus rendering the checkbox at the wrong height. So, even though it looks like two different issues, both problems should be fixed by just rendering the quantity.

If you agree that this is a bug (as opposed to me just the app incorrectly) and it doesn't turn out to be way too complicated, I'd like to offer making a PR for this, myself.

### Temporary fix
I set up a unit containing just a [soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen), that appears empty while not causing the layout bug. For ease of use, I set that unit to be my default.
![image](https://user-images.githubusercontent.com/8076094/91287666-54aaad80-e790-11ea-8f98-fb27785234a8.png)

**Comment by vabene1111** [comment]
So technically it is not supposed to be allowed to leave the unit empty. I have run into the general issue of eggs and other stuff as well and have always used a unit called `Pieces` or `Packs` or whatever is applicable. 

Nonetheless this needs to be fixed. We can either fix the rendering (should not be to bad) or prevent saving of recipe ingredients without units. I guess you should be able to remove the unit as you can also remove the amount (which removes the unit as well). 

So a fix should

- [ ] fix the rendering of ingredients without units
- [ ] update the editing view and change the unit select box to allow easy unselection (there is an option for that)

feel free to fix either in a PR, the latter might be a little tricky so if you do the first i can do the second. I can also fix both, should not be to hard, but its always fun to have PRs so whatever you like.

**Comment by LBBO** [comment]
It looks to me like the rendering issue lies in [`recipe_view.html:151`](https://github.com/vabene1111/recipes/blob/develop/cookbook/templates/recipe_view.html#L151) (and line 266). Would it be possible to only hide the unit if it doesn't exist and still show the amount or would that collide with another use case (where, perhaps, the amount is empty and should trigger some behavior)?

What exactly do you mean by allowing easy unselection in the unit select box? As far as I can tell, you can just enter the current unit and instead of being able to add it, you're able to remove it. Perhaps you mean that that option should initially be visible and maybe even the default (before the user starts typing)?

**Comment by vabene1111** [comment]
Removing the unit and keeping the amount should be fine. I just tested it an you are right, i tought i disabled the remove behavior and i meant to add it back, but as its already in nothing has to be done here.

**Comment by LBBO** [comment]
Ok, great! PR incoming
