### ISSUE TITLE
bootstrap-vue textbox auto resize scroll issue

### ISSUE THREAD

**Issue by LBBO** [vabene1111/recipes#163]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.1

### Bug description
The simplest instructions to reproduce this issue should be the following:

1. Create / open a recipe
2. Edit the instructions. Make sure they are multiple lines long.
3. Scroll to the very bottom of the page
4. Edit the instructions by adding or deleting a character. The browser will immediately scroll up, oftentimes hiding a line or two of the instructions.

I can reproduce this issue reliably on a 1920 x 1080 screen in Chrome. However, in Firefox everything seems to work just fine.

In case my description wasn't clear, here's a GIF showing the issue. The upwards-scrolling happens automatically; the downwards-scrolling is done by me.

![GIF showing the issue](https://user-images.githubusercontent.com/8076094/91304472-d22ee780-e7a9-11ea-8abd-863edf0592d0.gif)

I believe the problem actually lies with bootstrap-vue. They watch the textarea's value and on every change, they re-compute the height. One of the steps is to set the height to auto, which defaults to two lines worth of text. Afterwards, they set the height back to something useful. In the meantime, Chrome seems to render the DOM, notices that it's gotten shorter and scrolls up as to not have any empty space at the bottom. Then, the textarea grows again, but now the new scroll height has already been set. For some reason, this doesn't seem to happen in Firefox.

Since the issue seems to actually lie with bootstrap-vue, I can understand if you don't want to fix this and you'd rather wait for an update from them. However, one possible solution to fix this on your side could be to just always make sure the textarea is completely visible on-screen after every edit. That way, there's less waiting :D

**Comment by vabene1111** [comment]
thats an interesting bug. I added the automatically sizing textboxes because i wanted to keep the DOM hight short if not needed but easily expandable if needed. Theoretically this could be disabled.

Thanks for posting this in bootstraß-vue's tracker, i will wait a few days to see if someone there responds and if not will try to find a workaround (maybe just a margin at the bottom of the page)

**Comment by vabene1111** [comment]
so i have implemented a margin at the bottom of the page, this way the instructions dont scroll out of the way when editing but it still scrolls a little bit. 

Since bootstrap-vue appears to be working on fixing the issue i will not implement any further mitigations as i think this is acceptable for the time being.

**Comment by LBBO** [comment]
Interesting! I can't reproduce it anymore on either of my setups. My local setup is built from bc39b53 and my "production" setup is running v0.11.2

Let me know if there's anything I can do to help. Not being able to reproduce the issue anymore might make that hard, though.

**Comment by vabene1111** [comment]
i guess if many people would be having this issue they would have reported it by now ..

I presume your local setup has debug enabled ?

**Comment by LBBO** [comment]
I'm not 100% sure I know what you mean (it's been a while since I touched my local config). If you mean the `DEBUG` env variable: no, it wasn't. I changed it to 1 just now but that didn't change anything - I still can't reproduce the issue.

**Comment by vabene1111** [comment]
ok then i will consider this fixed for most users except my local dev setup (for whatever reason).

I will keep this open, maybe bootstrap vue fixes this completely at some point as there appears to be some kind of issue

**Comment by LBBO** [comment]
Alright. I hope this doesn't stay so inconsistent!

Once again: thanks for your awesome work!

**Comment by vabene1111** [comment]
glad you like it, thanks for your help :)

**Comment by vabene1111** [comment]
ok since bootstrap vue textbox has been removed with the next update i am closing this
