### ISSUE TITLE
Invite function

### ISSUE THREAD

**Issue by wuast94** [vabene1111/recipes#165]
Would be nice to have an option for inviting people with email or an invite link

I think it's not a good way to make the registration completely open or set a password for new users. It would be better to invite Persons. 

For example enter an email Adress that get a registration link to create a user account with guest group/permissions. Or the same but without email, just a registration link that is 1 time usable or in other words can create 1 user account. 

My English is not the best but I hope you know what and how I mean it :) 

P.S.: thanks all for this great Projekt :)

**Comment by vabene1111** [comment]
thats a really great idea. The project was always meant for personal small scale use but being able to create a link that someone else can use to signup.

I think i would not add sending via email as thats just a lot of extra complexity added and just make a page (probably admin or system) where you can create a link for a certain group. That link can be valid for a fixed amount or even configurable.

**Comment by wuast94** [comment]
Email was just an addition but yes your right it's to much overhead :) 

Nice that you like the idea :)

Want to make a small group of People that can join an contribute to the recipes... And an invite link would make it much easier and more privacy related :)
