### ISSUE TITLE
TYPO: "Log in to view Recipies" text should be "Log in to view Recipes"

### ISSUE THREAD

**Issue by colino17** [vabene1111/recipes#166]
### Version
0.10.1

### Bug description
Mispelled warning in the following file:

**cookbook/templates/index.html
cookbook/locale/en/LC_MESSAGES/django.po
cookbook/locale/de/LC_MESSAGES/django.po
cookbook/locale/nl/LC_MESSAGES/django.po
cookbook/locale/fr/LC_MESSAGES/django.po**

"Log in to view Recipies"

should be

"Log in to view Recipes"

**Comment by vabene1111** [comment]
fixed, thanks for reporting
