### ISSUE TITLE
Recipe lookup by ingredient

### ISSUE THREAD

**Issue by stewartadam** [vabene1111/recipes#168]
**Is your feature request related to a problem? Please describe.**
Would be fun to select one (or more) ingredients and show matching recipes. Helpful for answering the question 'What can I cook with what's in the fridge?'

**Describe the solution you'd like**
1. Feature would permit selection of one or more ingredients (optionally, users could to match any ingredient or all entered ingredients)
2. App would search for recipes matching the requested ingredients

**Describe alternatives you've considered**
Not being lazy and matching recipes to what's in the fridge ;)

**Comment by vabene1111** [comment]
This is already possible (or should be). If you are on the search page press the three dots and open the advanced search, there you should be able to search for different foods. Please verify if this is what you are looking for. I haven't really used this feature much so if its lacking anything feel free to tell me :)

**Comment by stewartadam** [comment]
Correct, I missed the advanced search - thanks!
