### ISSUE TITLE
Show notes field during web import

### ISSUE THREAD

**Issue by stewartadam** [vabene1111/recipes#169]
**Is your feature request related to a problem? Please describe.**
When editing a recipe a 'notes' field is accessible next to each ingredient but the same field is not present during web import of a recipe. Often recipes have notes with alternative units or specifics e.g. `1 cup of bread flour (75 grams)` or more precise instructions (e.g. `1 red onion (finely chopped)` which ends up importing as *qty=1, unit=cup, ingredient=bread flour (75 grams)*.

It would be nice to be able to editing out the extra portion to properly map an existing ingredient like `bread flour` or `red onion` inline during import, but as it stands I have to save the recipe with the odd ingredients, edit the resulting recipe to migrate the `(parenthesis)` portion to notes, and then merge the imported ingredients against existing ones if they were not net-new ingredients.

**Describe the solution you'd like**
1. Notes field is present during web import

**Comment by vabene1111** [comment]
yes, thats definitely possible and should be done. I dislike the import and edit view being different views anyway but i think its to complicated to merge them completely. Maybe in the future, for now this can be added rather easily.
