### ISSUE TITLE
Add options to add nutritional values to the recipe. 

### ISSUE THREAD

**Issue by stormsz** [vabene1111/recipes#179]
It would be great if there was an option to add nutritional values to the recipes.
Right now I'm adding those values to the NOTES section of each recipe.

I realize this can get tricky because of the recently implemented feature that allow us to multiply the ingredients numbers, since I'm not a nutritionist I'm not sure if it as simple as say, if we have a recipe that as the ingredients for 1 people, setting that recipe for 2 people would mean that the nutritional value just multiplies by 2. We could get around that by simply displaying a "per serving" nutritional value instead of the total

A lot of recipes websites already offer such information so we can take some inspiration from them.
For some example that i think it would work with the layout of the recipe layout:

Minimal and has a cool feature if you hover the mouse over, lets say "Fat" it shows a description of what it is:
[square style that can easily be placed under the image](https://www.jamieoliver.com/recipes/peppers-recipes/sticky-miso-peppers/)

Minimal but still elegant and functional, also the "low in" is a nice feature:
[another shot at the "square style"](https://www.bbcgoodfood.com/recipes/blackberry-apple-loaf)

At the bottom, this is a somewhat "minimal" nutritional card:
[the classic nutritional card style](https://www.feastingathome.com/instant-pot-mujadara/)

At the bottom, this is a very complex and extensive nutritional card:
[text of the important nutritional stuff with a link to a full card](https://www.allrecipes.com/recipe/222247/vegan-black-bean-burgers/)

**Comment by vabene1111** [comment]
this is a good idea and not hard to implement!

**Comment by sebimarkgraf** [comment]
I would start working on this.
I would leave out the import for a different issue. 

Another thing we could check is calculating the nutrional values, but this seems not really doable due to different portion possiblities combined with all ingredient would be hard to check in a database.

**Comment by vabene1111** [comment]
i mean technically ingredients are objects in the DB and if you wanted you could add the value per unit. Some kind of feature that allows unit conversion is planned anyway for the future ... but i would start simple. 

Give it a go and if you need any help let me know. Dev branch is currently in a semi working state with the shopping list rework 😂
