### ISSUE TITLE
Fresh install redirects to https then dies

### ISSUE THREAD

**Issue by dukejustice** [vabene1111/recipes#181]
Hello dear community.

I am in trouble. I have followed this procedure to the letter and got no issue (https://github.com/vabene1111/recipes). Not even with database. I have no errors. docker logs -f on all containers come to everything ok, let's have connection sort of messages.

When I go to my url, http://192.168.0.77, I get redirected to https then an unable to connect page from the browser. Nothing in logs. redirect is not logged in recipes_nginx_recipes_1.

I do not know where to begin to diagnose this issue. Can some of you help me?

docker logs -f recipes_web_recipes_1

Updating database
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, cookbook, sessions
Running migrations:
  No migrations to apply.

0 static files copied to '/opt/recipes/staticfiles', 673 unmodified, 1242 post-processed.
Done
[2020-09-21 01:45:04 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-09-21 01:45:04 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2020-09-21 01:45:04 +0000] [1] [INFO] Using worker: sync
[2020-09-21 01:45:04 +0000] [12] [INFO] Booting worker with pid: 12

docker logs -f recipes_nginx_recipes_1

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

docker logs -f recipes_db_recipes_1

PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-09-21 01:34:47.774 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-09-21 01:34:47.775 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-09-21 01:34:47.791 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-09-21 01:34:47.835 UTC [21] LOG:  database system was shut down at 2020-09-21 01:32:29 UTC
2020-09-21 01:34:47.863 UTC [1] LOG:  database system is ready to accept connections

Any help would be very much appreciated.

Regards.

Marc.

**Comment by vabene1111** [comment]
Are you unable to connect because you run in a local network and dont have any certificate or does it show some kind of error code (e.g. 404, 400, 500, 502) ?

If you run the default setup and just nginx no automatic redirect should happen and it should bring you to port 80 on the nginx were the actual server runs. Do you by chance have some kind of browser plugin that redirects to https by default ?

Is there something in your router that might switch you to https or is there any reverse proxy running in front of your installation ?

**Comment by dukejustice** [comment]
Hello. Thank you for replying.

I have nothing. After the git clone... I added  postgres db password in
.env and that is it. Ran compose up and createsuperuser. No redirect plugin
on browser. No http code. White page with nothing in logs of all 3 rynning
containers. I am calling the webpage from its own virtualbox vm. Same
result from the host. No log verbose. Totally clean unedited gut clone from
develop branch (well ahead of master).

I have no router / reversed proxy of any kind... I have tried host only
network. Full reinstall. Same results.

May I look at other suggestions as to what or where to look?

Regards.

Marc.


Le lun. 21 sept. 2020 2 h 41 p.m., vabene1111 <notifications@github.com> a
écrit :

**Comment by vabene1111** [comment]
What lead you to choose the option to clone the repo to run it when you are using docker ? This was needed a while ago but is no longer, please take a look at https://github.com/vabene1111/recipes/tree/develop/docs
If this does not fix it please tell me which docker-compose you are using exactly.

Also running the development branch is definitely not recommended for a production setup. Although i have some fixes pending release there are also some breaking changes and migrations dont allow rollbacks so unless you know what you are up for i recommend staying on latest :)

**Comment by dukejustice** [comment]
Hello.

Thank you.

I still used the plain docker-compose offered as is. Retried after your reply and I am up with exactly the same result. Just a white page.

My wife acceptation factor tells me that I need this software to run. But I am new to compose.

Any other pointers I should look into?

Best regards.

Marc.

**Comment by vabene1111** [comment]
Hmm this is very interesting. I dont see what would possibly forward you to https/443 without running any kind of proxy in front or any plugin.

Which exact docker compose did you choose from the documentation ?

**Comment by dukejustice** [comment]
Hello again and thank you for staying with me!

I chose plain. As is. All I did is add a password for the DB in .env. I
swear I did nor used nothing else. Still in my VM with a totally clean and
fresh 20.04.1 Ubuntu.

Thank you.

Marc

**Comment by vabene1111** [comment]
Please try using different browsers and specifying the port in the url ( e.g. http://192.168.0.77:80 )

also please provide the output of docker-compose logs -f  without a container filter so everything is visible.

You can also try, just for testing, to access port 8080 to connect to gunicorn directly and see if that works.

**Comment by dukejustice** [comment]
Hello.

I did a fresh ubuntu 20.04.1 lts install in a virtualbox vm. Installed git, docker and compose. added a PW to .env and launched compose up -d. I now get an error 500 with these logs.

I accessed via 127.0.0.1 and tried with :8080 as well... 127.0.0.1 gives a 500 while 8080 yields a problem loading page firefox message

Here are the logs.

Thank you again for your help

`db_recipes_1     | The files belonging to this database system will be owned by user "postgres".
db_recipes_1     | This user must also own the server process.
db_recipes_1     | 
db_recipes_1     | The database cluster will be initialized with locale "en_US.utf8".
db_recipes_1     | The default database encoding has accordingly been set to "UTF8".
db_recipes_1     | The default text search configuration will be set to "english".
db_recipes_1     | 
db_recipes_1     | Data page checksums are disabled.
db_recipes_1     | 
db_recipes_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_recipes_1     | creating subdirectories ... ok
db_recipes_1     | selecting default max_connections ... 100
db_recipes_1     | selecting default shared_buffers ... 128MB
db_recipes_1     | selecting default timezone ... UTC
db_recipes_1     | selecting dynamic shared memory implementation ... posix
db_recipes_1     | creating configuration files ... ok
db_recipes_1     | running bootstrap script ... ok
db_recipes_1     | sh: locale: not found
db_recipes_1     | 2020-09-22 21:32:15.232 UTC [30] WARNING:  no usable system locales were found
db_recipes_1     | performing post-bootstrap initialization ... ok
db_recipes_1     | syncing data to disk ... ok
db_recipes_1     | 
db_recipes_1     | Success. You can now start the database server using:
db_recipes_1     | 
db_recipes_1     | 
db_recipes_1     | WARNING: enabling "trust" authentication for local connections
db_recipes_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_recipes_1     | --auth-local and --auth-host, the next time you run initdb.
db_recipes_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_recipes_1     | 
db_recipes_1     | waiting for server to start....2020-09-22 21:32:18.109 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_recipes_1     | 2020-09-22 21:32:18.147 UTC [36] LOG:  database system was shut down at 2020-09-22 21:32:16 UTC
db_recipes_1     | 2020-09-22 21:32:18.156 UTC [35] LOG:  database system is ready to accept connections
db_recipes_1     |  done
db_recipes_1     | server started
db_recipes_1     | CREATE DATABASE
db_recipes_1     | 
db_recipes_1     | 
db_recipes_1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_recipes_1     | 
db_recipes_1     | waiting for server to shut down....2020-09-22 21:32:18.845 UTC [35] LOG:  received fast shutdown request
db_recipes_1     | 2020-09-22 21:32:18.852 UTC [35] LOG:  aborting any active transactions
db_recipes_1     | 2020-09-22 21:32:18.857 UTC [35] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
db_recipes_1     | 2020-09-22 21:32:18.857 UTC [37] LOG:  shutting down
db_recipes_1     | 2020-09-22 21:32:18.893 UTC [35] LOG:  database system is shut down
db_recipes_1     |  done
db_recipes_1     | server stopped
db_recipes_1     | 
db_recipes_1     | PostgreSQL init process complete; ready for start up.
db_recipes_1     | 
db_recipes_1     | 2020-09-22 21:32:18.962 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_recipes_1     | 2020-09-22 21:32:18.962 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_recipes_1     | 2020-09-22 21:32:18.972 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_recipes_1     | 2020-09-22 21:32:19.029 UTC [46] LOG:  database system was shut down at 2020-09-22 21:32:18 UTC
db_recipes_1     | 2020-09-22 21:32:19.036 UTC [1] LOG:  database system is ready to accept connections
db_recipes_1     | 2020-09-22 21:32:33.598 UTC [53] ERROR:  relation "auth_user" does not exist at character 35
db_recipes_1     | 2020-09-22 21:32:33.598 UTC [53] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "auth_user"
db_recipes_1     | 2020-09-22 21:32:33.643 UTC [53] ERROR:  relation "auth_user" does not exist at character 280
db_recipes_1     | 2020-09-22 21:32:33.643 UTC [53] STATEMENT:  SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" LIMIT 21
nginx_recipes_1  | /docker-entrypoint.sh: /docke.r-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_recipes_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_recipes_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_recipes_1  | 2020/09/22 21:32:14 [emerg] 1#1: host not found in upstream "web_recipes" in /etc/nginx/conf.d/Recipes.conf:14
nginx_recipes_1  | nginx: [emerg] host not found in upstream "web_recipes" in /etc/nginx/conf.d/Recipes.conf:14
nginx_recipes_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_recipes_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_recipes_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_recipes_1  | 172.18.0.1 - - [22/Sep/2020:21:32:33 +0000] "GET / HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0". "-"
nginx_recipes_1  | 172.18.0.1 - - [22/Sep/2020:21:32:33 +0000] "GET /favicon.ico HTTP/1.1" 404 7106 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0" "-"
web_recipes_1    | Updating database
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_recipes_1    |     self.connect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
web_recipes_1    |     connection = Database.connect(**conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_recipes_1    | psycopg2.OperationalError: could not connect to server: Connection refused
web_recipes_1    | 	Is the server running on host "db_recipes" (172.18.0.3) and accepting
web_recipes_1    | 	TCP/IP connections on port 5432?
web_recipes_1    | 
web_recipes_1    | 
web_recipes_1    | The above exception was the direct cause of the following exception:
web_recipes_1    | 
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "manage.py", line 15, in <module>
web_recipes_1    |     execute_from_command_line(sys.argv)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
web_recipes_1    |     utility.execute()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
web_recipes_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
web_recipes_1    |     self.execute(*args, **cmd_options)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
web_recipes_1    |     output = self.handle(*args, **options)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
web_recipes_1    |     res = handle_func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
web_recipes_1    |     executor = MigrationExecutor(connection, self.migration_progress_callback)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_recipes_1    |     self.loader = MigrationLoader(self.connection)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
web_recipes_1    |     self.build_graph()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
web_recipes_1    |     self.applied_migrations = recorder.applied_migrations()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
web_recipes_1    |     if self.has_table():
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
web_recipes_1    |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
web_recipes_1    |     return self._cursor()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web_recipes_1    |     self.ensure_connection()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_recipes_1    |     self.connect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_recipes_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_recipes_1    |     self.connect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
web_recipes_1    |     connection = Database.connect(**conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_recipes_1    | django.db.utils.OperationalError: could not connect to server: Connection refused
web_recipes_1    | 	Is the server running on ho.st "db_recipes" (172.18.0.3) and accepting
web_recipes_1    | 	TCP/IP connections on port 5432?
web_recipes_1    | 
web_recipes_1    | 
web_recipes_1    | 673 static files copied to '/opt/recipes/staticfiles', 1915 post-processed.
web_recipes_1    | Done
web_recipes_1    | [2020-09-22 21:32:26 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_recipes_1    | [2020-09-22 21:32:26 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
web_recipes_1    | [2020-09-22 21:32:26 +0000] [1] [INFO] Using worker: sync
web_recipes_1    | [2020-09-22 21:32:26 +0000] [12] [INFO] Booting worker with pid: 12
web_recipes_1    | 172.18.0.2 - - [22/Sep/2020:21:32:33 +0000] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
web_recipes_1    | 172.18.0.2 - - [22/Sep/2020:21:32:33 +0000] "GET /favicon.ico HTTP/1.0" 404 7106 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"


The docker image (vabene1111/recipes) simply exposes the application on port 8080. You may choose any preferred installation method, the following are just examples to make it easier.
Docker-Compose

    Choose one of the included configurations here.
    Download the environment (config) file template and fill it out wget https://raw.githubusercontent.com/vabene1111/recipes/develop/.env.template -O .env
    Start the container docker-compose up -d
    Open the page to create the first user. Alternatively use 
`

**Comment by vabene1111** [comment]
Hmm there are definitely some errors in your log which normally should not be there. 

It looks like its related to the web application not being able to connect to the named database host (which is db_recipes). Sadly i cannot tell you what the cause of this issue is, if you have one of the example docker compose files it should definitely be working. Also the database server itself does not appear to have any problems (maybe run docker-compose ps to see if everything is up)

I am super short on time the next few weeks due to work and personal obligations, after that we can do a remote session if you still have the issue. Just write here if the problem still exists in about 2-3 weeks. Sry but faster is not possible atm.

**Comment by dukejustice** [comment]
Dear Vabene1111,

Thank you for such a display of altruism. Your plea for unavailability lead me to dig myself into my issue. I did a prune of everything and git cloned the plain compose file, got the .env and ended up with the same issue.

I then fell on your manual install page with the postgres operations to initialize the DB. I exec'ed into my DB container and psql'ed into djangodb user to \l, use and \dt... All was fine. 

Scratching my head to no avail, I had to reboot for another reason (vpn tunnel down). Upon startup... Doing no other configuration nor testing, my VM's Ubuntu with containers was working just fine. Just like it had been kickstarted by the DB login slash reboot.

Thank you again for your altruism. My WAF says the app is excellent. I will find a way to thank you in a way I can.

Best regards.

Marc.

**Comment by vabene1111** [comment]
dont worry about thanking me, glad you got it to work. 

I guess you fell for a typical IT Professional mistake where we think (me as well often) that "turning it off and back on again" does not work for us 😂 

hope you enjoy the app, if you have any wishes or suggestions feel free to let me know (there are several fixes and improvements already in the next release which should be coming very soon)
