### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#183]
Implement some kind of demo mode

- [x] disable external storage
- [x] disable system page
- [x] disable account settings change

Check out some free tier hosting to host demo

**Comment by stormsz** [comment]
Google free tier:
https://cloud.google.com/

- Compute Engine - 1 non-preemptible f1-micro, 30GB HDD, 5GB snapshot storage (restricted to certain regions)
---
Microsoft Azure free tier:
https://azure.microsoft.com/en-us/services/virtual-machines/

- 1 B1S Linux VM, 1 B1S Windows VM
---
Oracle Cloud free tier:
https://www.oracle.com/cloud/free/

- Compute - 2 VM.Standard.E2.1.Micro 1GB RAM
---
Alibaba Cloud free tier (lol):

- Compute - 1 ecs.t5-lc1m1.small for 12 months with 40 GB ultra cloud disk or SSD disk and 1 MB internet bandwidth.
- .tech Domain Name - Free to use for one year
---

there's also cheap vps's at https://lowendbox.com/ but there's some horror stories from these kind of providers. 

I think is possible (?) to make a static website and use stuff like jekyll or hugo and githubpages, but that is probably a lot of work just for a demo.
https://pages.github.com/

**Comment by vabene1111** [comment]
thanks very much for all the info. I have actually already setup a google cloud free tier instance but am very hesitent as to the restricted traffic and potential cost after exceeding it. Also traffic to australia and some other regions is not included at all.

I will checkout the other providers you linked. If there is anything completly free in there i might choose it, else i will probably rent an additional VM at hetzner where i host my private stuff ATM and put it there. Its 3€/Month but at least i know i wont get any big suprise bills 😂
