### ISSUE TITLE
Import/Export standards

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#19]
It appears there are certain standardized recipe markup languages that could be used to support interoperability and import/export of recipes.

**Comment by vabene1111** [comment]
After some research i found that meal master (see "spec" http://www.ffts.com/mmformat.txt) appears to be the most widely used standard for export/import of recipes (example http://www.garvick.com/recipes-ms/app01101.htm).

Meal Master is a very old standard and not parsable with any standard parsers (json/xml) and i dont really feel like writing importers and exporters currently. There is a project that has build importer/exporter in python 2, it can be found here https://github.com/thinkle/gourmet  

If someone writes or finds a good importer/exporter i will definitely implement it.

**Comment by mhoellmann** [comment]
Also an export to pdf would be nice. A layout similar to the recipe page would do the work. Than it would be possible to print some recipes to give them to persons which are using paper-based recipe books

**Comment by vabene1111** [comment]
the web page has the appropriate css classes set so that you can simply use your browsers print function to export a pdf. But i was thinking about adding a print button as well so that this is more obvious.

A real PDF export would probably require to build the complete view page agains and also maintain changes in both versions which adds a lot of overhead so i think that the current solution is the best way.

**Comment by vabene1111** [comment]
i have added a simple json import/export with the latest version (to be released), still help would be very much appreciated getting a parser for meal master up and running.

**Comment by Cludch** [comment]
Hey
I was wondering how the import of the json file works?

I made the mistake to use the SQLite even though I want to use a Postgres database.
Thus, I did a export of the SQLite instance through the webinterface. However, I cannot find a route or code reference on how to import the json file again.

**Comment by vabene1111** [comment]
that is correct! Thanks for updating the comment. This process definitly needs to be improved but for the time being this is the way to go

**Comment by vabene1111** [comment]
i have added a generic import/export module with support for multiple popular applications

to this date i have not heard anyone who wishes to import meal master so i will skip this for now but if anyone needs it just open an issue.
