### ISSUE TITLE
Internal server error 500 after reboot/manage.py staticfiles.json crash

### ISSUE THREAD

**Issue by mglubber** [vabene1111/recipes#198]
I had (multiple) host reboot due to some hardware/power issues, after which I couldn't access the recipes webserver (running as a docker container); it only showed an `Internal server error 500` page. After digging through the logs, I found that the `python manage.py collectstatic --noinput` during boot was causing an error (specifically, `ValueError: Couldn't load manifest 'staticfiles.json' (version 1.0)`).  I managed to fix the error by deleting the empty staticfiles.json and running the `collectstatic` command in the docker image; [somehow the staticfiles.json was emptied (only one blank line, not deleted), causing the application to crash](https://framagit.org/ideascube/ideascube/-/issues/829).

This seems to be a more general issue with django, not with recipes specifically, but I thought I'd record the issue here in case any one else is having the same problem. If you're interested, I can also try adding more error checking during/health checks for the docker images

**Comment by vabene1111** [comment]
hmm this sounds like a very interesting issue 🤔 

i have never really looked into how docker health checks work but i guess this would bee a good thing to look into for issues like this. If you want and know how it works feel free to submit a PR, otherwise i will leave this open so at some point someone can implement this.

**Comment by vabene1111** [comment]
closing this for now since this apparently never happend again. Will look into health checks in the future

**Comment by timdonovanuk** [comment]
FWIW I just randomly hit this. I upgraded the docker container from a very old version and this happened. Even recreating the container it happened again (not sure how). I had to shell into the web container and remove 'staticfiles.json'.

Cheers.

**Comment by Rustymage** [comment]
Just got hit with this. The quoted fixed it.

> FWIW I just randomly hit this. I upgraded the docker container from a very old version and this happened. Even recreating the container it happened again (not sure how). I had to shell into the web container and remove 'staticfiles.json'.
> 
> Cheers.

**Comment by slishak** [comment]
Also happened to me - staticfiles.json was empty, had to delete and recreate the container.

**Comment by renanmoretto** [comment]
also happened to me after restarting a vps with a django project running on docker
just had to delete the staticfiles folder and restart the container 
rm -rf staticfiles
docker restart project_name
