### ISSUE TITLE
Meal planning

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#20]
Someone suggested meal planning and i think that would fit into this application without making it to complex.

https://www.reddit.com/r/selfhosted/comments/eo2z2l/self_hosted_recipe_management_tool/fede82g/?context=3

**Comment by vabene1111** [comment]
baisc meal plan implemented but some nice QoL features missing

**Comment by vabene1111** [comment]
Further enhancements as suggested in https://www.reddit.com/r/selfhosted/comments/eo2z2l/self_hosted_recipe_management_tool/fmwav0r/

- [ ] make meals configurable (not everyone wants to plan breakfast)
- [ ] nice looking view only page (maybe in combination with #53 )

**Comment by mixedbreed** [comment]
Hi!
Would like to see the possibility to create a shoppinglist based on a week meal planning.
If the shoppinglist could also have the possibility with a easy delete per line that would be perfect!
Thanks for your effort!

**Comment by vabene1111** [comment]
yes, shopping lists from meal plan dates and meals are definitely something that i want to do, that was the main reason i created the shopping list in the first place. sadly the data structure is a little bit complex and i want to sort out some other structural changes first so it might take some time to implement.

**Comment by mixedbreed** [comment]
One more request would be to have a default measure per ingredient. Like water is liter, butter is gram and so forth.

**Comment by vabene1111** [comment]
you can open a separate issue for this but given the current architecture of the recipe editing page this would be pretty hard to do.

**Comment by vabene1111** [comment]
has been merged into #84
