### ISSUE TITLE
Recipe Linking

### ISSUE THREAD

**Issue by CorneliousJD** [vabene1111/recipes#203]
I think a way to link recipes would be great.

For example, if you have a recipe for a sauce/mirande that you make, you could easily reference the sauce recipe in another recipe. 

6 cups of :linked recipe: where it's a hyperlink to the other recipe so you can just easily click it and see how to make it.
There would need to be some form of interface that lets you select it from a dropdown just like you're selecting ingredients now. 

Right now seemingly the only way to do this is to have 2 differente steps on each recipe, one for the sauce, and the other for the rest of the recipe, but if you ever want to tweak your sauce recipe, and you use it in multiple dishes, you'd have to go back and tweak it on every single one. 

In my opinion this would be a low priority feature request, just thought it would be cool.
The OpenEats project which I've previously used has this feature, and it's handy!

**Comment by vabene1111** [comment]
so there is that one thing were you can add your sauce as an ingredient to a recipe and then go to the foods page where you can set a recipe for each food. 

I actually added that feature a while ago to be able to link dough that i use for several recipes. I hope this solves your problem but i guess i will have to make that feature somewhat more obvious to find. In general some proper integrated help would be very useful i guess 😂

**Comment by CorneliousJD** [comment]
Ah this makes sense, thank you for the explanation. Glad you already thought of it :)
