### ISSUE TITLE
System is saying I'm not running on Postgres when I am.

### ISSUE THREAD

**Issue by CorneliousJD** [vabene1111/recipes#204]
### Version
Version:  0.11.0

### Bug description

Setup in docker on unraid, and I opted to actually setup PostgreSQL instead of SQLite, and it tells me still that I am not running on Postgres for some reason, yet I can see tables being made, entries being modified live in the PostgreSQL database, so it's certainly running on PostgreSQL, yet warning that I'm not.

I AM running the ENV variable of 
DB_ENGINE = django.db.backends.postgresql
instead of django.db.backends.postgresql_psycopg2
My understanding is the _psycopg2 is old/unneeded at this point? 

If I change DB_ENGINE to "django.db.backends.postgresql_psycopg2" then it shows up as okay.
Perhaps there's a check somewhere in the looking for _psycopg2 when it's unnecessary?

See here: https://stackoverflow.com/questions/59395721/django-db-backends-postgresql-psycopg2-not-working-in-django-3-0
"The django.db.backends.postgresql_psycopg2 module is deprecated in favor of django.db.backends.postgresql. It’s been an alias since Django 1.9. This only affects code that imports from the module directly. The DATABASES setting can still use 'django.db.backends.postgresql_psycopg2', though you can simplify that by using the 'django.db.backends.postgresql' name added in Django 1.9."

![image](https://user-images.githubusercontent.com/724777/97125176-69acaa00-1709-11eb-9b1b-10ae2def3e33.png)

![image](https://user-images.githubusercontent.com/724777/97125207-8943d280-1709-11eb-8104-006f26e6881e.png)

**Comment by vabene1111** [comment]
thanks for the info. The check definitly checks for the old variable as this was the standard when i started this project. I will update the check to include both package names.

**Comment by vabene1111** [comment]
fixed in the upcoming release (by changing the default and having the check test for both values). There is no actual code that needs changing

**Comment by archedraft** [comment]
This issue appears to have come back in. I have been using environment var DB_ENGINE = django.db.backends.postgresql for some time now and it has given me the database OK. Within the last few months I get the yellow warning even though I am using postgresql. If I can the environment var to django.db.backends.postgresql_psycopg2 it gives me the green OK, but I am not sure if I should use that variable? Any chance you can check and see if the test is still working in the version below:

commit abf8f791360b2bc4a5c7d011877668679bcbb3f2
Author: vabene1111 
Date:   Sun Dec 3 14:10:28 2023 +0100

    Merge branch 'develop'

**Comment by smilerz** [comment]
Duplicate
