### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by hammermannman** [vabene1111/recipes#205]
If I want to import a recipe, I get this error message when saving:
Beim importieren der Webseite ist ein Fehler aufgetreten! <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>

the recipe is from: https://thequeenofdelicious.com

**Comment by vabene1111** [comment]
This is probably to malformed or weirdly formed recipes on that page. I will take a look at this.

The 500 error should not be there but it should show you a page telling you it could not import the recipe

**Comment by vabene1111** [comment]
closed together with #208 #215
