### ISSUE TITLE
Nextcloud cookbook import

### ISSUE THREAD

**Issue by hammermannman** [vabene1111/recipes#206]
Hey,
It would be very useful if you could import your recipes from your Nextcloud: https://apps.nextcloud.com/apps/cookbook

**Comment by l0c4lh057** [comment]
> is there any way to export recipes in nextcloud cookbook ? if so can you provide me with an example ?

There is not really an option to export the recipes. However in the settings you can change where they are stored and considering the set path as root directory `/` the recipes will be stored in `/{recipeName}/` which contains a `recipe.json` and, if the recipe has an image, `full.jpg` and `thumb.jpg`.

The `recipe.json` file follows the https://schema.org/Recipe structure.

**Comment by vabene1111** [comment]
i read (i think somewhere on reddit) that you can use the url import on the nextcloud recipes pages.

But maybe we can write an importer for schema.org/Recipes confirm json files

**Comment by vabene1111** [comment]
the next version will contain an import feature, exporting is still open
