### ISSUE TITLE
Markdown preview while editing

### ISSUE THREAD

**Issue by stewartadam** [vabene1111/recipes#207]
**Is your feature request related to a problem? Please describe.**
When editing a recipe, it would be nice to have a live markdown preview to avoid having to save+view repeatedly.

**Describe the solution you'd like**
An edit/preview tab like on GitHub comments

**Describe alternatives you've considered**
N/A

**Comment by vabene1111** [comment]
yes that would indeed be very nice. The reason this is not implemented yet is that markdown is currently renderd on the server and not on the client. This means that a preview would need to send the data to the server and get the rendered markdown returned. 

The other option would be to move markdown rendering to the client which is probably not to hard but means additional javascript and client computation. 

This is definitly something that needs to be looked at

**Comment by vabene1111** [comment]
there is a markdown preview with the new recipe editor, it does not apply the exact same rendering as the server but should suffice to give a rough indication on how the recipe is later rendered
