### ISSUE TITLE
New user Registration Page Confusion

### ISSUE THREAD

**Issue by Tmaxxrox97** [vabene1111/recipes#209]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version:  0.11.0

### Bug description

New user registration page has the field for Username listed as Name. This can be confusing as it causes new users to fill in their actual name rather than a username. A simple renaming of this header to Username would fix this issue.

Picture of Current Page
![image](https://user-images.githubusercontent.com/59188392/97512373-5c84fa80-1957-11eb-88a6-9b61b86cada8.png)

Picture of Suggested Edit
![image](https://user-images.githubusercontent.com/59188392/97512438-7fafaa00-1957-11eb-90a7-5653e4975364.png)

**Comment by Tmaxxrox97** [comment]
Additionally adding the First Name and Last Name Fields to this Page may be beneficial.

**Comment by Tmaxxrox97** [comment]
I looked through the files so I could try making a PR to change this but for the life of me I can't find the file that this form is created in. If someone could point me in the direction of where that file is I can make the change.

**Comment by vabene1111** [comment]
fixen in PR, thanks!
