### ISSUE TITLE
Option for the way images are displayed on the search page

### ISSUE THREAD

**Issue by FunWithUrban** [vabene1111/recipes#214]
It would be great if we had an option for the the way images are displayed on the search page. Currently it only looks good when the focal point of the image is the exact center. Most of my recipes are imported so for it to look good for me a lot of the time I would either need to edit the image or find a new one. Here's an example of what it can look like sometimes.

![Current](https://user-images.githubusercontent.com/73844982/98019850-40a6ac00-1dd0-11eb-968f-ad0cd06c6eba.png)

Option one would be to have squared images using your same format. From my experience square images show WAY more of the part of the image that you want to see. I think with this one being able to add more info from the recipe like what you do for prep time and keywords would also be beneficial because currently there is a lot of wasted space. Some examples I would like to see are specifying the source by text (Bon Appétit), recipe difficulty (Easy, Medium, or Hard), and a personal star rating out of five. Please mind my terrible photoshop skills but here's a quick mock up I did with the green boxes symbolizing where the recipe info would go but its basically the system you already use but with more options.

![new](https://user-images.githubusercontent.com/73844982/98026219-c6c6f080-1dd8-11eb-87b8-ed3a9e11bfe8.png)

The other option I would like to see is a grid based view of at least eight recipes horizontally where the important thing is just the name of the recipe and the image. This would be great for being able to quickly scan through all your recipes for ideas and it also just looks nice and would be nice to be able to switch back and forth. Here's how something like that would look (this is from Paprika Recipe Manager)

![Paprika](https://user-images.githubusercontent.com/73844982/98027233-5e790e80-1dda-11eb-867d-ad5fc2d8c2b4.png)

Thanks for putting the time into this, I'm really loving it so far!

**Comment by vabene1111** [comment]
thanks for the ideas, i had some difficulties getting the image to work correctly on different screen sizes but you are definitely right, this needs to be improved. A star rating is already possible by the way buy "logging cooking". The info texts are something i wanted to do for a while but did not get around to yet so its good that you wrote an issue for it !

**Comment by FunWithUrban** [comment]
Thats great to hear, glad we are on the same page.

**Comment by vabene1111** [comment]
closed in favor of main search rewrite issue
