### ISSUE TITLE
Language Change?

### ISSUE THREAD

**Issue by palitu** [vabene1111/recipes#23]
Whilst i  appreciate the (Assuming) german... is there any translations?

ta

**Comment by vabene1111** [comment]
i forgot to add djangos locale middleware which led to only the default language (which was german) to be displayed. I added it so now english or german should be choosen depending on your browser preferences. 

In case any other languages are needed someone would need to provide them as i only speak english and german.

**Comment by palitu** [comment]
you're a gentleman and a scholar!

thanks.
