### ISSUE TITLE
Request Heimdall Integration

### ISSUE THREAD

**Issue by sebimarkgraf** [vabene1111/recipes#240]
**Is your feature request related to a problem? Please describe.**
Heimdall is often used for private servers to have all applications at one glance.
Adding a integration for recipes would allow to automatically recognize the name and style it fitting to the application

**Describe the solution you'd like**
A request can be made here: https://apps.heimdall.site/request/create.
This needs a logo in the right format.

**Describe alternatives you've considered**
It is always possible to style it as user, but it's easier for users if the integration is done automatically.

**Additional context**
I'm not sure how fixed the logo is and if it works well for something like this.

**Comment by sebimarkgraf** [comment]
@vabene1111 as the logo has been fixed, I would go ahead and create the request. Is that ok with you?

**Comment by vabene1111** [comment]
sure, thank you. Sry that i havn't gotten around to doing so, there are just so many enhancement ideas that i simply cant keep up 🙈

**Comment by sebimarkgraf** [comment]
I have requested the integration and it can be now seen here: https://apps.heimdall.site/request#343eebd3e9330c34952dcb3bc5c94ba12bf07a67

The project is really picking up interest. Can I somehow support you?

**Comment by vabene1111** [comment]
thank you very much. Help is always very much appreciated. What you can do depends on your skills. If you know your way around python feel free to tackle any issue you come across. If you prefer something else the documentation could definitely use some love.

Other than that helping people with setup issues is also something that takes a lot of time.

**Comment by vabene1111** [comment]
but dont feel obligated to do anything, if you like it and use it its already awesome :)

**Comment by sebimarkgraf** [comment]
FYI
My PR was merged and the integration to heimdall is complete.
