### ISSUE TITLE
Allow to adjust date for cooking log

### ISSUE THREAD

**Issue by sebimarkgraf** [vabene1111/recipes#243]
**Is your feature request related to a problem? Please describe.**
When recording cooking always the current date is used. This works for most use cases, but especially when checking the next day or adding it 1 week later it would be useful to adjust the date.

**Describe the solution you'd like**
An additional field when creating a cooking log prefilled with "Today"

**Describe alternatives you've considered**
Not adding it is probably fine as well, but then the last cooked information could be off.

**Comment by vabene1111** [comment]
i have run into this many times myself .. to be honest the whole cook log/rating feature was added without much thought and is honestly not great (there is not even feedback if rating worked).

This will be reworked completely and your feature will be implemented as well when doing so

**Comment by vabene1111** [comment]
![2021-01-13_18-08](https://user-images.githubusercontent.com/6819595/104485103-5dc6da80-55ca-11eb-9aea-f7b608bcf23b.gif)

Will be implemented in the next release (which might be a little of as its quite big
