### ISSUE TITLE
Import format for recipes

### ISSUE THREAD

**Issue by MatthK** [vabene1111/recipes#258]
Sorry for the probably stupid questions, but as I couldn't find any kind of documentation. 

### Version
I just setup a docker container using the vabene1111/recipes:latest image and got it up and running. It says it's version 0.12.0

### Issue
I have no clue where to start. How do I import a recipe? What format does it need? Are there any templates of those JSON files? Is there software to create the JSON from some other format?
And can I just add a folder on a network drive as I neither have Dropbox nor Nextcloud.

I tried the "Configure Sync", but there's nothing to select on the Storage drop down, and I'm not quite sure what kind of Path I'd have to enter. Is that a path on the host of the docker?

### `.env`
```
DEBUG = 0
ALLOWED_HOSTS = *
SECRET_KEY = Not showing 
TIMEZONE = ASIA/HONG_KONG
FRACTION_PREF_DEFAULT =| 0
COMMENT_PREF_DEFAULT = 1
SHOPPING_MIN_AUTOSYNC_INTERVAL = 5
GUNICORN_MEDIA = 0
REVERSE_PROXY_AUTH = 0
```

**Comment by vabene1111** [comment]
there is no such thing as a stupid question and your questions come from my insufficent documentation/help which i did not have time to properly add (yet).

1. the sync backends currently only work with nextcloud and dropbox (as that is what i use). It is pretty easy to expand to new providers but i currently dont have the time to write the modules required for that. (if you know your way around python you will just need to copy the dropbox or nextcloud helpers and create a "network drive" one and add some entries here and there [this process definitely needs documentation 🙈 ])
2. recipes can be imported when previously exported or from websites containing microdata or ld+json data. 
3. to create a manual recipe simply press the new button (three dots next to search), give it a name and get going

i hope this helps, if you have any further questions feel free to ask

**Comment by MatthK** [comment]
Thanks, that was quick. And I just created my first recipe. Quite a nice and simple interface. I guess I'll have to check again the setup and once I have installed it properly with a database I'll most likely will give that a try. It looks worth it to replace my lose recipe collection.

And unfortunately I'm no good with python at all. But adding the recipes manually shouldn't be the issue.
