### ISSUE TITLE
Installation help needed

### ISSUE THREAD

**Issue by cyberius0** [vabene1111/recipes#260]
Hello,
this is what I did on my Raspberry 3+:

- installed docker
- docker pull vabene1111/recipes
- docker container run vabene1111/recipes

But I can't access anything on port 8080 (page doesn't load)

Do I need those additional steps ("Choose one of the included configurations here.
Download the environment (config) file template and fill it out wget https://raw.githubusercontent.com/vabene1111/recipes/develop/.env.template -O .env") ?

I don't understand them. Where do I have to put that .env file? Where do I have to put that docker-compose.yml / ngix.conf file?

Sorry, but I hope you can help me :)

**Comment by vabene1111** [comment]
yes you indeed need to follow the instructions provided in the readme.

download the docker-compose to a directory of your choice and put the .env file and the nginx folder in the same directory. 

Then configure the .env file to your liking and run docker-compose up -d
