### ISSUE TITLE
[Request] Ingredient categories for recipes

### ISSUE THREAD

**Issue by l0c4lh057** [vabene1111/recipes#269]
**Is your feature request related to a problem? Please describe.**
Sometimes it is nice to have categories for the ingredients for one recipe. For example for pizza you could have a category for the dough, one for the tomato sauce and one for the topping.

**Describe the solution you'd like**
(I don't know how data is stored, but let's just assume it is JSON.) Instead of storing the ingredients as
```json
{
  "ingredients": [
    {"amount": 3, "unit": "tbsp", "name": "olive oil"},
    {"amount": 5, "unit": "cloves", "name": "garlic"}
  ]
}
```
they could be stored as
```json
{
  "ingredients": {
    "dough": [
      {"amount": 3, "unit": "tbsp", "name": "olive oil"}
    ],
    "tomato sauce": [
      {"amount": 5, "unit": "cloves", "name": "garlic"}
    ]
  }
}
```
Then the website would sort the ingredients by category and show the category name at the top of the sublist.
Optionally it could be implemented to only add ingredients from specific categories to the shopping list.

This option would not consider category order since (afaik) JS(ON) objects are unordered. To also have the possibility to order categories they could be stored like this instead:
```json
{
  "name": "tomato sauce",
  "ingredients": [...]
}
```
These category objects would then be stored in a list.

**Additional context**
Examples:
- https://www.jamieoliver.com/recipes/bread-recipes/basic-pizza/ (which I used as example in the introduction)
- https://www.chefkoch.de/rezepte/1305881235547779/Kuerbisstrudel.html (note how there also is one unnamed category, this could for example be a category with the name `default` which is just not displayed on the front-end)

**Comment by vabene1111** [comment]
isn't this exactly what steps do ?

I mean the shopping list integration is missing, you can only add everything but apart from that everything should be there (there is a special type of ingredient called a header btw).

**Comment by vabene1111** [comment]
There is also the option to link a recipe in an ingredient. I have pizza where the dough is an ingredient that is linked. You do so by going into the foods menu, lookup the ingredient and there add a recipe

**Comment by l0c4lh057** [comment]
Oh yeah, sorry, I overlooked that. Guess debugging for hours straight isn't good for me.

**Comment by vabene1111** [comment]
haha no worries, glad i could help :)
