### ISSUE TITLE
Few quick questions about the docker image

### ISSUE THREAD

**Issue by edcous** [vabene1111/recipes#270]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.12.1

### Issue
Please describe your problem here

Hello! I set this software up tonight on my VPS, and had a few questions. It is telling me I have no secret key set in the .env file, but doesn't django automatically generate one if I don't provide one? Also, is there a reason a .env file is used instead of just having environment variables in the docker compose?

I'm running the regular vabene1111/recipes image btw.

**Comment by vabene1111** [comment]
django does not generate a random one and if it did so all sessions would expire on every restart (which is kind of annoying).

the .env file is used for easier communication of what needs to be done and to be compatible with different kinds of deployment, you can always choose to move all variables to the docker compose file directly.

I hope i could help, if you have any further questions feel free to ask

**Comment by edcous** [comment]
Thanks so much for the reply! I'm actually using this thing called https://caprover.com which is why I can't just open up the .env file and I have to configure it in the UI. I'll try setting it there! Thanks!

**Comment by edcous** [comment]
It worked, closing now 👍
