### ISSUE TITLE
Put recipe rating stars in a wrapper element

### ISSUE THREAD

**Issue by l0c4lh057** [vabene1111/recipes#271]
### Version
Version: 0.12.1

### Bug description
Right now the rating for recipes is inside the title like this
```html
<h3>
  recipe title
  <i class="fas fa-star da-xs"></i>
  <i class="fas fa-star da-xs"></i>
  <i class="fas fa-star da-xs"></i>
</h3>
```
This causes weird breaks of the rating on small screens

Example:
![grafik](https://user-images.githubusercontent.com/42084688/102716004-3a658400-42d9-11eb-8fcb-0fac3a5d755b.png)

Instead the rating should be wrapped in one element that goes on the next line instead of only some stars.

What seems to work for me:
```html
<h3>
  recipe title
  <span style="display: inline-block;">
    <i class="fas fa-star da-xs"></i>
    <i class="fas fa-star da-xs"></i>
    <i class="fas fa-star da-xs"></i>
  </span>
</h3>
```

This example above applies to the page of the recipe itself. The same also applies to the recipe overview (in search). While I think it would not be an issue in the recipe overview of a cookbook I'd say it'd be good to make it the same everywhere and also do the same there.

I could not get this working on my local machine on which I'd test stuff like this, so it is an issue and not a PR.

**Comment by vabene1111** [comment]
The recipe sounds delicious and the fix seems good! Thanks for reporting.

**Comment by cyberius0** [comment]
How do you add rating stars? I don't see any. Version: 0.12.1

**Comment by l0c4lh057** [comment]
I have to agree, that is not very obvious. I also had to search again right now. But when clicking on the three dot menu for a recipe (works both in the recipe view and the main/search view) you can click `Log Cooking` and then add a rating.
