### ISSUE TITLE
500 server error when importing certain site

### ISSUE THREAD

**Issue by edcous** [vabene1111/recipes#276]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.12.1

### Bug description

When importing https://www.feastingathome.com/orecchiette-pasta-with-broccoli-sauce/ I get a 500 server error: ```An error occurred while trying to import this recipe! <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>```

**Comment by edcous** [comment]
Here's another example: https://cooking.nytimes.com/recipes/1019034-garlic-braised-short-ribs-with-red-wine

**Comment by vabene1111** [comment]
ok since i can import the recipe myself i will guess that this is the same problem as #208
