### ISSUE TITLE
Unintuitive keywords label in website import

### ISSUE THREAD

**Issue by l0c4lh057** [vabene1111/recipes#278]
### Version
Version: latest master clone (2020-12-20, just shows 0.0.0 in dev setup)

### Bug description
When importing a website the checkbox to import all keywords and not just those that already exist is a bit weird. The text above `All Keywords` is the label to the checkbox that is one line below whereas the text right next to the checkbox is no label. That was a bit irritating to me because usually you can just click the text next to a checkbox to check it which did not work here but when looking at the source code there was a label. I did not even consider the title as label until I saw it. Imo the text right to the checkbox should be the label. The title can be a label too but doesn't have to be (idk if there are any accessibility guidelines saying something about multiple labels for one checkbox)

![grafik](https://user-images.githubusercontent.com/42084688/102915469-2ad56f00-4482-11eb-8915-c10a40d33bc5.png)

**Comment by l0c4lh057** [comment]
Just checked and it seems that google lighthouse also flags elements with multiple labels ([Source](https://web.dev/form-field-multiple-labels/)). Then I'd say the `All Keywords` texts should not be a label and only the text next to the checkbox should be.

**Comment by vabene1111** [comment]
that definitely makes sense/sounds reasonable. I will change that in an upcoming release, i personally prefer checkboxes that have clickable text as well but i honestly never use the keyword import thats why i never noticed 😂
