### ISSUE TITLE
Improvements for English texts

### ISSUE THREAD

**Issue by l0c4lh057** [vabene1111/recipes#284]
### Format

`original text` (transifex id)
comment

### Current issues/potential improvements I found:

`Default user to share newly created meal plan entries with.` (5)
If I understand it correctly this is a field where you can input users to share recipes with by default. Then imo something like this would be better:
`Users with whom newly created meal plan entries should be shared by default.`

`Scaling factor for recipes` (38)
Should get changed to `Servings` as soon as the PR for that is merged.

`You cannot interact with this object as its not owned by you!` (42)
`it is` or `it's`

`Imported from ` (45)
Either remove the space and add it to the template or make the url a variable of the text. Since spaces are hard to see it will happen that it will just go missing, as it was the case with German.

Difference between tags and keywords?
`Tags` is used (68) but also `Keyword` (69). Are they used as synonyms or is there a difference between them? If there is not then they should be unified.

`Markdown Help` (83)
Maybe `Markdown Guide`, but tbh `Markdown Help` is ok too.

`On this Page you can manage all storage folder locations that should be monitored and synced`
This really is a proper sentence that should get a period at the end imo.

`The path must be in the following format` (94)
Should have a colon at the end, either in the template html or the translation.

`Are you sure that you want to merge these two units ?` (159)
`Are you sure that you want to merge these two ingredients ?` (161)
PLEASE remove the space in front of the question mark!

`Are you sure you want to delete the %(title)s: %(object)s`
Missing the question mark at the end.

### Additional

I currently checked the first half of the strings on transifex and will check the other half soon. I will just edit this comment to add more.

And couldn't you use keys like `settings.share.defaultUsers` instead of the actual string in English? Then it would be easier to fix the English "translation". At least I hope you can set transifex up to show you the English version as original instead of the key.

**Comment by vabene1111** [comment]
Ok so i have added all changes in the comment above. Please do not edit the comment as i would loose track of what is already done and what not. Just add a new one and reopen it.

Regarding the Translation System: I originally started coding with android where the translation system is based on identifiers (like your proposed settings.share.xyz). When i started django i was confused that it is apparently standard to have the whole text as the identifier. This is very practical and easy for me as the developer both because i do not have to create any resources and because i can read everything directly in the code. Also there is no context and translations are done starting from the key (and not from the value as in android for example) thus i think we have to stick to this method.

But you are right, it makes fixing stuff in the original language kinda hard.

**Comment by l0c4lh057** [comment]
Yeah, I would have created a new comment here instead of editing the original one, I just thought I'd get to it earlier. But Christmas was *Christmas-ier* than I thought it would be so I did not got to that.

`Log in to view Recipes` (191)
`Log in to view recipes`

```
        Markdown is lightweight markup language that can be used to format plain text easily.
        This site uses the Python Markdown library to
        convert your text into nice looking html. Its full markdown documentation can be found
        here.
        An incomplete but most likely sufficient documentation can be found below.
```
(193)
I'd capitalize the `html` to `HTML`

`This text is in italics` (199)
Even tho that is correct I'd use `This text is italic`

`Lists can ordered or unorderd.` (202)
`Lists can be ordered or unordered.`

`This applicaiton also` (208)
Misspelled `application`

`This will become and Image` (209)
`This will become an image`

`Markdown tables are hard to create by hand. It is recommended to use a table editor like <a ...>this</a> one.` (211)
I'd put the `<a>` tag around `this one` instead of just `this`. Also the tag should have the `rel="noreferrer noopener"` property.

`Shopping List currently empty` (223)
`Shopping list currently empty`

`The meal plan module allows planning of meals both with recipes or just notes` (237)
`The meal plan module allows planning of meals both with recipes and notes`

`Creating only Notes is possible` (237)
`Creating notes is possible`

`order to open the detail view. Here you` (237)
`order to open the detailed view. There you`

`To start using this application you must first create a superuser.` (276)
I'd add `account` at the end because you don't create a superuser but a superuser account.

`Create Superuser` (277)
Same as above

`You are offline, shopping list might not sync.` (283)
Either `synced` or `synchronized`/`synchronised`

`Import all Keywords not only the ones already existing.` (320)
`Import all keywords, not only the ones already existing.`


These are all I found right now after going through all of the entries on transifex.

**Comment by l0c4lh057** [comment]
Seems like I can't reopen the issue. Either that or I just forgot how to do it. But would be nice if you could do that again @vabene1111

**Comment by vabene1111** [comment]
thanks for reporting all those issues. I have tried to fix them all and not break the localization at the same time

**Comment by l0c4lh057** [comment]
I just opened transifex again and it seems like you forgot to update `This will become and image` (`and`→`an`). Will check the others too later but this is the one I just spotted right now.

**Comment by vabene1111** [comment]
Hmm i dont think i collected english but i thought i replaced everything directly in the localized files 🤔 will have to check if everythging went trough on transifex

**Comment by vabene1111** [comment]
ok i had forgotten/overlooked this one. It will be fixed in the next release
