### ISSUE TITLE
Redirect to login

### ISSUE THREAD

**Issue by hcientist** [vabene1111/recipes#292]
**Is your feature request related to a problem? Please describe.**
When I visit the site while unauthenticated, I see `Log in to view Recipes`, and esp. on mobile this is not very helpful.

**Describe the solution you'd like**
I'd like it to be easier to login when necessary.

**Describe alternatives you've considered**
1. I'd at least like [the `Log in to view Recipes`](https://github.com/vabene1111/recipes/blob/bb48655acb084e94c1fdc985c6636ff716850bd5/cookbook/templates/index.html#L94) to be a login link, but 
2. ideally, we'd use a redirect for when not logged in [1](https://stackoverflow.com/a/45139393/1449799)[2](https://docs.djangoproject.com/en/3.1/topics/auth/default/#the-loginrequired-mixin)

**Additional context**
Thanks for sharing your work. This project looks interesting.

**Comment by vabene1111** [comment]
there should at least be a link in the "you have to login" info box i guess 😂 since the session timeout is quite high i never really thought about that

**Comment by vabene1111** [comment]
fixed with correct redirects in next release
