### ISSUE TITLE
Seed data (food, ingredient, unit, else)?

### ISSUE THREAD

**Issue by hcientist** [vabene1111/recipes#294]
**Is your feature request related to a problem? Please describe.**
Not a problem, per se

**Describe the solution you'd like**
I would like for a fresh install to be more immediately useful.

**Describe alternatives you've considered**
1. Perhaps the developer or other experienced users would be willing to share their food, ingredient, and/or unit tables/data? Just as a link in this repo's wiki?
2. Perhaps such data could be committed to the repo as [initial Django data](https://docs.djangoproject.com/en/3.1/howto/initial-data/)?

**Additional context**
It seems that at least in a locale-specific way, there may be common staples that users might enjoy not entering manually.

**Comment by vabene1111** [comment]
As you have already mentioned, since everything is locale specific i did not provide any inital data. I guess people could post .json files with their data `manage.py dumpdata cookbook.food` or others and upload them to a discussion. Others could then import them using the `loaddata` command.
