### ISSUE TITLE
Display yield of recipe

### ISSUE THREAD

**Issue by MarioPinto** [vabene1111/recipes#300]
**Is your feature request related to a problem? Please describe.**
I think it would be nice if the **yield** of a recipe (e.g., 24 cookies, 1 loaf, 2L sauce, enough for a large pizza,... ) would be imported/displayed as well.

**Describe the solution you'd like**
The yield is automatically imported when using the URL import functionality or can be entered manually in a field just like prep and waiting time.  (using the recipeYield property I guess)

**Describe alternatives you've considered**
Currently I am writing it down in the recipe instructions field but this is just a work around.

![Screenshot 2021-01-01 at 12 32 36](https://user-images.githubusercontent.com/2913438/103437942-957a6d80-4c2d-11eb-9591-97417240d0a6.png)

**Additional context**
I think that this is partially linked to https://github.com/vabene1111/recipes/issues/197 although the focus there is on scaling the recipe using the yield.
In my use case I really just want to know what I am objectively getting from the recipe.

**Comment by vabene1111** [comment]
Servings have been added on the dev branch in the last few days. They allow to specify an arbitrary yield but do not currently allow you to specify the unit of the yield (e.g. pcs, cookies,..)


I was thinking on how to add that as well and how to properly display it

I think the release will be out in a few days once I have tested it a little more

**Comment by vabene1111** [comment]
the next release also adds the option to set a custom text for servings e.g. Pcs, Loafs, whatever
