### ISSUE TITLE
Allow sorting shopping list by category of item

### ISSUE THREAD

**Issue by edcous** [vabene1111/recipes#306]
**Is your feature request related to a problem? Please describe.**
When at the store it's nice to be able to have everything in each area of the store (ex. produce, bakery, meat, etc.) in categories on the shopping list.
**Describe the solution you'd like**
Add an option to drag each item on the shopping list to different categories for easy purchasing while in the store.

**Comment by vabene1111** [comment]
categories is an intereseting idea in the shopping list. I usually order mine. 

The idea was to have food categories which can be assigned to foods and the shopping list would automatically order the items according to the supermarket you configured.

Would that be something that would be ok for you or do you think a visual distinction in categories is required ?

**Comment by edcous** [comment]
Hmm the auto ordering is interesting, I can just see that getting very complicated in terms of all the different sites people use in different countries, as well as some people still do like to shop in person (after Covid). Of course I understand you do all this for free so please don't feel obligated to implement this. I personally think it would be a good idea to still allow sorting by category though.

**Comment by vabene1111** [comment]
i definitly want to allow sorting by category. 

The only question is do you think that it is required that the shopping list has a visual distinction of the categories or that all entries are just a big list ordered by category.

**Comment by edcous** [comment]
I’d say I personally think it should be an option on the shopping list as well.

**Comment by mikensan** [comment]
> 
> 
> i definitly want to allow sorting by category.
> 
> The only question is do you think that it is required that the shopping list has a visual distinction of the categories or that all entries are just a big list ordered by category.
> 
> Ordering the categories themself afterwards is then optional and depending on where you shop.

I think a little space may be enough between groupings, but if that ends up being the same amount of effort then sure the name of each category as a divider is nice. Extra bonus would be to edit an item's category directly from the list so as you creating shopping lists you can categorize all the ingredients over time.

**Comment by vabene1111** [comment]
yes, i will need to build some kind of modal anyway for the ingredients as i dont feel like switchting between the pages so that could be integrated into the shopping list page as well.

So i have a rough idea on what this feature should look like, now i just need to get around to actually implementing it 😂

**Comment by vabene1111** [comment]
this feature has been implemented for the next release. I hope you like it, its not super polished but very powerful in my opinion.
