### ISSUE TITLE
Add Directory Storage Backend Provider

### ISSUE THREAD

**Issue by jakobwenzel** [vabene1111/recipes#310]
Hi!

It would be great to be able to specify some raw directory as Storage Backend Provider. Users could point this to their actual data location or use some sync tool to get the files there.

Like #117 this would require supporting providers without a sharing interface.

Cheers,
Jakob

**Comment by vabene1111** [comment]
yes, i originally did not have this implemented because the whole reason of the storage providers was to use external storage (as i run a very cheap VPS) but local storage is definitly needed.

I want to combine it with a webinterface for fileuploads and at least some basic management functions (like storage limits, editing and deleting tough, so its a bigger feature)

**Comment by vabene1111** [comment]
added local storage with the next update, feel free to try it out and give me some feedback once its released

**Comment by jakobwenzel** [comment]
Thank you for implementing this! I updated to the docker beta image to try this out. Discovery, Importing and Viewing Recipes works perfectly.

However, viewing the Sync Log errors out:

> Environment:
> 
> 
> Request Method: GET
> Request URL: https://redacted/list/sync-log/
> 
> Django Version: 3.1.6
> Python Version: 3.8.7
> Installed Applications:
> ['dal',
>  'dal_select2',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.sites',
>  'django.contrib.staticfiles',
>  'django_tables2',
>  'django_filters',
>  'crispy_forms',
>  'emoji_picker',
>  'rest_framework',
>  'rest_framework.authtoken',
>  'django_cleanup.apps.CleanupConfig',
>  'webpack_loader',
>  'django_js_reverse',
>  'allauth',
>  'allauth.account',
>  'allauth.socialaccount',
>  'cookbook.apps.CookbookConfig']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'whitenoise.middleware.WhiteNoiseMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.locale.LocaleMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'recipes.middleware.CustomRemoteUser']
> 
> 
> Template error:
> In template /opt/recipes/cookbook/templates/generic/table_template.html, error at line 30
>    function lower(timestamp with time zone) does not exist
> LINE 1: ...og"."created_at" FROM "cookbook_synclog" ORDER BY LOWER("coo...
>                                                              ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> 
>    20 :                                         {{ column.header }}
>    21 :                                     {% endif %}
>    22 :                                 </th>
>    23 :                             {% endfor %}
>    24 :                         </tr>
>    25 :                         </thead>
>    26 :                     {% endif %}
>    27 :                 {% endblock table.thead %}
>    28 :                 {% block table.tbody %}
>    29 :                     <tbody {{ table.attrs.tbody.as_html }}>
>    30 :                      {% for row in table.paginated_rows %} 
>    31 :                         {% block table.tbody.row %}
>    32 :                             <tr {{ row.attrs.as_html }}>
>    33 :                                 {% for column, cell in row.items %}
>    34 :                                     <td {{ column.attrs.td.as_html }}>
>    35 :                                         {% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}
>    36 :                                             {{ cell|localize }}{% else %}{{ cell|unlocalize }}
>    37 :                                         {% endif %}{% endif %}</td>
>    38 :                                 {% endfor %}
>    39 :                             </tr>
>    40 :                         {% endblock table.tbody.row %}
> 
> 
> Traceback (most recent call last):
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> 
> The above exception (function lower(timestamp with time zone) does not exist
> LINE 1: ...og"."created_at" FROM "cookbook_synclog" ORDER BY LOWER("coo...
>                                                              ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> ) was the direct cause of the following exception:
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
>     return view_func(request, *args, **kwargs)
>   File "/opt/recipes/cookbook/views/lists.py", line 39, in sync_log
>     return render(
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
>     content = loader.render_to_string(template_name, context, request, using=using)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
>     return template.render(context, request)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
>     return self.template.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
>     return self._render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
>     return self.nodelist.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
>     return compiled_parent._render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
>     return self.nodelist.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
>     result = block.nodelist.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django_tables2/templatetags/django_tables2.py", line 167, in render
>     return template.render(context={"table": table}, request=request)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
>     return self.template.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
>     return self._render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
>     return self.nodelist.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
>     result = self.nodelist.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
>     result = self.nodelist.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
>     result = self.nodelist.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
>     bit = node.render_annotated(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
>     return self.render(context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 168, in render
>     len_values = len(values)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django_tables2/rows.py", line 325, in __len__
>     length = len(self.data)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
>     self._fetch_all()
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
>     cursor.execute(sql, params)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
>     return super().execute(sql, params)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> 
> Exception Type: ProgrammingError at /list/sync-log/
> Exception Value: function lower(timestamp with time zone) does not exist
> LINE 1: ...og"."created_at" FROM "cookbook_synclog" ORDER BY LOWER("coo...
>                                                              ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
>

**Comment by vabene1111** [comment]
ah ok, i have not tested that. I will check it out

**Comment by vabene1111** [comment]
ok that is interesting, i cannot reproduce this issue in my local setup. 
What is your configuration for the local provider ?
are you using docker ?

**Comment by jakobwenzel** [comment]
For me it is reproducible on every call.

I have a single Local Storage Backend configured with `/` as path, and one Watched Folder with `/externalrecipes` as path.

I am using Docker. This is the docker-compose snippet for the recipes container:
```
  recipes_web:
    image: vabene1111/recipes:beta
    container_name: recipes_web
    restart: always
    networks:
      - t2_proxy
    env_file:
      - ./recipes/.env
    volumes:
      - ./recipes/staticfiles:/opt/recipes/staticfiles
      - ./recipes/mediafiles:/opt/recipes/mediafiles
      - ./recipes/external:/externalrecipes:ro
    depends_on:
      - recipes_db
```
I also use Reverse Proxy Auth.

**Comment by jakobwenzel** [comment]
I had one file with the character "ö" in its filename in the directory. However, renaming it does not change the error.

**Comment by vabene1111** [comment]
Ok this issue was actually not related to the new local provider at all but the import log itself was broken for every type of external storage 🙈 

This should be fixed with the upcoming release
