### ISSUE TITLE
Missing translations even if translated

### ISSUE THREAD

**Issue by auanasgheps** [vabene1111/recipes#313]
### Version
Version: 0.13

### Bug description
Hey there, thanks for the latest update.
Since I've done the Italian translation I was doing a check to see how it goes. 
Well I've found many missing translations even if they have been already translated.

For example this one was translated 2 months ago.
![image](https://user-images.githubusercontent.com/20586878/103643012-46497b00-4f54-11eb-9d79-23d5947f0b86.png)

![image](https://user-images.githubusercontent.com/20586878/103642952-2fa32400-4f54-11eb-91f7-3be26d17a926.png)

The translation is available in the [code ](https://github.com/vabene1111/recipes/blob/develop/cookbook/locale/it/LC_MESSAGES/django.po)as well
![image](https://user-images.githubusercontent.com/20586878/103643377-dd163780-4f54-11eb-8373-448b4d333986.png)

This is just an example, I've found several like this one.
Additionally I haven't found strings for these settings
![image](https://user-images.githubusercontent.com/20586878/103643105-6711d080-4f54-11eb-9f55-06d5bfb97c99.png)

**Comment by vabene1111** [comment]
very interesting. Normally this is related to me forgetting to compile the language files but i tought it did it this time ..

i will need to better automate the translation process 🤔 
i will look into this asap

**Comment by vabene1111** [comment]
ok this has been solved. The issue was that forms apparently cannot use gettext directly but must use gettext_lazy for translations.

I guess this is related to the user context not being accessible to the form during Initiation
