### ISSUE TITLE
Plain Docker install errors due to volumes

### ISSUE THREAD

**Issue by KyleWJohnston** [vabene1111/recipes#317]
### Version
Version: 0.12.1

### Bug description
I really like the new documentation! Much cleaner. However, I'm having issues with the plain Docker install. I can run the application without issue using the old method via `Recipes.conf` file for nginx, but with the new method I can't get the `web_recipes` and `nginx_recipes` containers to run. I think it's related to the new volumes structure. I tried fixing a few issues and submitted a PR (#316) with the changes.

#### Issue 1
After configuring `.env` and creating `docker-compose.yml` from the plain Docker configuration, I run `docker-compose up -d` and get this:
```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here in "./docker-compose.yml", line 38, column 13
```

I added colons to `nginx` and `staticfiles`:
```diff
volumes:
<   nginx
<   staticfiles
---
>   nginx:
>   staticfiles:
  mediafiles:
```

#### Issue 2
I ran `docker-compose up -d` again and this time got this:
```
ERROR: Named volume "nginx_config:/opt/recipes/nginx/conf.d:rw" is used in service "web_recipes" but no declaration was found in the volumes section.
```

I changed `nginx` to `nginx_config`:
```diff
volumes:
<   nginx:
---
>   nginx_config:
  staticfiles:
  mediafiles:
```

#### Issue 3
After running `docker-compose up -d`, this time I got this:
```
Creating network "my_recipes_dir_default" with the default driver
Creating my_recipes_dir_db_recipes_1 ... 
Creating my_recipes_dir_nginx_recipes_1 ... error

Creating my_recipes_dir_db_recipes_1    ... done
flags: 0x1000: no such file or directory
Creating my_recipes_dir_web_recipes_1   ... error

ERROR: for my_recipes_dir_web_recipes_1  Cannot start service web_recipes: error while mounting volume '/var/lib/docker/volumes/my_recipes_dir_mediafiles/_data': failed to mount local volume: mount /home/myhomedir/docker/my_recipes_dir/mediafiles:/var/lib/docker/volumes/my_recipes_dir_mediafiles/_data, flags: 0x1000: no such file or directory

ERROR: for nginx_recipes  Cannot create container for service nginx_recipes: failed to mount local volume: mount /home/myhomedir/docker/my_recipes_dir/mediafiles:/var/lib/docker/volumes/my_recipes_dir_mediafiles/_data, flags: 0x1000: no such file or directory

ERROR: for web_recipes  Cannot start service web_recipes: error while mounting volume '/var/lib/docker/volumes/my_recipes_dir_mediafiles/_data': failed to mount local volume: mount /home/myhomedir/docker/my_recipes_dir/mediafiles:/var/lib/docker/volumes/my_recipes_dir_mediafiles/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

Probably more detail than needed, but I'm still learning Docker. Hopefully none of the assumptions above are wrong. Hopefully this helps someone figure out the issue.

**Comment by vabene1111** [comment]
i messed that up, sry! Looks like your PR fixes all the issues.

I will close this and have further discussion in the PR

**Comment by KyleWJohnston** [comment]
Thanks for the quick feedback and awesome web app! The PR fixes issues 1 and 2 above, but not issue 3.

**Comment by vabene1111** [comment]
really ? 
thats intereseintg .. it should not have any problems creating those volumes ...

I will have to do a test on that

**Comment by vabene1111** [comment]
This appears to be related to the fact that when using bind mounts docker compose does not create the folder automatically when the volume is definied as a named volume in the volumes section but does so when the bind mount is defined on the service. 

I feel like this whole bind mount and volumes thing is increadibly stupid but i am pretty sure that someone has a good reason that i simply do not yet understand. 

The intermediate fix would be to just use a volume for mediafiles as well but that feels like giving up :/

**Comment by vabene1111** [comment]
ok so i have updated the config file. 

I just used the bind mount syntax directly in the container volume and it appears to be working. Please let me know if you have any further trouble

**Comment by KyleWJohnston** [comment]
Sorry, forgot to confirm this worked for me and close the issue. Changing the config worked perfectly for me. Thanks a ton for all your work with this app!

**Comment by vabene1111** [comment]
glad you like it and thanks for reporting back :) have fun and stay safe
