### ISSUE TITLE
Ingredients scaling should not go to 0 or negative.

### ISSUE THREAD

**Issue by charleszlu** [vabene1111/recipes#325]
### Version
Version: 0.13.0

### Bug description
When scaling ingredients, the counter should not be able to go to 0 or negative.

**Comment by vabene1111** [comment]
you are correct. There was a PR not long ago but i think merging servings reverted some of the changes. 

While this is nice its not really something important so only classified as enhancement, will fix it when i get around to it.

Note to future self: Make sure 0.XY is supported
