### ISSUE TITLE
Tag removing from URL import not working correctly

### ISSUE THREAD

**Issue by HenrikGeiger** [vabene1111/recipes#337]
### Version
Version: 0.12.1

### Bug description
Tag removing from URL import not working correctly. 
While importing an recipe from url (e.g. https://www.chefkoch.de/rezepte/1932511314682960/Eierkuchen-bzw-Pfannkuchen.html) I can edit the recipe. If I want to remove a tag always the first or second tag is removed, although if I click on remove button from the last tag.

I suspect this is not intentional? If you need more information about this bug please feel free to ask

**Comment by vabene1111** [comment]
i think i have never actually tested this as i usually dont import tags ... i have some ideas on what could cause this
