### ISSUE TITLE
[Feature] Linking recipes

### ISSUE THREAD

**Issue by l0c4lh057** [vabene1111/recipes#338]
**Is your feature request related to a problem? Please describe.**
Some recipes are just a base for something else. For example a marinara sauce might be something you need in multiple recipes. Or maybe for pizza you create a recipe for each topping to make it more organized than just adding them all to one recipe. Then you don't want to include the base recipe needed for all of them (marinara sauce or pizza dough) in every single recipe needing them.

**Describe the solution you'd like**
One idea I have is that you can add another recipe as an ingredient. Then when you have a recipe for pizza dough that has a yield of 8 pizza bases you can add 1 pizza dough as ingredient and it will automatically add 1/8 of the pizza dough ingredients to the shopping list when you add the pizza recipe itself to the shopping list. The `1 pizza dough` will just get replaced by `(amount needed / yield of dough recipe) * base amount of the ingredient in the dough recipe` for every ingredient in the dough recipe.
Also in the steps at first the steps of the linked recipe are shown. I have added an example below.

_Pizza dough recipe_
![grafik](https://user-images.githubusercontent.com/42084688/104859016-44ec5b00-5923-11eb-9dfb-314b4fee6dc1.png)

_Pizza Speciale recipe in edit mode_
![grafik](https://user-images.githubusercontent.com/42084688/104858973-25edc900-5923-11eb-8632-cd3387b5da36.png)

_Pizza Speciale recipe when viewed_
![grafik](https://user-images.githubusercontent.com/42084688/104859225-fdb29a00-5923-11eb-85ae-2986df088c8f.png)

**Describe alternatives you've considered**
Currently you can link to another recipe like `[some text](recipe id)`, so when marinara sauce has the id `5` it would be something like `[first you need to make marinara sauce](5)`. That does not have any integration tho with the shopping list or showing the instructions right on the same page.

**Comment by vabene1111** [comment]
so there is currently no shopping list integration (which is a cool idea) but you can have a recipe as an ingredient. Simply add the ingredient "Pizza dough" and then open the ingredient list, search for it and open it. There you can set a recipe for that ingredient that will be shown as a link in the ingredient list.

i have updated issue #114 to integrate that into the shopping list in the future.
