### ISSUE TITLE
Apache2

### ISSUE THREAD

**Issue by ameralzarouni** [vabene1111/recipes#339]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: Latest

### Issue
Please describe your problem here: Is it possible to use this with apache instead of nginx?

**Comment by vabene1111** [comment]
Yes, you can do everything nginx can with apache (as far as i know) 

The recipes container simply exposes port 8000, you can put any webserver in front of that. Make sure to have it also serve the media files. Please refer to the documentation for further details.

**Comment by tdvantine** [comment]
Did you ever get this working @ameralzarouni? Looking at doing the same.

**Comment by ameralzarouni** [comment]
I managed to use apache as a reverse proxy for the container (exposing port 8000 on my domain) but I have no idea how to have it server the media files. 
I put my work on hold because I got busy, tho I'll try a reinstall soon.

**Comment by vabene1111** [comment]
i have no idea how apache works but there should be a way to configure a directory to be served under a certain path

**Comment by ameralzarouni** [comment]
Yes, it can server a certain directory, which directory should I server for the media files? and under which path? (Sorry if this is a stupid question, but I'm new to this)

**Comment by vabene1111** [comment]
no worries the directory is called `mediafiles` and the path should be `/media/recipes/`

**Comment by ameralzarouni** [comment]
Where are files for docker containers located?

**Comment by vabene1111** [comment]
the mediafiles directory inside the container is located in `/opt/recipes/mediafiles/recipes/image.png` but you need to use the volume mount anyway to mount into the apache container

**Comment by ameralzarouni** [comment]
I lost hope trying to set this up with apache, so I ended up trying the default options. When I try running the docker command as it is with no modifications, I get: 
`OperationalError at /

could not translate host name "db_recipes" to address: Name does not resolve`

When I tried the plain docker-compose, I get:
`502 Bad Gateway
nginx/1.19.8`

Can't seem to get any to work :(

**Comment by ameralzarouni** [comment]
I lost hope trying to set this up with apache, so I ended up trying the default options. When I try running the docker command as it is with no modifications, I get: 
`OperationalError at /`
`could not translate host name "db_recipes" to address: Name does not resolve`

When I tried the plain docker-compose, I get:
`502 Bad Gateway`
`nginx/1.19.8`

Can't seem to get any to work :(

**Comment by vabene1111** [comment]
when trying the default version did you use the exact docker-compose file i provided for it ? The error say that it cant find the database container, is that container present and online ?

**Comment by ameralzarouni** [comment]
Yes I used the docker-compose you provided. It includes this in it:
`db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env`

**Comment by vabene1111** [comment]
where does your apache run ? is the web_recipes container in the same file as the db_recipes one.

Please post detailed information describing you setup since i cannot help you otherwise or just use the default setup because that usually works best.

**Comment by ameralzarouni** [comment]
I'm not running apache, I gave up on that. I'm trying to run it with the default nginx it comes with.

**Comment by vabene1111** [comment]
please open a new issue and describe the steps you did along with some basic information about your system. I simply canot help you with the information you have given me so far.
