### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by Zazou89** [vabene1111/recipes#342]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.13.0

### Issue
I don't understand few things in the application : 

In Meal Plan, I don't understand how to add a recipe in a day. Can you explain me ? 
![image](https://user-images.githubusercontent.com/206181/105079630-fc05e500-5a8f-11eb-9e69-2e3c02941ad3.png)

In a recipe page, why I have this symbol in red ? 
![image](https://user-images.githubusercontent.com/206181/105079743-222b8500-5a90-11eb-9586-a4df414c827b.png)

And what is the field on the right ?

Thank you !

**Comment by vabene1111** [comment]
1. you first need to add one or more meal types (in the box at the bottom right), then simply drag the meals onto the plan.
2. the red things are just icons, dont worry about them
3. the boxes are for times. If you specify minutes for each step you can say when you start and it will calculate the starting time of other steps (useful for baking for example).

The whole UI will be reworked with the next update

**Comment by Zazou89** [comment]
Okay thank you :)

**Comment by eTaurus** [comment]
Sorry for opening this issue again. Should I be seeing these icons @Zazou89 encircled i red even after saving the recipe? See attached screenshot for reference.
![grafik](https://user-images.githubusercontent.com/24603992/105575346-37900000-5d6b-11eb-9f0b-6cf834e1fb7f.png)
Even when giving a step a name this icon does not disappear.
It seems that the option "Show as header" respectively "Hide as header" does not work for me. Is it even possible to have a step without a caption/header?

**Comment by vabene1111** [comment]
no, each step has a name. If the name is empty it will be "Step X" and if it has a name it will be the name.

**Comment by eTaurus** [comment]
Okay, I understand. But why am I seeing this icon?

**Comment by vabene1111** [comment]
The icon is just one that i set in the code because i thought it looked good .. i am not the best in terms of design and the whole recipe view will be refactored with the next update.
