### ISSUE TITLE
Use unaccent to make search easier

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#344]
It would be nice to use the [Unacccent Feature](https://www.postgresql.org/docs/current/unaccent.html) in Postgres, that way if you search for "Crepe" the application would also show the recipe "Crêpe".

At the moment it is required to enter the correct accent in order to get the recipe.

**Comment by vabene1111** [comment]
really ? i tought the django trigram similarity feature would solve this .. but this sounds like a really good (and probably easy to implement) idea, thanks for the suggestion!

**Comment by Forceu** [comment]
I guess that is because it can limit performance on big databases. I suppose it should be fine for this use case? https://docs.djangoproject.com/en/3.1/ref/contrib/postgres/lookups/

**Comment by vabene1111** [comment]
i think that should be fine, who has more than a few thousand recipes ..

**Comment by vabene1111** [comment]
ok i have added the unnaccent filter to the lookup but as its a postgresql feature it only works with that database backend
