### ISSUE TITLE
Edit servings during website import

### ISSUE THREAD

**Issue by bobokun** [vabene1111/recipes#349]
**Is your feature request related to a problem? Please describe.**
When importing from a website, after the import I have to edit the recipe if I want to change the servings (it defaults to 1). 

**Describe the solution you'd like**
I would like to be able to modify the servings amount prior to submitting a recipe that's being imported from a website.

**Describe alternatives you've considered**

**Additional context**

**Comment by vabene1111** [comment]
yes this has not yet been added as servings a relatively new .. will add this asap

**Comment by bobokun** [comment]
I think you've done a great job with this application and I've only recently started using it. I didn't know that the servings option was new so I thought this was just a bug that was missed. Thank you for creating this application and enhancing it! I look forward to the updates

**Comment by vabene1111** [comment]
no worries, feedback is always welcome. Dont hesitate to write an issue with you ideas, the worst that can happen is that we decide to close it or maybe that i forget it for a long time 😂
