### ISSUE TITLE
Emoji Picker Issue

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#35]
ERROR: django-emoji-picker 0.0.5 has requirement django<3,>=2, but you'll have django 3.0.3 which is incompatible.

**Comment by vabene1111** [comment]
Issue in library https://github.com/wdr-data/django-emoji-picker/issues/3

**Comment by palitu** [comment]
It also looks like if you try and assign a keyword with no emoji, it spits the dummy when you try and open the recipe.

**Comment by vabene1111** [comment]
the last thing sounds like it is related to #38 which will be fixed in the next release.

If not please open a seperate issue with an exact explanation on how to reproduce the issue.

**Comment by vabene1111** [comment]
fixed in library Version 0.0.6
