### ISSUE TITLE
Passwords incorrect for user created invite links

### ISSUE THREAD

**Issue by bobokun** [vabene1111/recipes#350]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.13.0

### Issue
Please describe your problem here
When generating an invite link and trying to create a new user, after the user gets created I can't login with the password that was entered. ("Your username and password didn't match. Please try again.")

However modifying the password from the Django administration page works and I can login.

**Comment by vabene1111** [comment]
that sounds like a bug somewhere, i will test it and get back to you

**Comment by bobokun** [comment]
Found another bug.
When creating a password through the invite link it allows you to create any password even if it doesn't satisfy the rules that are in Django admin page.

Your password can’t be too similar to your other personal information.
Your password must contain at least 8 characters.
Your password can’t be a commonly used password.
Your password can’t be entirely numeric.

**Comment by vabene1111** [comment]
both fixed in the next release, the two issues were related.
