### ISSUE TITLE
Wrong size in the form inside the ingredients

### ISSUE THREAD

**Issue by cesarblancg** [vabene1111/recipes#353]
### Version
Version: 0.13.0

### Bug description
On my screen(1366x768) I can't see the numbers in the form inside the layout of the ingredients. 

I solved it by changing the CSS and bootstrap elements inside the ingredients. I searched inside the project searching where is it created and make a pr, but I didn't see anything.

Screenshot of the error: https://photos.app.goo.gl/31CYoD3nvR9SBWmQA
Changes applied: https://photos.app.goo.gl/cB24StX2TYtLa8BTA
Video with my changes: https://photos.app.goo.gl/8fQRdeBuZFV7iZaG9

**Comment by vabene1111** [comment]
yes this was a problem i had a few times as well. The recipe view hast been refactored for the next update so this is no longer a problem. Thanks for reporting

**Comment by vabene1111** [comment]
![image](https://user-images.githubusercontent.com/6819595/105633438-dc3c3b80-5e58-11eb-9c5d-455d5719c4de.png)
