### ISSUE TITLE
Add Image to Meal Plan

### ISSUE THREAD

**Issue by Ronalaus** [vabene1111/recipes#361]
Automatically add image from the recipe to the meal plan.

Example:
![Meal_Plan_Suggestion](https://user-images.githubusercontent.com/24578158/106070742-e6a94000-60b9-11eb-8813-3cdbd65f80dc.png)

Thanks for the amazing work on this!

-Ronalaus

**Comment by vabene1111** [comment]
i definitly want to improve the esthetics of the meal plan but it is very difficult to not screw up the UI for mobile and desktop.

I guess when i move the meal plan to the new vue component system i will take a look at making images show at least on desktop

**Comment by vabene1111** [comment]
meal plan is currently being reworked with the image in mind
