### ISSUE TITLE
BUG: Nutritional info duplicated on database

### ISSUE THREAD

**Issue by cesarblancg** [vabene1111/recipes#363]
### Version
Version: beta ([commit](https://github.com/vabene1111/recipes/commit/96146a388a7c98b0bd09c3f7e417ce0f8c0b627a))

###Bug
When you edit a recipe and save it, the database will create new nutritional info without erasing the old. 

I only have 3 recipes, but I edited it, so now I have 13 nutritional info on my database. 

I attached a video :)

https://user-images.githubusercontent.com/29866109/106134405-c6838a80-6166-11eb-962e-fb8209aff39f.mp4

**Comment by vabene1111** [comment]
fixed with the next update, the ID was missing from the API
