### ISSUE TITLE
Default credentials? 

### ISSUE THREAD

**Issue by thewismit** [vabene1111/recipes#369]
### Issue
Does this require an authentication backend? I've not found the default credentials anywhere in the documentation. 

Thank you.

**Comment by thewismit** [comment]
Whoops! I found this

```
Create a default user by executing into the container with docker-compose exec web_recipes sh and run python3 manage.py createsuperuser.
```
However I get the following error

`python3 manage.py createsuperuser
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`

**Comment by vabene1111** [comment]
when you launch the application for the first time the website should display a form that allows you to create a new superuser account. From there you can create new accounts in the admin or use proxy authentication (and from next release on also OAuth)
