### ISSUE TITLE
gitignore project files

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#37]
when setting up a new dev environment .idea files seem to be missing.

**Comment by h4llow3En** [comment]
the .idea folder is located in the .gitignore

In my opinion this should be that way.

**Comment by vabene1111** [comment]
as far as i remember jetbrains official docs there are certain files that should and should not be ignored. My other django repos work fine so i will just have to see where the difference in the ignore is .. i have already made one change but haven't gotten around to testing it

**Comment by h4llow3En** [comment]
Yes and no. It is correct that some files could be included if you want others to have the same configuration as in your IDE.

I just offered my opinion. 🙂

**Comment by vabene1111** [comment]
thank you very much for your opionion, always welcome :) 

i was refering to this article https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems 

i will fix it the following few days ..

**Comment by vabene1111** [comment]
it appears the changes already made were sufficient to fix the issue.
