### ISSUE TITLE
Error creating superuser 

### ISSUE THREAD

**Issue by thewismit** [vabene1111/recipes#370]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 

### Issue
When trying to create default superuser I get this

python3 manage.py createsuperuser
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

If you need the env and compose files I can get them for you. I'm in my phone at the moment and can't copy and paste over my ssh session :(

What I did to install was follow the instructions for docker-compose except I'm not using the nginx container as I'm already running a reverse proxy using caddy. 

The site loads fine. I just can't create the superuser. 

Thank you!

**Comment by vabene1111** [comment]
do you try to create the superuser via the console or are you using the web interface ?

**Comment by thewismit** [comment]
I went into docker-compose exec

**Comment by thewismit** [comment]
also, I didn't clone the repository. I created the directory, set the environment file and docker compose yall and then ran docker-compose up -d.

Is that the problem?

**Comment by enrico-kaack** [comment]
@thewismit the django application is running inside the container in an virtual env (see https://github.com/vabene1111/recipes/blob/7ebf4d5e2a38f1be8399d38a11fa90b45646ecc6/Dockerfile#L13 ). In order to run the manage.py, you have to open a shell in the container and activate that virtual environment. It should work in the following way:

1. Create a shell in the running container:
```
docker-compose exec web_recipes sh
```
2. Activate the virtualenv named venv in the folder venv (/opt/recipes/venv)
```
source venv/bin/activate
```
3. Run your python migrate.py commands:
```
python manage.py
 ```

**Comment by thewismit** [comment]
Aha! I don't know how I missed the activation of the virtual environment step. Thank you.

FYI this is what I had to run

/opt/recipes # source /venv/bin/activate
sh: source /venv/bin/activate: not found
/opt/recipes # ls
CONTRIBUTERS.md   makemessages.cmd  recipes
SECURITY.md       manage.py         requirements.txt
boot.sh           mediafiles        setup.sh
cookbook          mkdocs.yml        staticfiles
docker_buildx     nginx             venv
/opt/recipes # ls venv/bin/
Activate.ps1      dotenv            pip3
__pycache__       easy_install      pip3.8
activate          easy_install-3.8  python
activate.csh      gunicorn          python3
activate.fish     icalendar         sqlformat
chardetect        markdown_py       wdc
django-admin      microdata.py
django-admin.py   pip
/opt/recipes # source venv/bin/activate
sh: source venv/bin/activate: not found
/opt/recipes # whereis source
sh: whereis: not found
/opt/recipes # cd venv
/opt/recipes/venv # cd bin
/opt/recipes/venv/bin # source ./activate
(venv) /opt/recipes/venv/bin # python3 manage.py createsuperuser
python3: can't open file 'manage.py': [Errno 2] No such file or directory
(venv) /opt/recipes/venv/bin # cd ../../
(venv) /opt/recipes # ls
CONTRIBUTERS.md   makemessages.cmd  recipes
SECURITY.md       manage.py         requirements.txt
boot.sh           mediafiles        setup.sh
cookbook          mkdocs.yml        staticfiles
docker_buildx     nginx             venv
(venv) /opt/recipes # python3 manage.py createsuperuser
Username (leave blank to use 'root'): thewismit
Email address: will@thewismit.com
Password:
Password (again):
Superuser created successfully.

**Comment by thewismit** [comment]
Thank you for your help, this is working now.
