### ISSUE TITLE
Rest Api: Duplicated Schema Definitions

### ISSUE THREAD

**Issue by enrico-kaack** [vabene1111/recipes#371]
### Version
Version: main-latest

### Bug description

When using the API, the user encounters several duplicated schemas that are named differently when embedded in other schemas. The cause for those duplicated schemas is a duplication of the schema definition (instead of a reference) if embedded in another schema.

This makes it cumbersome to work with auto-generated clients based on the openapi spec:

Ingredients - Recipe.ingredients (generates a RecipeIngredients model with the same content)
Keyword - Recipe.keywords
Step - Recipe.steps
(probably some more)

**Describe the solution you'd like**
A correct schema definition for a correct client code generation.

**Comment by vabene1111** [comment]
discussed and irrelevant or at least the drawbacks of the currently taken approach are out weight by the the benefits
