### ISSUE TITLE
Serious Eats Recipe Import

### ISSUE THREAD

**Issue by lspgs** [vabene1111/recipes#376]
**Is your feature request related to a problem? Please describe.**
Adding support to import recipes from seriouseats.com Example recipe URL: https://www.seriouseats.com/recipes/2011/12/serious-eats-halal-cart-style-chicken-and-rice-white-sauce-recipe.html

**Describe the solution you'd like**
Import recipes for this domain similar to other recipe sites.

**Comment by smilerz** [comment]
There is a project with a large number of recipe scrapers [here](https://github.com/hhursev/recipe-scrapers).

**Comment by vabene1111** [comment]
many pages are already supported but only if they provide some kind of machine readable dataset of recipes which is either ld+json or micordata.

What is interesting is that seriouseats does provide ld+json but the parser does not pick it up. I will need to investigate what goes wrong here.
