### ISSUE TITLE
Update docker container to include port configuration

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#377]
I currently have docker containers running on 80 & 8080.
It would be nice to be able to change the behavior without manual intervention.

**Comment by vabene1111** [comment]
you can add whatever port mapping you desire in the docker compose file so the container exposes for example 8181 

Or what is the problem here ?

**Comment by smilerz** [comment]
> you can add whatever port mapping you desire in the docker compose file so the container exposes for example 8181
> 
> Or what is the problem here ?

I was referring to the .env file to modify the container you published

**Comment by vabene1111** [comment]
i dont really understand ? do you want to expose gunicorn to another port directly ?

I dont see why that would be required because boot.sh is only run in dockerized deployments and those can specifiy the port mapping 🤔

**Comment by smilerz** [comment]
> i dont really understand ? do you want to expose gunicorn to another port directly ?
> 
> I dont see why that would be required because boot.sh is only run in dockerized deployments and those can specifiy the port mapping 🤔

I barely understand docker - so maybe I'm doing something wrong.  Let me fiddle with it some more and I'll open a new issue if it is something other than just me.
