### ISSUE TITLE
TypeError when viewing recipe

### ISSUE THREAD

**Issue by chetwisniewski** [vabene1111/recipes#38]
I entered a recipe successfully, but once I added tags to it, I can no longer view it getting a TypeError. I have attached the full error message 

[TypeError at _view_recipe_1.zip](https://github.com/vabene1111/recipes/files/4335442/TypeError.at._view_recipe_1.zip)

Request Method: | GET
-- | --
http://recipes.zuzax.com/view/recipe/1
3.0.4
TypeError
unsupported operand type(s) for +: 'NoneType' and 'str'
/Recipes/cookbook/models.py in <listcomp>, line 102
/usr/bin/python3
3.6.9
['/Recipes',  '/usr/local/bin',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Mon, 16 Mar 2020 00:32:27 +0100

**Comment by chetwisniewski** [comment]
This occurs when no icon is selected. If you use an emoji it works.

**Comment by vabene1111** [comment]
fixed in upcoming release
