### ISSUE TITLE
RezKonv import/export

### ISSUE THREAD

**Issue by Tuetenk0pp** [vabene1111/recipes#380]
**Read the conversation here: #375**

### So, there is actually two things that relate to this:

**1. import RezKonv recipes and export them**
I will supply information about the RezKonv fomat once i receive it from the developer.
I do however have a copy of an RezKonf export from a different application, which might not be a correct representation of the RezKonf format: [RezepteRezKonv-Format.txt](https://github.com/vabene1111/recipes/files/5910426/RezepteRezKonv-Format.txt)

**2. import RezKonv cookbooks and export them**
There are some example downloads on the developer's website. Here is one of them: [auflaeufe.zip](https://github.com/vabene1111/recipes/files/5910222/auflaeufe.zip)
They usually contain three files, all with the same name but different extensions as shown in the example. Unfortunately I couldn't get to open them properly with vs code, so there might be an issue with encoding.

### Edit 1:
I updated the supplied RezKonv recipe export

**Comment by Tuetenk0pp** [comment]
This is the RezKonv [website](https://www.rezkonv.de/software/rksuite/index.html)

**Comment by Tuetenk0pp** [comment]
Here is the promised details about the rezkonv format. I hope you speak german @vabene1111 😆 let me know if you need help with the translation
[rezkonv.pdf](https://github.com/vabene1111/recipes/files/5961173/rezkonv.pdf)

**Comment by vabene1111** [comment]
German is no problem but this is a huge spec... I will take a look at it and see if it's worth writing an importer for it

**Comment by vabene1111** [comment]
ok even tough the docs start with "the format was invented to be easily understandable and not require any documentation" and follows with 18 pages of docs i have got the importer working 😂 

its actually working quite well. Since meal master is very similar i will probably add that as well.
