### ISSUE TITLE
Das kleine Rezeptbuch import/export

### ISSUE THREAD

**Issue by Tuetenk0pp** [vabene1111/recipes#381]
Here is how [Rezeptbuch](https://www.wboeck.de/download.htm) stores a recipe: 
[RezepteExport.zip](https://github.com/vabene1111/recipes/files/5910453/RezepteExport.zip)

**Comment by vabene1111** [comment]
thanks 👍 

just as a general note, i am not particularly good a writing parsers so i might add a module that can be expanded with different providers over the time.

**Comment by Tuetenk0pp** [comment]
no pressure! I just read in the roadmap that you would like to add these things.

Btw: you have an awesome project going on here 👍 so far I really like it, especially the batch editing capabilities. Keep it up!

**Comment by vabene1111** [comment]
ok so i have taken a look at the example data you provided. sadyl it is in a binarized format which i cannot import.
Is there any other way to export data from the application ?

**Comment by Tuetenk0pp** [comment]
Actually yes. You can export to the RezKonv format #380 mentioned in this post. I have more information on that which I will post there.

**Comment by vabene1111** [comment]
ok then i will close this one and implement both with #380 might also take a look at meal master again
