### ISSUE TITLE
Icon web app on Apple devices

### ISSUE THREAD

**Issue by cesarblancg** [vabene1111/recipes#385]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version:  beta

### Bug description
The Icon web app on iPad pro doesn't appear. 

I searched info and founded this:
_To specify multiple icons for different device resolutions—for example, support both iPhone and iPad devices—add a sizes attribute to each link element as follows_
font:
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by vabene1111** [comment]
thanks for closing, i thought github did it automatically as it was mentioned in the merged PR (it used to do that anyway 🤔 )
