### ISSUE TITLE
Improvment of Dockerfile

### ISSUE THREAD

**Issue by cesarblancg** [vabene1111/recipes#387]
When Docker build the image, It uses Cache if the layer didn't change. In the actual Dockerfile, you COPY the entire project before install all the requirements, so every time you change a line in your code, Docker has to install all the requirements again. 
More info about how docker uses the cache:
https://pythonspeed.com/articles/docker-caching-model/

**Comment by vabene1111** [comment]
interesting, i have tried doing exactly this just a few weeks ago but it failed as far as i remeber .. or at least the image size increased dramatically from ~40MB to around 180 

but if you got it working that would be awesome. I will check it out and get back to you, thanks !

**Comment by cesarblancg** [comment]
I tried it and didn't saw a different size.

**Comment by vabene1111** [comment]
perfect, thanks for the feedback 👍
