### ISSUE TITLE
Image path wrong in recipe view

### ISSUE THREAD

**Issue by tdvantine** [vabene1111/recipes#392]
### Version
Version: Beta (docker)

### Bug description
Images load fine in the cookbook view, but once clicking on the recipe the image fails to load. I have gone through past issues, but all of them were ALL images failed to load, this is only on recipe page. I followed the link and for me it is missing the port number. 
![image](https://user-images.githubusercontent.com/56764154/107709714-e3e64780-6c82-11eb-9d30-42c67ab20f75.png)
Right clicking, open image in new tab takes me to the correct path, minus the port number. Manually adding it load the image.

**Comment by vabene1111** [comment]
Ok so you host your setup under a non standard port ?

Can you post the links that are shown if you right click the images and "copy image addresss" ? The images render differently (one with django, one with javascript) depending on the view (in the beta).
i guess things like this are the reason why many pages use a setting to define the site url

**Comment by tdvantine** [comment]
Cookbook View: http://10.0.30.30:9030/media/recipes/a74ccb6b-a3d6-4ed3-8e04-8d02b1d6b423_7.png

Recipe View: http://10.0.30.30/media/recipes/a74ccb6b-a3d6-4ed3-8e04-8d02b1d6b423_7.png

Yes, because i already have another program under port 80 on this machine, so to keep it as a local install  I just changed the port, which was fine until I wanted the SSO feature in the beta lol, but i knew beta meant not 100% working.

**Comment by vabene1111** [comment]
Ok so the issue is that DRF outputs the location of the media files automatically trough the rest api which the view uses to display the image.

For some reason, probably due to the nginx setup, it does not recognize that there is a different port running the application.

can you try to solutions presented in this post and see if this fixes your problem ? 

https://stackoverflow.com/a/56254271/6478110

**Comment by tdvantine** [comment]
Alright so I opted for solution 2 since it dynamically handles the port and would make more sense to use in a final release. 
That has indeed solved the issue! Took me a moment to figure out how to change that, but wasn't hard at all. 
![Screenshot_20210215-100344.png](https://user-images.githubusercontent.com/56764154/107975425-52722080-6f75-11eb-9b9e-ae6c86945228.png)

**Comment by tdvantine** [comment]
Forked, and pulled with the updated line.

**Comment by vabene1111** [comment]
perfect, thank you
