### ISSUE TITLE
sync with remote: success message, but no files in dropbox

### ISSUE THREAD

**Issue by mhoellmann** [vabene1111/recipes#40]
I added my Dropbox as remote. When I trigger the sync on the "configure sync" page a success message pops up but the folder in my Dropbox is still empty.

When the sync works correctly something should appear in my Dropbox, shouldn't it?

**Comment by vabene1111** [comment]
The whole sync thingy is a little unintuitive i fear .. sync is meant to include recipes that you have laying around as PDF files from a remote storage location into the recipe page, not to export stuff. 

So if you put some PDF files into the dropbox folder it should find them and then be able to display them on the page.

The reason this feature exists is that this application was originally build to make my recipe collection (a few hundred PDF's) more searchable and then developed to a complete recipe management thing.

**Comment by mhoellmann** [comment]
Well, that's really not what I expected...

Are there any plans on having a real dropbox multi-instance sync? So that e.g. an instance could be running at my mothers place and one at my place and when my mother adds an recipe it is synced to my instance?

**Comment by vabene1111** [comment]
hmm you could both configure the same storage location and put PDFs in there which would show up in both instances, but it is not really meant to run in a federated setup. 

I suggest having one installation and seperate users or if that is not possible to setup some kind of database level sync.
