### ISSUE TITLE
Chowdown Import - Not Working

### ISSUE THREAD

**Issue by PureLoneWolf** [vabene1111/recipes#404]
Hi there

I have been trying to import from my Chowdown recipes, but can't seem to get it working on my Unraid installation of Recipes.

It uploads, seems to say it is complete, doesn't provide any errors and adds a keyword for the import including the date and time, but doesn't actually import anything.

I can confirm that the structure is exactly as described in the documentation - Recipes.zip with images and recipes folders.  

I am not sure if this makes any difference, but the images are not named the same as the recipe files (they are referenced correctly within the md file though)

I tried in both Firefox and Chrome just to make sure that it isn't a browser issue.

Also, and unrelated - I tried to delete an ingredient in the backend and it is still displayed under Ingredients - How do I remove ingredients?

Thanks

**Comment by vabene1111** [comment]
Please raise a seperate issue for the ingredients, maybe there is something wrong there and we can better discuss it.

Regarding the import:

You can do the following
1. run  `docker-compose logs -f` to see if any errors occur during import
2. send me a zip file containing some of your recipes that does not work

i dont have a chowdown installation myself so i took the recipes from the website to verify the importing but maybe that does not catch all edge cases so some sample data would be very great.

**Comment by PureLoneWolf** [comment]
Sorry - When I run the docker-compose command in a console window, it says that docker-compose doesn't exist.  I did get something from the Unraid Docker logs which i copied into a text file.

I also deleted everything bar 2 from my Recipes.zip and attached it here.

[recipes-log.txt](https://github.com/vabene1111/recipes/files/5993786/recipes-log.txt)
[Recipes.zip](https://github.com/vabene1111/recipes/files/5993793/Recipes.zip)

**Comment by vabene1111** [comment]
The reason its not working is because you forgot the `_` before the recipes folder.
I do no know why the author of chowdown choose to have an undersocre before some folders but not others but it was this way in the demo.

Is it not this way in your installation or have you just copied the files and not seen the `_` (which is easily missable)

I have added a warning in the docs but if chowon has different folder namings i might add an additional filter to use both folders depending on which one is present

**Comment by vabene1111** [comment]
ok i have updated the next release to support both `recipes` and `_recipes`

**Comment by PureLoneWolf** [comment]
Thanks...I didn't spot that - _recipes is a container location that I replaced in Unraid so that I can store my recipes outside of the Chowdown AppData folder.

I will just update the zip...sorry about that, and thanks :)

**Comment by vabene1111** [comment]
no worries, i am sure other people would have had the same problem, its better this way
