### ISSUE TITLE
Deleted Ingredients still showing

### ISSUE THREAD

**Issue by PureLoneWolf** [vabene1111/recipes#405]
I tried to delete an ingredient in the backend and it is still displayed under Ingredients

Thanks
![admin](https://user-images.githubusercontent.com/5523493/108169781-75c5d880-70f9-11eb-803f-62236559947d.jpg)
![front-end](https://user-images.githubusercontent.com/5523493/108169782-765e6f00-70f9-11eb-9f2a-71f662674be0.jpg)

**Comment by vabene1111** [comment]
ah yea this is a little naming confusion relic left from old times. 

The Ingredients in the admin refers to the combination of amount, food, unit and a note that is child of a step. 

The Frontend shows "Food" as ingredients as that is kind of what everyone calls it (although technically the ingredient as part of a recipe is what described above). 

I guess i will need to get the naming clear but it should work if you delete a food (which you can do from the frontent i think)

**Comment by PureLoneWolf** [comment]
I couldn't see anywhere in the front-end to delete it - But I found the entry under food in the back-end :)

Thanks
