### ISSUE TITLE
Linked/Sub/Component Recipes

### ISSUE THREAD

**Issue by PureLoneWolf** [vabene1111/recipes#406]
This is something from Chowdown that I think would be a great addition here...albeit better implemented hopefully :)  They call them Component Recipes.

I have a number of base recipes that I like to use as part of other recipes.  A good example would be Shortcrust Pastry, of which I have about 7 different variations, depending on mood/need.  So, when I create a Pie recipe...I can tell it to use one (or more) recipes as a component and it displays the component recipes as a component of the displayed recipe.

With the nature of this being database managed, it would mean, potentially, that I could select any recipe to be a component of any other recipe...which would be awesome as the Chowdown implementation means dropping components in their own sub-folder and they are then not displayed as part of the main books.

I have attached a recipe file with the component listed along with a screenshot of how it looks :)

[Sweet - Cherry Bakewell Tart.txt](https://github.com/vabene1111/recipes/files/5994549/Sweet.-.Cherry.Bakewell.Tart.txt)
![chowdown](https://user-images.githubusercontent.com/5523493/108182283-212a5980-7109-11eb-894e-b85368f42366.png)

**Comment by vabene1111** [comment]
if you go into the food list (utilities > food) and select a food you can specifiy a recipe to create said food.

This is not really intutive and a modal of some kind that allow viewing the food and recipe details in the normal recipe view needs to be added at some point but for now this works.

**Comment by PureLoneWolf** [comment]
Hiya - Actually yeah, although some way to view the recipe within the main recipe page would definitely be useful (maybe toggled visibility) - Also, having to explicitly add a food item based on the recipe feels redundant...it feels like it would make more sense to just be able to add a recipe as an ingredient directly.

But at least I know I can do it now :)  Thanks!

**Comment by vabene1111** [comment]
interesting ideas, i will remember this when adding the more in depth recipe ingredient feature
