### ISSUE TITLE
Ingredient Tooltip rendering glitch

### ISSUE THREAD

**Issue by cesarblancg** [vabene1111/recipes#407]
### Version
Version:  Beta ([commit](https://github.com/vabene1111/recipes/commit/103878e1075bd6eeb0b28b06827d59cf9f20cbb5))

### Bug description
The popover with the description appears over the navbar. Changing the z-index to "auto" solved the problem.

https://user-images.githubusercontent.com/29866109/108188442-df50e180-710f-11eb-8124-f47bc1c7ff27.mp4

**Comment by cesarblancg** [comment]
https://getbootstrap.com/docs/4.4/layout/overview/#z-index
The default z-index of the popover is 1060. Changing the z-index of the navbar to 1061 could be a nice workaround.

**Comment by vabene1111** [comment]
o thanks, i kinda pushed this issue before me as i didn't really know how to fix it 😂 will apply that fix with the next update i hope

**Comment by vabene1111** [comment]
fixed (better late than never 😂 )
