### ISSUE TITLE
Set versions to requirements

### ISSUE THREAD

**Issue by h4llow3En** [vabene1111/recipes#41]
There should be versions for the dependencies in the requirements.txt

Also, if I may ask, do you use gunicorn as a development dependency? Otherwise it should be removed from the requirements.txt and manually installed in the Dockerfiles. Because it is (probaby) only used there

**Comment by vabene1111** [comment]
i only use it for deployment, so it is safe to remove if we install it in docker. Versions are probably a good idea, i never had them as i always wanna have the latest but now that other people use them ist probably safer :D
