### ISSUE TITLE
Plantoeat import/export

### ISSUE THREAD

**Issue by benburdick** [vabene1111/recipes#413]
Plantoeat (https://www.plantoeat.com) allows you to export your recipes in both CSV and/or txt format - I have attached a sample of each to hopefully make things easy for you.  I am happy to help you test this if needed as well!  

[plantoeat-export-data.zip](https://github.com/vabene1111/recipes/files/6005834/plantoeat-export-data.zip)

**Comment by vabene1111** [comment]
thank you 👍

**Comment by vabene1111** [comment]
will be included in next update, sorry for taking so long
