### ISSUE TITLE
Unable to save recipies

### ISSUE THREAD

**Issue by recom273** [vabene1111/recipes#415]
Great looking app

1. Cant Save

An error occurred while trying to import this recipe

`An error occurred while trying to import this recipe! <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>`

2. Cant edit imported ingredients.

3. Cant import from the number one google search for most recipes - https://www.allrecipes.com/recipes/377/desserts/cakes/cupcakes/

Using Unraid - followed instructions on wiki

**Comment by vabene1111** [comment]
since these things are working for many people this is probably a setup issue. 
Can you provide the container logs ? i dont know how this is done on unraid but the 500 error should show somewhere in the logs with a stacktrace

**Comment by IxsharpxI** [comment]
Yes i got this same error trying to import a recipe. Im using docker and looking at container logs in portainer. trying to import the following recipe. But get same error. which container log should i check? there isnt a lot of useful information that I see. 

https://www.hellofresh.com/recipes/firecracker-meatballs-5ea70fe14c4efb3fb12140f1

**Comment by vabene1111** [comment]
ah ok this is related to importing. Have you upgraded to the latest version (0.14.3) ? 

There was an issue related to the servings being empty in some cases which was fixed in that release

**Comment by IxsharpxI** [comment]
Yep that solved it for my case!
