### ISSUE TITLE
Optimize Recipe List Layout for wide screens

### ISSUE THREAD

**Issue by ministryofsillywalks** [vabene1111/recipes#418]
**Is your feature request related to a problem? Please describe.**
Currently the recipe list layout on wide screens (PCs and Tablets in Landscape) has a lot of dead space.
I know there is a list view but this currently doesn't even show images.

**Describe the solution you'd like**
Offer different view types (colums & cards) see mockups below

**Describe alternatives you've considered**
Mealie (though lacking in other features) has a very nice looking card layout based on material design which uses the screen real estate a lot more efficiently.
See here: https://user-images.githubusercontent.com/10544895/108477408-75614500-7293-11eb-950f-8541ac6eb6fd.png

**Additional context**
These are just some quick mockups to better visualize what I'm talking about.

The standard layout on a wide screen has a lot of dead space:
![standard](https://user-images.githubusercontent.com/10544895/108476950-e9e7b400-7292-11eb-8fb2-af25fcff0d92.png)
If columns were available this would already double the number of recipes you can see at the same time:
![columns](https://user-images.githubusercontent.com/10544895/108477048-0683ec00-7293-11eb-85a7-22e4bcf01495.png)
A card view type could triple the amount of recipes:
![Cards](https://user-images.githubusercontent.com/10544895/108477101-17346200-7293-11eb-8170-d83d3964d65b.png)

Not sure if this is easily implemented but it would make browsing a large recipe catalog on a landscape screen a lot more efficient.
Thanks for this awesome software!

**Comment by vabene1111** [comment]
thanks for the feedback, the search page is definitly due for a rework and one of the next things on my todo list

**Comment by vabene1111** [comment]
closed and linked in search rewrite issue
