### ISSUE TITLE
Optimise Serving Count to Shopping List

### ISSUE THREAD

**Issue by B1ue-W01f** [vabene1111/recipes#419]
Currently, the process of capturing servings is a little inefficient for a number of reasons:

1) Serving Count on the Meal Plan is reset every time you place a meal. Its safe to assume for most meals the number of servings will remain consistent i.e. 2 people every day = 2 servings for every meal
2) Serving Count doesn't appear to affect the shopping list quantities, a 10 serving count meal added to the Meal Plan adds the exact same number of ingredients to the Shopping List as a 1 serving count meal.

I'd suggest Serving Count remembers the previous entry (at least within session) and the serving count stored in meal plan is captured when adding the day to the shopping list.

**Comment by vabene1111** [comment]
The serving count given in the recipe is the base amount the recipe ingredients are good for. 

e.g. A meal with the basic configuration is 4 servings. Now if you want to cook double that you will need to put 8 servings in, no matter if you are on the plan, the shopping list or the recipe view. 

If you dont feel like working with servings you can just leave them at 1 even for a 4 person meal and if you want to double that you enter 2. 

Last time i tested everything worked like this

**Comment by B1ue-W01f** [comment]
@vabene1111 Thats not what I was referring to:

> Serving Count ***on the Meal Plan***

The logic should be the recipe has a set number of servings sure, but the Serving Count on the ***Meal Plan*** doesn't appear to actually do anything currently, other than arbitrarily set the serving in the meal plan - and certainly doesn't effect the shopping list. Furthermore, the setting is reset after adding an entry.

**Comment by vabene1111** [comment]
Ok i will need to test this. The meal plan should store the desired servings for when you create a shopping list from it so that the shopping list is already scaled up.

**Comment by B1ue-W01f** [comment]
Checked the demo website and don't believe it's happening on there.

**Comment by vabene1111** [comment]
ok so i have set one of my recipes to be 4 servings. I have then added it to the meal plan which preserved the servings correctly. I have then edited the servings to be 8 instead of 4 which was saved correctly and also passed correctly in the url parameter to the shopping list view. 

here the parameter gets ignored which needs to be fixed.

**Comment by vabene1111** [comment]
Ok fixing this issue has lead me to the discovery of a much more serious issue on the shopping list. 

I have detailed the issue here #453 

i have also discoverd that creating plans from the recipe context menu is broken #454
