### ISSUE TITLE
Image import failing

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#420]
the reason the image loading fails sometimes might be the user agent

#208

https://github.com/vabene1111/recipes/issues/208#issuecomment-781661811

**Comment by tohn** [comment]
I also had this error just now:

```
There was an error updating the recipe!{"image":["Upload a valid image. The file you uploaded was either not an image or a corrupted image."]}
```

What's interesting with this: the image showed correctly during import and when I select an image later in the edit mode:

<img width="718" alt="Screenshot 2021-08-30 at 02 00 12" src="https://user-images.githubusercontent.com/427159/131262429-f257b886-81c7-4823-93db-613fdc69f26c.png">

**Comment by vabene1111** [comment]
i think the problem you are having might be unrelated to this issue as webp images might not be supported, i have honestly never tested that. Could you open another issue, link to this one and post the original URL where you tried to import from

**Comment by tohn** [comment]
> i think the problem you are having might be unrelated to this issue as webp images might not be supported, i have honestly never tested that. Could you open another issue, link to this one and post the original URL where you tried to import from

Nevermind, I just solved my issue 🤦 (I was using a password protected site and the referenced image was apparently not downloaded with the proper authentication). Thanks tough, webp works fine if the website is not protected.

**Comment by vabene1111** [comment]
ok awesome, password protected pages do pose a problem as the website is loaded from the server and thus authentication is not shared. This will likely change in the future and you can also use the bookmarklet to import any page that cannot be imported by the server due to possible IP or user agent checking
