### ISSUE TITLE
403 CSRF Error

### ISSUE THREAD

**Issue by kushfest** [vabene1111/recipes#429]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.14.2

### Issue
I use a SWAG container to handle reverse proxying services with subdomains, using authelia for authentication. I followed the directions in #391 to setup my Recipes.conf to forward the auth headers, so that nginx in my SWAG container can handle reverse authentication with authelia. I've got it up and running and I thought it was all good until I tried updating my settings. 

When I click any of the save buttons I am met with a 403 error that says "CSRF verification failed. Request aborted." I also found this happens when I try to add a storage backend, import a  recipe, or really do anything significant in the app. Any ideas?

Edit: I just disabled authelia from my setup for tandoor and i'm getting the same CSRF errors. I can't even login now, I'm just immediately met with the CSRF error.

### nginx-recipes container: /conf.d/Recipes.conf
```
server {
  listen 80;
  server_name localhost;

  client_max_body_size 256M;

  # serve media files
  location /media/ {
    alias /media/;
  }

  # serve static files
  location /static/ {
    alias /static/;
  }

  # pass requests for dynamic content to gunicorn
  location / {
    proxy_set_header Host $http_host;
    proxy_set_header REMOTE-USER $http_remote_user;
    proxy_pass http://web_recipes:8080;
  }
}
```

### SWAG container: /proxy-confs/tandoor.subdomain.conf
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name cookbook.domain.com;

    include /config/nginx/ssl.conf;

    client_max_body_size 256M;

    # enable for Authelia
    include /config/nginx/authelia-server.conf;

    location / {
        # enable for Authelia
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;

	proxy_set_header REMOTE-USER $user;
	proxy_pass http://xxx.xxx.xxx.xxx:4444;
    }

    location /accounts/logout/ {
	return 301 https://cookbook.domain.com/authelia/logout?rd=https%3A%2F%cookbook.domain.com;
    }
}
```

**Comment by vabene1111** [comment]
hmm this is very interesting .. i have absolutely zero idea on how SWAG container and authelia work. The CSRF token is passed to the client both as a cookie and in normal forms as an invisible form field, both things are handled automatically by django.

I recently had an issue with another application where the scope of the cookie was the problem when i had the reverse proxy configured wrongly but i honestly have no clue what could be wrong with your setup because from what you show it all looks fine

**Comment by kushfest** [comment]
Totally fair, given reverse proxy + authelia are definitely not a main focus of your app. I will re-install a fresh copy of tandoor to try to get my proxy working again with CSRF and then will keep tinkering to see if I can get the setup working. If so, hopefully other users can benefit from whatever the solution is, if I can figure it out haha. If anything, maybe this will help me learn more about django!

**Comment by vabene1111** [comment]
perfect, thank you very much. I will be happy to update the docs with your experience once you are done so let me know if i can improve somthing or just add it yourself with a PR, whatever you like best.

**Comment by vabene1111** [comment]
i will leave this issue open for now so i remember checking back on it and other people find it better

**Comment by kushfest** [comment]
I did a fresh install and then went through my tandoor.subdomain.conf file for SWAG in detail and discovered that the setting causing the CSRF issue is:
```
proxy_set_header X-Forwarded-Proto https;
```
I was able to get rid of the CSRF error by changing it to:
```
proxy_set_header X-Forwarded-Proto http;
```

So that got my subdomain functioning again through my SWAG reverse proxy. I then tried turning authelia on again for this subdomain and ran into a new issue. The user created by tandoor when i first login with authelia is not right. If my user name was user it would be creating it is as user,user. 

I tried first with an existing superuser with the same username as my authelia login, in the hopes that would allow me not to have two different accounts. I then tried again with different user names and i'm still getting the same error.

Any ideas?

**Comment by vabene1111** [comment]
Hmm interesting problem. I have never really understood how the remote auth system of django works. There was a user who requested to add a setting to enable the setting.

Maybe this helps to understand the issue https://docs.djangoproject.com/en/3.1/howto/auth-remote-user/

I am not sure if something basic is broken in my settings/systems or if you need to configure this on your end.

**Comment by nishantbb** [comment]
@kushfest 

I'm planning to install soon and use SWAG as my reverse proxy. Did you include the NGINX container in your installation of Tandoor? I'm confused as to whether I should include that or not, and if I should, where to point SWAG to. Thanks for any help.

**Comment by vabene1111** [comment]
If anyone of you would like to contribute a new doc site on how to use Tandoor with swag that would be really cool! Could also be just a reply to this post and i can put it into the docs

**Comment by nishantbb** [comment]
> If anyone of you would like to contribute a new doc site on how to use Tandoor with swag that would be really cool! Could also be just a reply to this post and i can put it into the docs

Will reply back with anything noteworthy at some point this week. Thanks

**Comment by kushfest** [comment]
> edit: took a few seconds to look through SWAG and found that they already have a pre-configured conf for Recipes / Tandoor. pretty cool. Sorry for bugging you guys.
> 
> I'm planning to install soon and use SWAG as my reverse proxy. Did you include the NGINX container in your installation of Tandoor? I'm confused as to whether I should include that or not, and if I should, where to point SWAG to. Thanks for any help.

Oh great! I saw that someone had submitted it for swag, but they got that added quick! I'm still working through the authelia side of things, but as far as just the reverse proxy, it's working great now!

> If anyone of you would like to contribute a new doc site on how to use Tandoor with swag that would be really cool! Could also be just a reply to this post and i can put it into the docs

happy to help as well!

**Comment by nishantbb** [comment]
> > If anyone of you would like to contribute a new doc site on how to use Tandoor with swag that would be really cool! Could also be just a reply to this post and i can put it into the docs
> 
> Will reply back with anything noteworthy at some point this week. Thanks

Got it set up using SWAG. It's about as standard as any other LSIO image with SWAG. If you want to add a note onto the docs, you could simply add a step after container setup. Just mentioning the file in step 1 should be enough for most people.

Steps 1-3 are not special to Tandoor/Recipes. Step 4 is mentioned in the pre-configured SWAG file.

If using SWAG for your reverse proxy and are hosting Tandoor as a subdomain:
 1) find the pre-configured proxy conf file for recipes (swag/nginx/proxy-confs/recipes.subdomain.conf.sample)
 2) follow instructions on file, updating server_name to your domain
 3) if you used a different name than nginx_recipes, specify in $upstream_app (or use IP address)
 4) confirm Recipes.conf file is set up in the correct folder.
 5) save file, removing ".sample"

For whatever reason, Recipes.conf never populated my nginx_config folder. Likely an issue with how my portainer stack was set up. But I just downloaded and placed it in manually. I think I'll have issues when trying to update.

**Comment by vabene1111** [comment]
Thanks for providing these steps.

Before i put it into the docs, is there a place i can link to the swag config file for Tandoor ?

**Comment by nishantbb** [comment]
> Thanks for providing these steps.
> 
> Before i put it into the docs, is there a place i can link to the swag config file for Tandoor ?

Here is the specific file (still called "recipes"):
https://github.com/linuxserver/reverse-proxy-confs/blob/master/recipes.subdomain.conf.sample

All of the site proxy conf sample files come with an instance of SWAG. So it'd just be a manner of editing the server_name to the allowed_hosts specified in the environment.

You could drop a link to this when mentioning swag, as well. https://docs.linuxserver.io/general/swag

**Comment by auanasgheps** [comment]
You can also solve the CSRF error by adding
`proxy_set_header X-Forwarded-Proto $scheme;`
#409
