### ISSUE TITLE
iOS WebClip support

### ISSUE THREAD

**Issue by Tuetenk0pp** [vabene1111/recipes#432]
**Is your feature request related to a problem? Please describe.**
There is a way to add a 'WebClip' in iOS that opens any website as if it was a native iOS app. Users just have to 'pin' the website to their Homescreen when inside safari. It already works for Tandoor, but it could be better: it is missing a proper icon. You can also specify wether it should be opened fullscreen, with/without safari UI and more.

**Additional context**
I found some apple documentation on this, along with other website explaining how to add this functionallity.

Apple Documentaion:
* https://developer.apple.com/documentation/devicemanagement/webclip
* https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Tutorials:
* https://webdesign.tutsplus.com/articles/quick-tip-give-your-website-an-ios-home-screen-icon--webdesign-10067
* https://www.create.net/support/adding-an-ios-home-screen-icon-for-your-website

**Comment by vabene1111** [comment]
i hate apple for doing everything in other ways than everybody else (or maybe i am stupid and this is actually ok)

This feature for windows, androdi, linux and god know what other platform is called a progressive web app and support was added with the last update.

would you mind testing if installing tandoor as a PWA works if you use chrome on an IOS device ?

**Comment by Tuetenk0pp** [comment]
> i hate apple for doing everything in other ways than everybody else (or maybe i am stupid and this is actually ok)

I quite understand that :P 

Using another browser instead doesn't solve the problem, unfortunately (I have tried chrome and firefox, both don't support it at all). Every browser available for iOS has to base on WebKit (deep in the OS), which just doesn't fully support PWAs.

Just to be clear: it already works quite well and the only obvious problem is the app-icon (I'm sure there's more that one could optimize). Here's some pictues:
![PWA setup](https://user-images.githubusercontent.com/55783419/108601823-eb9e9e00-739e-11eb-82a0-ec8c8cdb86a4.jpg)
![PWA icon](https://user-images.githubusercontent.com/55783419/108601821-eb060780-739e-11eb-97b9-3f5eeb8d3d9b.jpg)
![PWA example](https://user-images.githubusercontent.com/55783419/108601825-eb9e9e00-739e-11eb-9fa9-c0b131f807ad.jpg)

> support was added with the last update.

I read the note in the changelog a few days ago, which is why I tried it (again). The experience on iOS is **already** better than before!

You can solve the app-icon problem by adding a link in the website header I think but that is described in some of the recourses I posted earlier.

**Comment by Tuetenk0pp** [comment]
Here is a detailed documentation on this topic: https://firt.dev/ios-14/

**Comment by vabene1111** [comment]
ah ok, i tought i fixed the apple app icon thingy. But this explains a lot, thank you very much. When i get around to it i will add the required features, i will tag you then as i dont own any apple devices to test on

**Comment by tdvantine** [comment]
I have some apple stuff I could test one as well. I haven't looked at the links but if it isn't too complicated I can give it a shot.

**Comment by vabene1111** [comment]
most times its just a manifest or header entry somewhere so if you want to give it a try feel free, if not dont worry, i will get around to support those special webkit browsers as well :) but might be a bit as there are some things that are kind of priority right now
