### ISSUE TITLE
Sum up the same ingredients in the main list

### ISSUE THREAD

**Issue by DaFlowah** [vabene1111/recipes#435]
**Is your feature request related to a problem? Please describe.**
In the main ingredient list, I'd like to see the sum of the same ingredient I put in the different steps.

**Describe the solution you'd like**
Put the same ingredients together in the main ingredient list if these ingredients are showing multiple times in different steps.

**Describe alternatives you've considered**
N/A

**Additional context**
I guess this might become complicated for (sub)multiples, for example if I have _300 g of flour_ in Step 1 and _1 kg of flour_ in Step 2.

![immagine](https://user-images.githubusercontent.com/33235583/108602988-2b648600-739d-11eb-9ecf-56682bfd1e6b.png)

**Comment by tdvantine** [comment]
This has already been requested 😉 make sure to search.
https://github.com/vabene1111/recipes/issues/196

**Comment by DaFlowah** [comment]
Crap baskets!
Sorry mate D:
I'll close this one.
