### ISSUE TITLE
Import from reishunger.de imcomplete

### ISSUE THREAD

**Issue by frudolph77** [vabene1111/recipes#438]
**Is your feature request related to a problem? Please describe.**
I tried to import a recipe from [reishunger.de](https://www.reishunger.de/rezepte/rezept) the ingredients where imported, but prep. time, wait time, servings and instructions where empty.
Saving the recipe failed with HTTP 500, because of an empty value in servings, after adding a number saving worked.

**Describe the solution you'd like**
Fully imported recipe :-)

**Describe alternatives you've considered**
Import ingredients, edit recipe and add missing stuff by hand.

**Comment by vabene1111** [comment]
can you verify if the 500 error still occurs after updating to 0.14.3 ?

Other than that i will take a look at the micordata/json on the page and verify if its a problem on my or their side

**Comment by frudolph77** [comment]
> can you verify if the 500 error still occurs after updating to 0.14.3 ?

Just update my k3s cluster from 0.14.2 to 0.14.3

With 0.14.3 the servings are initialized with 1 so saving worked fine.  But for the recipe the services was more than 1.

**Comment by vabene1111** [comment]
ok this is another issue. Depending on how a page formats its data it is sometimes not possibel to retrive the servings. Or at least i need to add different switchtes in the importer to support any of the 10000 stupid ways to format the field as some pages just put the number and some include text as well

**Comment by frudolph77** [comment]
I've check a recipe from their page see [here](https://search.google.com/test/rich-results?id=2vncMNL6pFCdkXUXkgxfag) 
The recipeInstructions is missing in the  ld+json data, but at least the recipeYield is present.

Nevertheless, thanks for your great work.

**Comment by vabene1111** [comment]
thanks for checking, i usually collect some issues and every few weeks go trough them and update the website parser. I will take a look at this one next time i do so and see if the importer can be improved

**Comment by smilerz** [comment]
@frudolph77  #475 will fix the serving size part of the import - but the major problem is that they store their ingredients in a dict which won't get fixed with that pull.

I suggest going over to [recipe-scrapers](https://github.com/hhursev/recipe-scrapers) and request having the site added to their list of custom scrapers.  Once 475 gets merged it will then fully work in recipes as well.

**Comment by frudolph77** [comment]
I've opened an issue at [recipe-scrapers](https://github.com/hhursev/recipe-scrapers/issues/352)

**Comment by smilerz** [comment]
@frudolph77 is this working now?  I think the update in recipe_scrapers was merged

**Comment by frudolph77** [comment]
Sorry, for the late feedback. Due to several issue, among broken hardware, I have not able to verify if it is working now. 
Will take a while, sorry again.

**Comment by vabene1111** [comment]
closing for now, if issues arise just report
