### ISSUE TITLE
Question: Insidee the recipe what do the check boxes do? 

### ISSUE THREAD

**Issue by faspina** [vabene1111/recipes#440]
### Version
Latest Docker on Unraid 

### Issue
What do the check boxes do beside each ingredient when you drill into a recipe. I checked a few items I had, uncheck items i needed and clicked add to list but all items from the recipe were put on the list. 

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
env content
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
docker-compose.yml content
```

**Comment by vabene1111** [comment]
they are just visual markers for when you are cooking and want to check the ingredients you already put in.

Avoids forgetting something if you have a large number of ingredients
