### ISSUE TITLE
Fix and complete German translation

### ISSUE THREAD

**Issue by MaxJa4** [vabene1111/recipes#442]
### Version
Version: 0.14.3

### Bug description
There are some translated strings to German which aren't completely right or have little errors (nothing major though).
Also, there is still ~12% untranslated (according to transifex) which is visible at times.

I registered at transifex to help translate German <-> English - so this bug ticket is just for documentation or in case I don't get accepted to contribute to the translation myself.

**Comment by vabene1111** [comment]
thanks for opening the issue. i have accepted you to transifex and i am looking forward to your translations

**Comment by MaxJa4** [comment]
Looks like @l0c4lh057 already did quite some work since the last pull of the translations. I fixed some very minor stuff and added the last few dozen of untranslated strings. Looking forward to see them in action soon :)

**Comment by vabene1111** [comment]
thank you very much :+1: translations will be included in the next update which hopefully is not to far away

**Comment by cyberius0** [comment]
Hi,
I guess the german translation fixes were not integrated yet? As I have a mixture of German and English. Also often the Translation switches to "English" even if I explicitly set German in settings. Can it be that my browser settings (default language=English) overwrites the setting in recipes?

![Example](https://i.ibb.co/2KhWHMM/transl.png)

**Comment by vabene1111** [comment]
the recipe UI has been moved to a new javascript frontend where translations are still a little buggy. This will be fixed in one of the upcoming releases.
