### ISSUE TITLE
Sub-Path not included in JavaScript files

### ISSUE THREAD

**Issue by albcp** [vabene1111/recipes#443]
### Version
Version: 0.14.3

### Bug description
The URLs from *reverse.js* do not contains the Sub-Path. Because of this, when JavaScript sends a request or include a URL into a template, the endpoint does not contains the Sub-Path.

This can be tested on the *recipe_view* page of any recipe. This page does not include the Sub-Path in the hrefs from the 3 dot menu and sends two requests to *api/*.

**Comment by vabene1111** [comment]
hmm interesting. do you mean sub domain by sub path ? e.g. subdomain.mydomain.com ?

**Comment by albcp** [comment]
No, I mean after the domain, e.g. mydomain.com/recipes/

As you can see in the screenshot, api requests are sent to mydomain.com/api/ instead of mydomain.com/recipes/api/.
![2021-02-22_18-16](https://user-images.githubusercontent.com/3170731/108744971-dbbbc100-753a-11eb-81a7-62fc0070e5be.png)

It was working in version 13.0 with the environment variables STATIC_URL, MEDIA_URL and SCRIPT_NAME.

**Comment by vabene1111** [comment]
ah ok .. i was using a different system then to get the urls on the client. 

I dont really know how the url generation system works when the system is run under a subpath. I will see if and how i can fix this.
