### ISSUE TITLE
Redundant spacing and no image with recipes on mobile

### ISSUE THREAD

**Issue by MaxJa4** [vabene1111/recipes#449]
### Version
Version: 0.14.3

### Bug description
When viewing a single recipe on mobile, there is lots of redundant spacing between multiple sections at the top. Additionally, the image doesn't show.
This happens on Safari and Google Chrome (iPhone 12 Pro iOS 14.4).

[Image #1](https://user-images.githubusercontent.com/74194322/108737597-0dc92500-7533-11eb-957c-b328e3241d83.PNG)
[Image #2](https://user-images.githubusercontent.com/74194322/108737592-0d308e80-7533-11eb-8c26-626202656245.PNG)
[Image #3](https://user-images.githubusercontent.com/74194322/108737589-0c97f800-7533-11eb-8fd2-e1f6de868292.PNG)

**Comment by vabene1111** [comment]
Interesting. On you desktop everything works ? 

Since mobile viewing is working perfectly for me i suspect that this might be related to iOS but since i know some other users are using IOS and have not reported issues could this be related to some kind of content filtering you have enabled ?

**Comment by IxsharpxI** [comment]
yes i can say mine looks like this as well on iphone 12 and ipad mini

**Comment by MaxJa4** [comment]
I don't have any filtering enabled, also no VPN or anything like that. On my desktop, everything is fine.

So looks like I'm not the only one, good and bad in a way.

**Comment by vabene1111** [comment]
hmm that is obviously i a problem. I have no idea on how to best test this without an apple device. Is it possibel to open a debug console on your mobile browser to show some logs or are there any warning visible somewhere ?

@Tuetenk0pp are you having these problems as well, i remember you were using iOS correct ?

**Comment by Tuetenk0pp** [comment]
> @Tuetenk0pp are you having these problems as well, i remember you were using iOS correct ?

Yes I can confirm that. Lot's of white spaces.
[recipes.pdf](https://github.com/vabene1111/recipes/files/6031529/recipes.pdf)
I also noticed that there is no author showing anymore.

**Comment by MaxJa4** [comment]
I just barely managed to get the HTML source out of my iPhone... "just use Safari on your Mac to debug sites" ok please give me one free Apple.

Looks like the style-attribute (in-line, not in a css-file apparently) "height: 100%" in the div class="row d-flex" is causing this. Would be the HTML source helpful? It's completely messed up because it lacks some references and I had to copy it via Word which messed up linebreaks... but opening it with Chrome and using the inspector is much better.

**Comment by MaxJa4** [comment]
Here is the src (just removed the link to my homepage for the recipe picture).
Just download, rename to *.html and open it with your browser of choice, you know the drill :)

[src.txt](https://github.com/vabene1111/recipes/files/6031593/src.txt)

**Comment by vabene1111** [comment]
The source code looks perfectly fine but that is also due to the fact that most of the code on the recipe view page is generated trough javascritp and not shown in the source code (but thank you very much for going trough all the trouble to get me the code).

Do i understand it correctly that the issue does not occor on desktop apple devices (which as far as i know also use webkit right ?).

Just from guessing this seems to be an issue where webkit renders the same thing differently than all the browsers i can test on. 

Is the recipe image the only thing that is no longer showing or looking broken ? the screenshot looks like the browser know the image should be there (and also the image dimensions) but does not render it and shows the alt text instead.

@Tuetenk0pp the author not showing is because i have not implemented that yet into the new view.

**Comment by MaxJa4** [comment]
I don't have any kind of Mac currently, so I can't say. I heard Chrome on iOS is using Webkit too in it's core.

Couldn't find any other occurrence of that issue. Even the recipe editing page looks correct.

**Comment by MaxJa4** [comment]
https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent

Yes it seems to be a Webkit issue. It needs a display: flex instead of height: 100%... hard to verify though due to the lack of a Mac (damn Apple knows how to sell those lol).

**Comment by IxsharpxI** [comment]
It appears fine on my mac using chrome. seems to be limited to mobile devices for me

**Comment by vabene1111** [comment]
Ok so just a note for myself: the image not displaying seems to be another issue (probably related to one of the many currently active discussions for different deployment options). 

Regarding the issue itself: I am terrible at front end design, it took me quite a while to get the top bar working correctly but i used some flex elements there that could probably cause this issue. 

The corresponding source can be found here https://github.com/vabene1111/recipes/blob/develop/vue/src/apps/RecipeView/RecipeView.vue#L25-L99

i will see how this can be fixed (there is most likely a better way to do the whole ui)

**Comment by Tuetenk0pp** [comment]
> https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent
> 
> Yes it seems to be a Webkit issue. It needs a display: flex instead of height: 100%... hard to verify though due to the lack of a Mac (damn Apple knows how to sell those lol).

I've got a semi-broken macbook that I could use to investigate stuff. Any need for that?? There's also a way to simulate iOS devices using Xcode I think

**Comment by MaxJa4** [comment]
@Tuetenk0pp Yes you can simulate iOS devices in XCode

@vabene1111 Glad that I reverse engineered to the same file haha. I'm no front end expert too, my main tactic is basics + google + chrome inspector. I changed that file inside the docker container. But it didn't apply the change apparently, is there caching happening or do I need to restart the container? I'm completely new to docker unfortunately.

**Comment by vabene1111** [comment]
There is a really nice person who messaged me on reddit the other day (dont now the github nick), he said he could reproduce the issue and would take a look. 

If he cant solve the issue i will let you know here so we can work together to fix it :)

**Comment by ProfessorSalty** [comment]
> There is a really nice person who messaged me on reddit the other day (dont now the github nick), he said he could reproduce the issue and would take a look.
> 
> If he cant solve the issue i will let you know here so we can work together to fix it :)

That's me. I'm on it :)
