### ISSUE TITLE
Add support for swedish food magazine Alltommat

### ISSUE THREAD

**Issue by roflcoopter** [vabene1111/recipes#465]
**Is your feature request related to a problem? Please describe.**
In Sweden there is a popular food magazine called Alltommat (AllAboutFood) where they publish lots of recipes.

**Describe the solution you'd like**
It would be great if the importer could support the format of these recipes.
An example would be this recipe:
https://alltommat.se/recept/stekt-rodbetsgnocchi-med-brynt-valnotssmor/

Looking at the HTML it does seem to have a good structure to grab the data from.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vabene1111** [comment]
the source does contain ld+json so it should be parsable. I will need to verify if requests are blocked or any information is stored in a non standard way but this should be possible

**Comment by roflcoopter** [comment]
Thanks for looking into it! Let me know if i can do anything to help

**Comment by smilerz** [comment]
@roflcoopter  The pull above will mostly fix the import - but that site does not include the units/measures in their ingredient list.

You can add a feature request at [recipe-scrapers](https://github.com/hhursev/recipe-scrapers) to have a custom scraper for that site added and when it gets merged there hopefully the new URL import will be merged here.

**Comment by roflcoopter** [comment]
Great! Yeah the units are embedded in the amounts... not ideal.
Any way i can test this out for you or should i just wait for the PR to get merged?

**Comment by smilerz** [comment]
If you know how to merge branches you can merge url_import_recipes branch (from [here](https://github.com/smilerz/recipes/tree/url_import_recipes)).  That won't make any database changes so should be safe.
