### ISSUE TITLE
New Translation Setup

### ISSUE THREAD

**Issue by auanasgheps** [vabene1111/recipes#466]
## Transifex related

Hi 
I've noticed that Transifex is not creating pull requests after I update a translation. It was only created when I completed the translation for the first time.
How is supposed to work? I've done many corrections but haven't been sent to Github.

**Comment by vabene1111** [comment]
yea i can manually trigger a PR but it does not do them automatically. to be honest i am not very happy with transifex and i am considering to move to another plattform. For now just let me know if i should update a certain language or just complete its translations if that is an otpion

**Comment by auanasgheps** [comment]
All right, yes please update the Italian translation, I've made a lot of changes since the last push.

You could consider Crowdin, I use it for other projects.

**Comment by vabene1111** [comment]
yes i have also heard good things about it. I will take a look :)

**Comment by comradekingu** [comment]
@vabene1111 @auanasgheps Have a look at Weblate too. In my view Crowdin is only better in a few areas, and _terribad_ where it matters. It is also closed source as-a-service only, with plenty of spying scripts.
I second the notion of getting away from Transifex. Will contribute if it gets put on any of the libre software platforms.

**Comment by vabene1111** [comment]
Nice, thanks for the feedback.

Maybe there is even something selhosted 🤔

**Comment by comradekingu** [comment]
@vabene1111 
https://github.com/WeblateOrg/weblate :)

**Comment by auanasgheps** [comment]
So I guess we found the platform 😆

**Comment by vabene1111** [comment]
this looks very cool. I will see that i get it setup on the demo server and migrate all the translation workflows over to it (maybe test it out a bit first 😂 )

will let you people know when its done, will probably take some time as i have some other important stuff to do right now

**Comment by vabene1111** [comment]
Ok so a new translation system is up and running. I will need to really figure out how it works but it appears to be really nice 

You can already check it out here https://translate.tandoor.dev/ some documentation will follow soon.

**Comment by auanasgheps** [comment]
Just translated and adjusted some stuff. I am already using Weblate for another project and I really like it!

**Comment by vabene1111** [comment]
glad you like it, there are still some things i need to figure out (for example if the pending changes are commited automatically and when) but overall it has been much less pain than transifex so far.
