### ISSUE TITLE
On first launch, does not default to /setup/ page, but to the login screen, with no way to create a user.

### ISSUE THREAD

**Issue by invisible-walrus** [vabene1111/recipes#467]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.14.5

### Bug description

after following docker-compose instructions, i'm greeted with a successfully set up server, but when i log into 192.168.x.x/setup, theres a bar that shows "The setup page can only be used to create the first user! If you have forgotten your superuser credentials please consult the django documentation on how to reset passwords."

I never created a superuser, or a first user. Django docs say to use a manage.py file, but i cant find it anywhere in any of the folders or volumes.

**Comment by vabene1111** [comment]
are you using reverse proxy authentication or an external authentication provider which might have created a user for you autmatically ?

**Comment by vabene1111** [comment]
ok so i have slightly improved the automatic redirects with the next update and added some documentation. Still not perfect but should be ok for now
