### ISSUE TITLE
Paprika Import Fails

### ISSUE THREAD

**Issue by marcusisinger** [vabene1111/recipes#479]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.14.5

### Bug description
Not sure if its a bug or something strange with my setup, I just recently got it up. The only thing out of the ordinary is I'm using my normal nginx server to forward proxy to the nginx docker container, but this should not be related to that it seems.

Exported my recipe library from Paprika (700+ recipes). Zipped folder. Imports fails with:

web_recipes_1    | testing Recipes/
web_recipes_1    | testing Recipes/Preserved Lemons.html
web_recipes_1    | Internal Server Error: /import/
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_recipes_1    |     response = get_response(request)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_recipes_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
web_recipes_1    |     return view_func(request, *args, **kwargs)
web_recipes_1    |   File "/opt/recipes/cookbook/views/import_export.py", line 40, in import_recipe
web_recipes_1    |     return integration.do_import(request.FILES.getlist('files'))
web_recipes_1    |   File "/opt/recipes/cookbook/integration/integration.py", line 90, in do_import
web_recipes_1    |     recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
web_recipes_1    |   File "/opt/recipes/cookbook/integration/paprika.py", line 30, in get_recipe_from_file
web_recipes_1    |     recipe_json = find_recipe_json(md_json['properties'], '')
web_recipes_1    |   File "/opt/recipes/cookbook/helper/recipe_url_import.py", line 214, in find_recipe_json
web_recipes_1    |     parse_duration(
web_recipes_1    | AttributeError: 'NoneType' object has no attribute 'seconds'

**Comment by vabene1111** [comment]
interesting. You are using the paprika HTML export and the file structure is according to the documentation ?

If you want (and if it does not contain any private information) you could share the recipes or some of them with me and i can see why the import fails

**Comment by marcusisinger** [comment]
Yep, I followed the docs. Before this I got a 500 error from the server, but I uncommented /media/ and /static/ in the .env and enabled debugging, then this happened. 

I can share a small subset of the recipes that replicate the behavior!

**Comment by marcusisinger** [comment]
Some of the recipes are in swedish if that would matter. I tested the example Paprika.Export.zip I found on here and that worked after I restructured the folders inside according to the docs.

**Comment by vabene1111** [comment]
yes, the structure is important. 

Does your import work now that the structure is correct ?

**Comment by marcusisinger** [comment]
I used the correct structure on my own paprika recipes. I tried a small set of them, and it works somewhat.. Out of 5 it imports 2.. How can that be? The recipes seems to be the same structurally. 

Would the large import fail only because it's too large?

**Comment by vabene1111** [comment]
there are problems with large imports which i need to address. The problem with paprika is that i currently use their not very well formatted html files. I recently learned that the file i thought to be a proprietary binary is just a compressed json (if i remember correctly) so i can probably switch to that for the next version. 

Sadly i have a lot of things to do currently and dont know when i will get to improving the importer.

**Comment by marcusisinger** [comment]
I managed to make it work with some batch editing of the html files in python (removing some tags that seemed to create errors and adding image placeholders to recipes missing images). If anyone is interested I can share the script. Now my problem is it times out, but that is another issue which should be fixable. 

However, during all this, it seems there is a need to be able to batch edit recipes (and batch delete). I haven't found a good way to delete recipes? Now when it timed out halfway through, and it parses the recipes in an apparent random order (?), I can't just continue where it failed.. So I need to delete all recipes and start over. Do I need to do that in the database directly? Thanks for your time and effort by the way, it's a great project with a bright future I think!

**Comment by vabene1111** [comment]
i guess you best bet would be the admin page ..

also sry that this is still broken, i currently am very short on time and havn't gotten around to fixing the timeouts. I want to re-write the system to basically run as a background job but that needs some serious refactoring sadly 

i will also re-work the paprika importer to use the json so there is no need to fix the current importer

**Comment by vabene1111** [comment]
From the next update on the importer will use the paprikarecipes file and should work much more reliable
