### ISSUE TITLE
Error when uploading pictures (PNG, JPG, ...)

### ISSUE THREAD

**Issue by Squadeur** [vabene1111/recipes#483]
Hello everybody,

I had an issue when I want to upload any picture (PNG, JPG, ...).
see below the message error :

There was an error updating the recipe!<!DOCTYPE html> <html lang="en"> <head> <meta http-equiv="content-type" content="text/html; charset=utf-8"> <meta name="robots" content="NONE,NOARCHIVE"> <title>OSError at /api/recipe/7/image/</title> <style type="text/css"> html * { padding:0; margin:0; } body * { padding:10px 20px; } body * * { padding:0; } body { font:small sans-serif; background-color:#fff; color:#000; } body>div { border-bottom:1px solid #ddd; } h1 { font-weight:normal; } h2 { margin-bottom:.8em; } h3 { margin:1em 0 .5em 0; } h4 { margin:0 0 .5em 0; font-weight: normal; } code, pre { font-size: 100%; white-space: pre-wrap; } table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; } tbody td, tbody th { vertical-align:top; padding:2px 3px; } thead th { padding:1px 6px 1px 3px; background:#fefefe; text-align:left; font-weight:normal; font-size:11px; border:1px solid #ddd; } tbody th { width:12em; text-align:right; color:#666; padding-right:.5em; } table.vars { margin:5px 0 2px 40px; } table.vars td, table.req td { font-family:monospace; } table td.code { width:100%; } table td.code pre { overflow:hidden; } table.source th { color:#666; } table.source td { font-family:monospace; white-space:pre; border-bottom:1px solid #eee; } ul.traceback { list-style-type:none; color: #222; } ul.traceback li.frame { padding-bottom:1em; color:#4f4f4f; } ul.traceback li.user { background-color:#e0e0e0; color:#000 } div.context { padding:10px 0; overflow:hidden; } div.context ol { padding-left:30px; margin:0 10px; list-style-position: inside; } div.context ol li { font-family:monospace; white-space:pre; color:#777; cursor:pointer; padding-left: 2px; } div.context ol li pre { display:inline; } div.context ol.context-line li { color:#464646; background-color:#dfdfdf; padding: 3px 2px; } div.context ol.context-line li span { position:absolute; right:32px; } .user div.context ol.context-line li { background-color:#bbb; color:#000; } .user div.context ol li { color:#666; } div.commands { margin-left: 40px; } div.commands a { color:#555; text-decoration:none; } .user

Also when I import from a website, the picture is never saved, only the text.

Tandoor recipes is on a docker container (made from stack).
Docker is on raspberry pi 4 4go.

**Comment by sebimarkgraf** [comment]
@Squadeur as this is labelled as a setup issue, could you please provide debug information?
Currently, your issue just points to an OSError at the API. 

Please, activate DEBUG in the ENV file and send the output from the logs of the server.

@vabene1111 maybe it would be useful to update the issue template to directly ask for the necessary information. 
Alternatively, a section about debugging issues could be added to the documentation.

**Comment by vabene1111** [comment]
yes, i need to update the template .. i guess `docker-compose logs` output, the .env file and the compose file would be a good starter for most issues. Also the installation method/System OS information

**Comment by vabene1111** [comment]
ok @sebimarkgraf if people use the correct template this is already asked. i have added a few pieces of information that is asked additionally

**Comment by Squadeur** [comment]
I would like to update for this issue.
Soon after I had this issue, I had a problem on my raspberry pi Hard Drive. I had to reset it.
So I switch to an X86 platform and after install it, I never see that issue again.

**Comment by vabene1111** [comment]
ok so this might be related to the arm container .. 

I never tested it but since some people appear to be using this on arm architectures it tought it was working fine. 

I will close this issue for now, if it comes up again we can try to narrow it down to an architecture issue and might be able to fix it.
