### ISSUE TITLE
Outdated Unraid Setup

### ISSUE THREAD

**Issue by CorneliousJD** [vabene1111/recipes#488]
Since the change in name to Tandoor Recipes, and new icon, the unraid documentation here is outdated.

https://docs.tandoor.dev/install/unraid/

Here are some new screenshots to replace them with.

![image](https://user-images.githubusercontent.com/724777/111038251-faa0cb00-83f5-11eb-9807-37815de8d795.png)

(Middle image is fine, no real changes there honestly other than the name)

![image](https://user-images.githubusercontent.com/724777/111038276-16a46c80-83f6-11eb-866b-b3bc9a2efb87.png)

**Comment by vabene1111** [comment]
Do I need to update that? I don't remember creating the unraid page 😂

I will take a look asap

**Comment by vabene1111** [comment]
Ah stupid me, you mean the docs... I will fix that
