### ISSUE TITLE
recently added view

### ISSUE THREAD

**Issue by Tuetenk0pp** [vabene1111/recipes#489]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I'd like to be able to see recently added recipes. It's especeally useful if more than two people participate. 

**Additional context**
not really related to this but maybe consider changing the recipes view to a two collumn layout with taller cards (at least on Desktop). That way we could see a bigger part of the thumbnail without really sacrificing space.

**Comment by vabene1111** [comment]
i will take this into account when refactoring the search page, i like the idea

**Comment by vabene1111** [comment]
closed and linked in search rework issue
