### ISSUE TITLE
Gif recipe import

### ISSUE THREAD

**Issue by brasilikum** [vabene1111/recipes#491]
**Is your feature request related to a problem? Please describe.**
I like to look at recipes on social media in the form of GIFs. Currently those are not supported via Website import. If I understand correctly, this is because sites like giphycat do not have a notion of the recipe metaformat.

**Describe the solution you'd like**
I would like to be able to save those recipes, even if it’s just the Title and gif

**Describe alternatives you've considered**
I could manually download and then upload the gif via normal recipe creation, if gifs were supported as cover image.
What I am currently doing is saving those recipes to my bookmarks. 

**Additional context**
I understand that this import is very flawed and limits the usefulness of other features like the shopping list. That is a trade off I would accept if it means that all my recipes are in one place, categorizable etc.
Fully understand if this is not where this Project want’s to go. Thanks for the gift that is this project!

**Comment by vabene1111** [comment]
interesting use case .. i guess you could use the markdown image format ![](gif url) i think that should work. 

But that means it breaks if the external GIF gets taken down the recipe breaks. I want to add some kind of file management there you would be able to upload gifs and then show them in recipes. 

This wont be happening soon as this is kind of an edge case feature but its definitly a nice idea .. maybe i could also just add GIF support to the external recipe feature

**Comment by vabene1111** [comment]
i have added support for gifs in external recipes with the next update
