### ISSUE TITLE
Info on Paprika format

### ISSUE THREAD

**Issue by ptoulouse** [vabene1111/recipes#492]
Not really an issue, but I thought developers may be interested to know.

As I was reading the documentation, I stumbled upon the section on Paprika.

> Paprika can create two types of export. The first is a proprietary .paprikarecipes file in some kind of binarized format. The second 
    one is HTML files containing at least a bit of microdata.

This is incorrect. The exported Paprika database `Export yyyy-mm-dd hh.mm.ss.paprikarecipes` is in fact a zip file. This zip file contains a bunch of files `recipe name.paprikarecipe`. These recipe files are in fact zipped json files. The json file contains labels such as ingredients, descriptions, nutritional_info, prep_time, cook_time, photo, categories, etc.  The info should be fairly simple to import if someone wants to do it.

**Comment by vabene1111** [comment]
thank you very much. Someone explained that to me a few weeks ago, once i find time for it i will change the importer to use that format. 

Thanks for writing this down

**Comment by vabene1111** [comment]
From the next update on the importer will use the paprikarecipes file and should work much more reliable
