### ISSUE TITLE
Component based recipes

### ISSUE THREAD

**Issue by meelon** [vabene1111/recipes#493]
I really like the idea to have separate recipes for ingredients, which then can be used in another recipe. The issue is you have to keep switching between recipes (for the main dish and for ingredients) back and forth.

Is there any way to have component based recipes like chowdown - example here: https://chowdown.io/recipes/red-berry-tart.html

It would be really usefull to be able to cook the dish on one screen and see steps for main dish and for linked ingredience recipes.

**Comment by vabene1111** [comment]
seeing the steps inside the main recipe is currently not possible but you can link ingredients to recipes. 

It is also planned to have a quick switch feature between recipes so you can have multiple recipes open at the same time and quickly switch between them.

Actually showing the external recipe steps would be cool as well and also technically possible so i will leave this open
