### ISSUE TITLE
Send URL to API for parsing

### ISSUE THREAD

**Issue by marcusisinger** [vabene1111/recipes#494]
A really useful feature of Paprika is the bookmarklet, which sends the current page to paprika for parsing.

This would be possible through the API, but I can't find a method for sending a URL to the server and adding the recipe? 

Such a method would be useful.

**Comment by vabene1111** [comment]
there is currently no endpoint in the api to import an external url. This also wont happen since manual cleaning is needed after most imports. 

What i can do is create a URL parameter or something which would allow to redirect to the import page with an already set external url that gets loaded automatically. In addition one would need to create a small browser plugin i guess ...

i definitely like the idea

**Comment by marcusisinger** [comment]
There is this tool to create a bookmarklet from js code: https://caiorss.github.io/bookmarklet-maker/

Yes, that would work.

**Comment by sebimarkgraf** [comment]
I guess creating a browser extension would be more portable and easier for users to install.
If Chrome on Android ever has support for browser extensions this could be easily installed on mobile as well.
In my opinion sending the JSON to the endpoint and automatically filling the frontend form, would allow to elegantly solve issues like #439 

So, the flow would be basically:
1. User is looking at a recipe on an external web page
2. User activates browser extension
3. The extension extracts the current recipe JSON + sends it to the endpoint in a new tab
4. The endpoint sends redirect to import page including the json
5. The user can adjust the recipe as usual

**Comment by vabene1111** [comment]
that sounds like a very good workflow.

We would need to see how well this works with all the cross origin and protection stuff that is in place in browsers but with an extension this should probably be possible

**Comment by smilerz** [comment]
I have this working in #515

**Comment by vabene1111** [comment]
thanks for linking this so i can close when merged

**Comment by marcusisinger** [comment]
> I have this working in #515

That's great! Where do I create the bookmarklet?

**Comment by vabene1111** [comment]
The feature is not yet merged and will most likely be included in one of the upcoming releases

**Comment by smilerz** [comment]
@marcusisinger this is merged in the development branch.

**Comment by vabene1111** [comment]
it will probably be a few days and then i will update the beta image. If you dont like broken things i recommend waiting for that to be released :D
