### ISSUE TITLE
column cookbook_space.created_by_id does not exist

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#496]
### Version
develop commit af1bc19

### Bug description
after merging, installing new requirements and running migrate I get this when launching the app:
```
Exception Type: ProgrammingError at /accounts/login/
Exception Value: column cookbook_space.created_by_id does not exist
LINE 1: ...T "cookbook_space"."id", "cookbook_space"."name", "cookbook_...
```

**Comment by vabene1111** [comment]
thats not good 🤔 what kind of setup are you running ?

Can you please post the log output of running the migrations and starting the application ?

**Comment by smilerz** [comment]
I'm running in conda on Windows.  
I didn't notice this before - but I think I figured out what is going on - manage.py migrate isn't picking up the .env settings.
Migrate says there aren't any more migrations to apply, but starting the server claims that there are 7 to apply.

**Comment by vabene1111** [comment]
that could definitely cause the issue you describe but it could also be an issue on my end, the space owner is kinda hacky ..

please report back if you could fix it or if you need any help

**Comment by smilerz** [comment]
Yep, that was it.  When I merged your update it took out my load_env().
However, now I'm getting permission denied after logging in:
![image](https://user-images.githubusercontent.com/1808639/111683070-12f85780-87f3-11eb-8d63-9a0153641b72.png)

**Comment by smilerz** [comment]
and I still had access to admin - all good.

Thanks!

**Comment by vabene1111** [comment]
ok perfect 👍
