### ISSUE TITLE
Kubernetes manifests

### ISSUE THREAD

**Issue by hakoerber** [vabene1111/recipes#50]
Hello,

I currently run this application on a Kubernetes cluster and have working manifests.

Are you interested in upstreaming them? Similar to the docker-compose files.

**Comment by vabene1111** [comment]
i have absolutely no idea about kubernetes but if these files help others deploy this in kubernetes then i think it would be great to add it. 

Just put it in the `docs` folder and write a little readme how to use it and maybe a small disclaimer that this isn't verified/tested when updating (at least not by me as i have no idea how it works).

You can also add a little comment to the main readme pointing out that there is a kubernetes manifest in the docs folder. 

If you dont want to create a PR just post the file here and if necessary some instructions and i will integrate them.

**Comment by hakoerber** [comment]
Thank you for your response!

The Kubernetes manifests are a bit similar to docker-compose.

> Just put it in the docs folder and write a little readme how to use it and maybe a small disclaimer that this isn't verified/tested when updating (at least not by me as i have no idea how it works).

Ok, I'll create a PR in the next few days, then you can take a look. I need to sanitize my setup a bit and make it generic.

**Comment by hakoerber** [comment]
Hey, I just opened a PR, feel free to take a look.
