### ISSUE TITLE
Add nutritional summary to mealplan

### ISSUE THREAD

**Issue by sebimarkgraf** [vabene1111/recipes#500]
**Is your feature request related to a problem? Please describe.**
When planning meals, it would be helpful to directly see the sum of planned values.

**Describe the solution you'd like**
Maybe a small summary field, that shows always the sum of the day or when it is clicked/hovered.

**Additional context**
Probably best, to implement it after the move of the meal plan to the new vue system.

**Comment by vabene1111** [comment]
yes definitly a good idea. When moving this to the new system i will consider this (along with images, maybe descriptions or some cool popovers 🤔 )

**Comment by DiversityBug** [comment]
Maybe worth considering, the current version 0.15.2 re-calculates the recipe's nutrition value when the servings are changed.
Recipes e.g. taken from the web usually include nutrition values per serving, hence one would assume it is not re-calculated when changing the servings in a meal but remains per serving.

**Comment by sebimarkgraf** [comment]
Ah, I've just realized this is a duplicate of #336.
Probably easier to close it here and track it just once.
