### ISSUE TITLE
Import / Export plugin structure

### ISSUE THREAD

**Issue by sebimarkgraf** [vabene1111/recipes#502]
**Is your feature request related to a problem? Please describe.**
As more and more import/export requests seem to exist, it could be a wise idea to create a fixed import/export interface and allow the usage of plugins.

**Describe the solution you'd like**
e.g. Using http://pluginbase.pocoo.org/
An import recipe plugin interface
An export shopping list plugin

**Describe alternatives you've considered**
All integrations could be done in recipes themselves, but either way, an interface needs to exist. In the case of plugins, it would be simpler for end-users to write their own integration.

**Comment by vabene1111** [comment]
hmm interesting idea. I have create the import/export system in such a way that it is very configurable and flexible. It also has well documented standard methods so its basically dropping a python file into a directory and setting some values somewhere.

Plugins would be a really great thing but i feel like it would be a lot of work. As long as i actively maintain this application (which i plan to do for a while) anyone can just PR the new integration/storage provider and i will merge it in. Developing this way would be easier as well as there is no plugin overhead. 

Maybe this is something that can be done in the very long run, will close this for now but keep it in mind
