### ISSUE TITLE
[Feature Request] Support ChefTap import

### ISSUE THREAD

**Issue by ModdedGamers** [vabene1111/recipes#509]
**Is your feature request related to a problem? Please describe.**
My family has been using the closed-source ChefTap app for a while, and I want to show them Tandoor as a demo to switch away from ChefTap. However, there is no "Import from ChefTap" function, and importing the ~500 recipes by hand would be way too tedious.

**Describe the solution you'd like**
An import option for ChefTap on the imports page.

**Describe alternatives you've considered**
None of the other import functions work.

**Additional context**
ChefTap uses a very simple plain text export format, and an export is simply a zip file named cheftap_export.zip. Please find attached a sample of recipes that should hopefully help if someone needed to test this.
[cheftap_export.zip](https://github.com/vabene1111/recipes/files/6217459/cheftap_export.zip)

**Comment by vabene1111** [comment]
the text files dont have much structure but i think this should be possible (it is similar to some other exports already working).

will see if i can include this in the next release.

**Comment by vabene1111** [comment]
Different formats found so far 

- no ingredients header 
- Instructions and Directions used for the same thing, sometimes no header is present
- Notes optional field in some exports

**Comment by vabene1111** [comment]
ok so i have added an importer for cheftap with the next release. It is not very optimal given the super unstructured data but it should work.

@ModdedGamers if you are a long time customer with them (you say you have 500 recipes) you might ask them to implement a better exporter. They are probably not interested in you leaving so i dont think this will be very likely but could improve the results significantly. 

Another way would be to import the recipes directly from their source pages. All examples you provided contain urls which might be imported again, but this of course would be a lot of work as well.

**Comment by ModdedGamers** [comment]
Alright, thanks!

**Comment by wilmardo** [comment]
Just to add to this since I was missing this feature too, I wrote a hacky scraper that gets the URLs stored in cheftap:
https://github.com/wilmardo/cheftap-recipe-export

So Tandoor or any other app can scan them again, this won't help for recipes added/edited by yourself but for a whole bunch it does :)
