### ISSUE TITLE
Paprika Improvements

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#522]
feedback by @jt196 in https://github.com/vabene1111/recipes/issues/123#issuecomment-813436394

just having a bit of a play around with the Paprika file import in the beta release. Looks like it's working much better, including images, which is a huge improvement. Great job! 

A couple of things that are missing which if imported would make me think seriously about migrating, some of them already have existing fields in the Tandoor data, so I guess just need mapping. Others not much so. I've currently nearly 600 recipes in Paprika, so manually adding this would be a lot of work! 

- **Categories > Tags** (currently the import has an 'imported' tag, but all my category data in Paprika is missing)
- **Description > Description** (this doesn't seem to be imported)
- **Notes > Comments** (I'd love to see the notes section in the Paprika file imported as the top comment on the Tandoor recipe, not sure how easy it would be to do this but it'd be a good way to preserve the data)
- **Prep time/cook time > Prep/cook time** (not imported)
- **Servings > Servings** (defaults to 1 serving)
- **Source** - it'd be nice to retain the source URL and/or text, or even have this in the inline text as a reference like the nutrition data is currently, and source is done during a URL import. 
- **Nutrition** - seems to be imported into the bottom of the recipe. TBH this isn't a bother for me as I don't use the field a lot.

**Comment by jt196** [comment]
Additionally, I've noted:

1. Import seems to stop after about 10 recipes. I get this error message on the Docker logs:
```
172.29.0.1 - - [05/Apr/2021:16:05:08 +0100] "GET /api/import-log/2/ HTTP/1.1" 200 127 "http://localhost:8080/import-response/2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.91 Safari/537.36"
```
2. I've tried using the do not import duplicate recipes with the same set of data (to avoid having to remove the imported recipes from the zip file), but all the same recipes seem to be importing as duplicates, it's also hanging at the same spot.

**Comment by vabene1111** [comment]
can you provide me with an example export that is breaking up ? because the new system was purposly build to avoide the timeouts and i am not sure if its just not working or if it is because of the export itself ?

**Comment by jt196** [comment]
[ImportFail.zip](https://github.com/vabene1111/recipes/files/6258851/ImportFail.zip)

Here it is. So it's failing on the v2 recipe, I thought I'd include the v1 recipe as it's working on that and has a similar title etc. As I'm sure you're aware, I think you'd just need to rename the file with a .paprikarecipes extension to do the import.

**Comment by jt196** [comment]
It's importing the title of the v2 recipe, but nothing else gets imported.

**Comment by vabene1111** [comment]
that kind of indicates an exception during the import, i will test that out and get back to you after i have solved the deployment issues

**Comment by vabene1111** [comment]
ok the issue was related to an empty ingredient line in the v2 recipe. This will be fixed in the v0.15.0 release once i get it to build properly ..

**Comment by vabene1111** [comment]
ok all fields have been added. Also the duplication check has been fixed, it was broken before. Will all be included in the next release

**Comment by jt196** [comment]
Blimey that was quick!

**Comment by jt196** [comment]
Looking great! The v2 recipe import more or less worked OK. The units are a bit borked though, see the image below:

![image](https://user-images.githubusercontent.com/8290163/113602016-fef98600-9639-11eb-9cf0-8a2a0e4feb57.png)

vs Paprika:

![image](https://user-images.githubusercontent.com/8290163/113602252-4b44c600-963a-11eb-87de-33a41e030d98.png)

**Comment by jt196** [comment]
(it's scaled down to 1 pizza, which is fine as it's easy enough to change that). 

I can get 1-2 tsp not working, but 360g bread flour should be straightforward. Nice that the bracketed text appears in the note column.

**Comment by vabene1111** [comment]
i can see your problem. Honestly i dont really know what can be done about this. The ingredient parser tries to do its best to split the string into an amount, a unit and a food (and possible an note). 

With you ingredients having both grams and tsp it cannot determine which part of the string belongs to which part of the ingredient. This obviously makes it pretty useless for you but i dont know how to explain this very special case to the parser without breaking tons of other things (at least not without a ton of effort)

The bread should definitely work and it is working for me
![image](https://user-images.githubusercontent.com/6819595/113602935-97e0cf00-9643-11eb-8f2a-1de8f324b34e.png)

i will need to manually open the export you gave me to see what is wrong here

**Comment by jt196** [comment]
Another attempt at import and it seems to get stuck on this one: 

[Alpine Trail Bars.zip](https://github.com/vabene1111/recipes/files/6259521/Alpine.Trail.Bars.zip)

It's the most recent beta image by the way, importing past the v2 up to 16 recipes now!

**Comment by jt196** [comment]
I don't know how easy it would be to do this but it'd be nice to have some feedback on import. At the moment, we have the spinning disc, and if there's an error, the only way of finding out is by heading to the statistics and seeing whether the number of recipes is increasing or not.

**Comment by jt196** [comment]
Weirdly the trail bars recipe seems to import OK on it's own, but the import doesn't finish.

**Comment by vabene1111** [comment]
yea i think i should add a broader exception around the whole thing to actually show all issues to the user if something gets stuck.

A progress bar is also something that is planned but i wanted to get the base working as fast as possible thats why its not implemented yet
