### ISSUE TITLE
Weird Behaviour of Servings Field

### ISSUE THREAD

**Issue by sebimarkgraf** [vabene1111/recipes#526]
### Version
v0.15.0 but already existed before

### Bug description
When trying to type a new servings number in the servings field the field behaves weirdly depending on the browser.
Numbers are added at the wrong place or cannot be deleted.

### Potential Solution
I assume this is due to the "rtl" text direction. As this problem is more noticeable on mobile phones, a fix could include setting
the text direction to "ltr" again and change the styling by adding the spin buttons manually.
One could try to integrate something like this or write a custom version: https://vuejsexamples.com/a-customizable-number-input-spinner-component-for-vuejs/

**Comment by vabene1111** [comment]
Do i understand correctly that this happens when viewing the recipe and not when editing it ?

**Comment by sebimarkgraf** [comment]
Yes, only when viewing the recipe and adjusting the number in the servings field.
Especially, Safari on iOS seems to struggle, but as far as I know, you don't have an ios device for testing.

**Comment by vabene1111** [comment]
yes the old problem 🙈  i will investigate what can be done about this. I never really liked the way the serving field works but so far haven't found a better solution

**Comment by Korndaweizen** [comment]
I can confirm this behavior on Android with Chrome.
