### ISSUE TITLE
Transform html entities

### ISSUE THREAD

**Issue by fayoh** [vabene1111/recipes#527]
### Version
v0.14.5

### Bug description
Some websites I like to use seems to feed me html entities for non ascii characters. I am not familiar with any of the libraries or languages for that matter 😆 used in this project, so I haven't looked into what is possible. But it feels like it would be pretty straight forward to transform these enitities to utf-8 or what is used internally.

### Example:
https://www.ica.se/recept/ostgratinerade-guajillochips-med-pulled-chicken-och-jalapeno-727915/ gives me an import with these nice instructions
```Ta ut pl&aring;ten ur ugnen och toppa med salladsl&ouml;k, lime, gr&auml;ddfil och jalape&ntilde;os.```

**Comment by vabene1111** [comment]
yes this should be fixed. Could you please verify that this issue still happens with the latest version (0.15.0). If so i will see what can be done about it

**Comment by fayoh** [comment]
Oh, I thought I was using the latest version. D'oh.

Will upgrade and test again

**Comment by vabene1111** [comment]
it was just released yesterday so no worries.

**Comment by fayoh** [comment]
One step in the right direction. Now the description looks right, but the instructions still have the same problem.

**Comment by vabene1111** [comment]
thanks @smilerz for already fixing this 👍 i will leave this issue open to manually verify it after merging the PR

**Comment by smilerz** [comment]
> thanks @smilerz for already fixing this 👍 i will leave this issue open to manually verify it after merging the PR

I was already in that part of the code writing tests, so I knew exactly where to fix it.
