### ISSUE TITLE
Cannot create new users

### ISSUE THREAD

**Issue by IxsharpxI** [vabene1111/recipes#528]
I am not able to create new users? I go to admin>users section and i only have the pencil. Not the add option. How do i add new users and assign spaces. Can admins see all spaces or can users share spaces?

**Comment by IxsharpxI** [comment]
And where can i add more groups?

**Comment by IxsharpxI** [comment]
Also, i had an old non super user that no can’t be added to any spaces. So when they login it says no space. How do i assign spaces to users already created?

**Comment by vabene1111** [comment]
These are some very good questions and show that i definitely need to update the documentation on this 🙈 

1. New users are created from the system page using invite links. This is because some custom logic is run when a user signs up and i havn't had the time to implement the same logic in the admin as well
2. There is no way to add groups, they are basically hard-coded dont change them
3. Spaces are assigned trough the User Infos table but you get them automatically when using the invite links

**Comment by IxsharpxI** [comment]
thank you for the reply. in the user info table i only have the following options. not a way to assign spaces. this is a user i created back in version 14 before they existed. If i have 3 users with 3 different spaces. can the superadmin see all 3? can the users share spaces or recipes between each other? or are they purposely separate and unshareable?

<img width="1066" alt="Screen Shot 2021-04-06 at 3 04 11 PM" src="https://user-images.githubusercontent.com/42504574/113771741-66bada00-96e9-11eb-987d-9ecebe781d15.png">

**Comment by vabene1111** [comment]
the screenshot does not show the user info table but the default user table. This is not really intuitive and there are currently no real systems in place to manage stuff trough the admin. I recommend using the system page and invite links and just the default space. 

In general spaces are completely separate but can each have multiple user (like slack or a private github repo).

its user preferences, sry
![image](https://user-images.githubusercontent.com/6819595/113778645-f766d980-972c-11eb-819a-ff04043457ce.png)

spaces are working but not really built into the UIs and documentation so use them if you want to play around but its probably going to take a few more updates before they are really ready

**Comment by IxsharpxI** [comment]
thanks. this is resolved on my part

**Comment by vabene1111** [comment]
i have added documentation to the new faq section of the docs (not yet pushed).
