### ISSUE TITLE
Public shared links do not work on 0.15.1

### ISSUE THREAD

**Issue by zurchpet** [vabene1111/recipes#533]
### Version
Version: 0.15.1

### Bug description
Example URL: https://rezepte.zuercher.it/view/recipe/9/7857ccf0-e42c-45bb-a804-1047fcafa44e
Before I could give anyone the shared link to a recipe and get the recipe shown.
Now I only get a 

> There was an error loading a resource! {"detail":"Nicht gefunden."}

The JSON is the response of the api to the request to /api/recipe/9 which only gives a valid result if logged in.
Returns the shown JSON `{"detail":"Nicht gefunden."}` otherwise.

Please tell me if I can provide further information to correct this issue.

**Comment by vabene1111** [comment]
fixed in the upcoming release

**Comment by zurchpet** [comment]
Thank you very much 💯

**Comment by Korndaweizen** [comment]
@vabene1111  Did you recently change the requests that are necessary for the shared recipies?
I used the following Regex for my Authelia/Traefik setup, to bypass the shared links.

- "^/view/recipe/[0-9]+/[a-zA-Z0-9]{8}-([a-zA-Z0-9]{4}-){3}[a-zA-Z0-9]{12}$"
 
Do I need to adjust my bypass settings, or will this issue be resolved with your fix in the upcoming release?

**Comment by vabene1111** [comment]
i did not change that view but there are additional requests that are required for the recipe view to work.

mainly a request to api/recipe/<id>/share?= (if i remember correctly)

Why do you block all routes using your atuh setup if i may ask ? because all views are protected by authentication checks anyway and if i understand correctly authelia just provides the auth context ?

**Comment by Korndaweizen** [comment]
As far as I remember I also bypass any calls to /api and /media which were also required as I set up my docker, so this should work. 

Anyways, you are asking a very good question. Lets call it a historical decision. Currently I block any and all requests that are not authenticated, to all of my subdomains. In case of recipes I might reconsider this restriction, as it is the only service I am hosting, that I am willing to share with other users (friends and family). And just like you said, the authentication is handled by authelia + recipes anyways 👍

**Comment by vabene1111** [comment]
ok thanks for the info. I totally respect your decision to block of recipes and it cant hurt from a security standpoint, just wanted to make sure that there is no shortcoming on my side that would require this.
