### ISSUE TITLE
Cannot delete comments

### ISSUE THREAD

**Issue by auanasgheps** [vabene1111/recipes#560]
### Version
Version: 0.15.2

### Bug description
When I click the "pencil" icon next to a comment, I get Server Error (500).

![image](https://user-images.githubusercontent.com/20586878/115008053-f65f4600-9eaa-11eb-9bfd-b2b4c333bd4a.png)

Docker container logs don't show much:

```
172.18.0.5 - - [16/Apr/2021:11:57:27 +0200] "GET /manifest.json HTTP/1.1" 200 1117 "https://recipes.nas.example.com:8080/view/recipe/8" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
172.18.0.5 - - [16/Apr/2021:11:57:29 +0200] "GET /service-worker.js HTTP/1.1" 200 45204 "https://recipes.nas.example.com:8080/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
```

**Comment by vabene1111** [comment]
a yea i think i noticed that issue a while ago but never wrote it down. thanks for reporting, i will need to fix that.

**Comment by vabene1111** [comment]
fixed with the next update. Comment editing/deleting is still pretty garbage but i do not have time to improve it at the moment. Will be something for a future update
