### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by auanasgheps** [vabene1111/recipes#561]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.15.2

### Bug description
Some UI elements are not translated even though my translation is complete (I am the Italian translator). I've tried other translations and results are the same.

In this screenshot:
- Preparation
- Waiting
- Servings
- Ingredients
![image](https://user-images.githubusercontent.com/20586878/115008428-640b7200-9eab-11eb-83a5-ba764d105fff.png)

Here all entries are in English.
![image](https://user-images.githubusercontent.com/20586878/115008520-800f1380-9eab-11eb-8c3b-3fd4e344baa3.png)

Here many settings are in English.
![image](https://user-images.githubusercontent.com/20586878/115008838-e85df500-9eab-11eb-8b0c-ff6a33d47a7c.png)

Other than english entries, here the title is guessed.
"Liste della spesa Elenco" is something I haven't translated, it is guessed. Please expose this kind of entries.
![image](https://user-images.githubusercontent.com/20586878/115009080-2c50fa00-9eac-11eb-9f75-b17095d4a7a4.png)

**Comment by vabene1111** [comment]
I have recently moved to the new vue based translation system, i will need to verify what is causing these issues ..

**Comment by MaxJa4** [comment]
+1 for the German translation.
Especially "Preperation", "Waiting",... like in the first screenshot.
Seems to be a general issue for (maybe) all languages.

**Comment by auanasgheps** [comment]
> Seems to be a general issue for (maybe) all languages.

Yep, I've checked a couple of languages and all those strings are untranslated. Since those translation are _completed_, the issue is in the app.

**Comment by vabene1111** [comment]
i assume that this is because it did not implement any language switcher. I thought that it would, like django, just determine the language automatically but that seems to not be the case.

**Comment by vabene1111** [comment]
ok should be fixed with the next release. The technical solution is shitty but works for now
