### ISSUE TITLE
Nextcloud Importer failing

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#563]
Hello there, this looks like a really nice project. However I can't seem to import all my recipes from NextCloud Cookbook. 

I have approximately 150 recipes, but by trying to import them into Tandoor Recipes it only imports around 50. They all seem to have the same structure, as described in the Tandoor documentation. If I try to run the importer again on the zip file, I get "0 recipes imported". 

Is there a way to troubleshoot what could be wrong with the 2/3 of the recipes that aren't getting imported? Is there anyone else having issues or success stories importing from NextCloud Cookbook?

Thanks!

_Originally posted by @quamok in https://github.com/vabene1111/recipes/discussions/559_

**Comment by cvinhaes** [comment]
Same issue here.

**Comment by thisisbenwoo** [comment]
Same here. I screwed up my Nextcloud install (still in test mode), and I only have about a dozen recipes. I followed the docs, and zipped up the /Recipes directory into Recipes.zip. I uploaded it in to my Nextcloud directory, but I can't find how to change the type to Cookbook. Thanks.

**Comment by vabene1111** [comment]
@thisisbenwoo i do not really understand your question ? This is not nextcloud cookbook but tandoor recipes. If you want to import your recipes from NC Cookbook you can do so under the importer tab but there is currently a little issue that i need to resolve.

**Comment by thisisbenwoo** [comment]
I'm sorry, I misunderstood. Should not be trying to figure these things out past midnight!

**Comment by vabene1111** [comment]
haha no worries, if you need any help feel free to ask

**Comment by vabene1111** [comment]
ok so the issue was related to recipes with special characters in their names not being discovered. 

I have fixed this for the next release, there might be a beta soon

**Comment by quamok** [comment]
thank you so much for fixing this. It worked perfectly. However, I had 1 recipe that didn't import because the description had more than 512 characters. I didn't get any warning. I only got the warning when I imported the recipe manually.

**Comment by vabene1111** [comment]
ok thats an easy fix, i will create a new issue and implement it with the next update. Glad you like it
