### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL

### ISSUE THREAD

**Issue by DiversityBug** [vabene1111/recipes#577]
### Version
Version: 0.15.2

### Information
Exact URL you are trying to import from: 
https://www.hellofresh.de/recipes/glasnudeln-mit-bulgogi-rinderhackfleisch-602b84423f3a9c111d3db852?isMegaAddonsEnabled=false

When did the issue happen: 
When importing after the page has loaded.

Response/Message shown 
![Server error 500](https://user-images.githubusercontent.com/82063721/116090103-0b9a5880-a693-11eb-9328-f976b33779c8.png)

Message
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
[Cookbook_Web.zip](https://github.com/vabene1111/recipes/files/6377434/Cookbook_Web.zip)

**Comment by vabene1111** [comment]
the issue was that it failed to get the image properly. I have fixed this issue with the next update
