### ISSUE TITLE
Localization String escape on shopping list

### ISSUE THREAD

**Issue by Dryusdan** [vabene1111/recipes#580]
Hello :)
 
### Version

Version: 1.15.2

### Bug description
I have install recipes with [manual](https://docs.tandoor.dev/install/manual/) explication.

I follow this step by step, and application work well but somes JS files doesn't work : 

In /shopping/, the form don't display and firefox console return this error : 
```
Uncaught SyntaxError: missing ) after argument listshopping:895:81
```
I encounter this problem also on Chromium. I can't reproduce this error on demo :/ 

I found another error when I want to add recipes in book but i can't reproduce, so I think is solved ^^ 

Thank for your help :)

**Comment by vabene1111** [comment]
Is there anything else in the browser console ?
Can you click on the link in the console and copy the relevant piece of code (if you need help with that let me know)

Please also provide a detailed overview of your setup

**Comment by Dryusdan** [comment]
Nope, nothing else.

This line is faulty
```
                                this.makeToast(gettext('Error'), 'Une erreur s\\'est produite lors de la création d\\'une ressource !' + err.bodyText, 'danger')
```

Ho, I found the problem, if I set langage to English it work well. 

Also, my setup is on Debian 11 (sid), with python 3.9. I use gunicorn with socket. Nginx and postgresql).

Here my config file : 
```
DEBUG=0

ALLOWED_HOSTS=*

SECRET_KEY=

TIMEZONE=Europe/Paris

DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=

FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=0
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
SOCIAL_DEFAULT_ACCESS=0
```

**Comment by vabene1111** [comment]
yes this is a problem with the old translation system that some languages escape in javascript. I will fix this

**Comment by Dryusdan** [comment]
Yes, thank ^^ 

I think only 3 backslash are usefull no ?

**Comment by vabene1111** [comment]
i need to verify that but i replaced the translation system anyway so this probably wont be an issue with the new one

**Comment by vabene1111** [comment]
fixed in next release, i overlooked one translation case, thanks for the patience
