### ISSUE TITLE
When no rating is submitted in CookLog, the value 0 is used for the average rating

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#581]
### Version
Version: 0.15.2

### Bug description

To reproduce: 

- Add cookinglog with a rating of 5
- Add cookinglog without a rating
- Average is then 2.5

I tried fixing it myself, unfortunately I was unable to find the section in the source code that processes the cookinglog :/

**Comment by vabene1111** [comment]
oh this should not be the case .. the rating system will be moved to the frontend anyway with the next update and i will need to rework it so i will fix it there.

#556

**Comment by Forceu** [comment]
The issue seems to be still present in the latest version unfortunately.

**Comment by vabene1111** [comment]
it is also still open in #556 :) sorry for it taking so long, had some important stuff last week, hope to get some features and fixes out this week

**Comment by Forceu** [comment]
Ah sorry, I didn't realise that it was added there, I thought it was fixed as the issue was closed ;) Thanks a lot for your hard work!!

**Comment by vabene1111** [comment]
no worries, already fixed the old search in cdbcc971b17eb3c96432683c4deddad9b5ad659a will be included in the next release. Now to see how to implement it for the new search
