### ISSUE TITLE
Ingredient Parser - Incorrect parsing when there is no space between quantity and unit

### ISSUE THREAD

**Issue by itsmegb** [vabene1111/recipes#582]
### Version
Version: develop

### Bug description
The Ingredient parser does not currently account for having the amount and unit joined into one value, e.g. 400g.
The result is the ingredient being parsed incorrectly.

For example, take the following ingredient:

- 400g unsalted butter

The parsing will result in:

- 400  - amount
- unsalted - unit
- butter - ingredient

The following recipe is an example that shows this behaviour: https://www.bbcgoodfood.com/recipes/best-ever-chocolate-brownies-recipe

**Comment by itsmegb** [comment]
Closer inspection shows that the parser does correctly determine the amount and unit initially, but because the ingredient contains 2 words ("unsalted" "butter") the parser then overrides the initial unit ("g") with what it expects to be the unit in a 3 part ingredient ("unsalted").

**Comment by vabene1111** [comment]
Interesting case. Will need to be addressed in the parser
