### ISSUE TITLE
Duplicate Foods

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#588]
For some reason there are duplicate foods in my test instance. find out why and fix

**Comment by smilerz** [comment]
I found that and fixed it in #505.  there were inconsistent uses of get_or_create on food and keywords and also inconsistent uses of .strip() to clear out leading and trailing spaces.

**Comment by vabene1111** [comment]
ah thats good to know, thanks for reminding me :joy: did you also add a migration to remove any duplicate foods ? if not no worries, i can do that

**Comment by smilerz** [comment]
I did not look into that.  I kept merging them when I found them.

**Comment by vabene1111** [comment]
ok perfect, i had some trouble merging one of the duplicates so i will probably add a migration. Thanks for fixing the base issue, hope to get your PR merged this week or next

**Comment by smilerz** [comment]
that would be awesome - thanks!  My base code is starting to drift pretty far and its getting hard keeping it rebased to your version.  Hahaha.

**Comment by vabene1111** [comment]
i am sorry, too much stuff going on at the moment and also the search rework taking much longer than expected. Hope to at least get a stable beta soon

**Comment by smilerz** [comment]
no need to apologize!

**Comment by vabene1111** [comment]
ok after some extensive testing i noticed that the food in question (in my database) hat a space at the end. 

This did not cause a uniqueness validation on the database as they are technically different but apparently causes issues with DRFs or djangos uniqueness checks 🤔 

i am not introducing a migration for this as the ingredient merge feature can take care of this and a migration like this would be very slow on large existing databases and nobody reported having these problems. I think they might be related to the telegram bot feature which is not widely used
