### ISSUE TITLE
Error Generating API

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#592]
### Version
Latest develop commit: c661646

### Bug description
openapi-generator-cli generate -g typescript-axios -i http://127.0.0.1:8000/openapi/ yields the following error

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).

 | Error count: 2, Warning count: 0

Errors: 
  -attribute paths.'/api/recipe/{id}/image/'. Declared path parameter id needs to be defined as a path parameter in path or operation level

 -attribute paths.'/api/recipe/{id}/'. Declared path parameter id needs to be defined as a path parameter in path or operation level
```

**Comment by vabene1111** [comment]
thanks! interestingly this endpoint was already this way when i first generated the spec but maybe some other changes broke this. I will see how this can be fixed and update the spec accordingly

**Comment by smilerz** [comment]
I think it is probably this, the super() returns an empty list.  But I didn't understand what it was trying to do, so didn't mess with it.  Maybe poor interaction between this and the action decorator on RecipeViewSet.image()?

```
class RecipeSchema(AutoSchema):

    def get_path_parameters(self, path, method):
        if not is_list_view(path, method, self.view):
            return []

        parameters = super().get_path_parameters(path, method)
        parameters.append({
            "name": 'query', "in": "query", "required": False,
            "description": 'Query string matched (fuzzy) against recipe name. In the future also fulltext search.',
            'schema': {'type': 'string', },
        })
        ...
```

**Comment by vabene1111** [comment]
thats possible. The image endpoint is also rather stupid and hacky as i did not know how to do it better back then. Probably something that should be rewritten at some point but for now i will see how the generator can be fixed

**Comment by vabene1111** [comment]
fixed. Issue was that i created a custom shema for the recipe view and in the function returned an empty array for all non list views. This is wrong as all non list views have `id` as a parameter so thats needed
