### ISSUE TITLE
Ability to reference other recipes within recipe step.

### ISSUE THREAD

**Issue by momab** [vabene1111/recipes#594]
**Is your feature request related to a problem? Please describe.**
When creating a recipe that needs a i.e. a sauce, you create the same step for every recipe. This is pretty cumbersome.

**Describe the solution you'd like**
As stated in the title, having the ability to reference other recipes as steps would be great.

**Describe alternatives you've considered**
Tbh, i do not have any other way of solving this.

**Additional context**
See grocy. They have this feature and it is great!

**Comment by vabene1111** [comment]
there is currently a feature to link ingredients to recipes

it is also planned to have something like this, it was discuessed in #493 

basically the plan is to allow steps to be recipes
