### ISSUE TITLE
Error 500 when trying to edit comments

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#599]
### Version
Version:  latest (0.15.2)

### Bug description
Whenever I click on the edit icon on a comment, I get a server error 500, therefore no comment can be edited. Let me know if you are unable to reproduce the error, in that case I can try to gather more information. :)

Thank you for this amazing app!

**Comment by vabene1111** [comment]
will be fixed in the next update :) if not feel free to raise a new issue
