### ISSUE TITLE
[Feature Request] Support CookBookApp import

### ISSUE THREAD

**Issue by iceman73** [vabene1111/recipes#601]
**Is your feature request related to a problem? Please describe.**
We have been using the TheCookBookApp.com  for some time now in my family and would like to move everyone to your App, but importing all those recipes by hand into Tandoor would not be good use of time if we could import them directly.

**Describe the solution you'd like**
An import option for TheCookBookApp on the imports page.

**Describe alternatives you've considered**
Doing this by hand

**Additional context**
The CookBookApp allows export by YAML and HTML, and I have included samples of both

[CookBook-Recipes-YML-20210504090521.zip](https://github.com/vabene1111/recipes/files/6424161/CookBook-Recipes-YML-20210504090521.zip)
[CookBook-Recipes-HTML-20210504170587.zip](https://github.com/vabene1111/recipes/files/6424162/CookBook-Recipes-HTML-20210504170587.zip)

**Comment by vabene1111** [comment]
The yaml format looks pretty decent, thanks for providing the example. I will try to get this into the next release

**Comment by vabene1111** [comment]
cookbookapp is included in next release. one of the example files you provided has malformed yaml which will fail the import, i dont know if this is common, if you have a big list of recipes to test with and many of them fail let me know and i will try to find a workaround for the broken yaml, if its just that single one i think its probabaly not a big problem
