### ISSUE TITLE
Sub Steps

### ISSUE THREAD

**Issue by jiggad369** [vabene1111/recipes#605]
Would it be possible to implement sub steps? The main "segment" would be more like a header with steps below it and collapsable for all steps underneath.

e.g.:

-**Segment 1: Pie crust** (Main step header)
  -Step 1: Make the dough
  -Step 2: Bake the dough

-**Segment 2: Pie filling** (Main step header)
  -Step 1: Chop the fruit
  -Step 2: Make the fruit filling
  -Step 3: Chill the filling

-Segment 3 and so on...

**Comment by vabene1111** [comment]
i guess you could just use a markdown headline and have a otherwise empty step 🤔

Other than that i am debating if adding extra technical complexity for this feature is justified ... but i will leave this open, maybe there is some input from the community

**Comment by vabene1111** [comment]
it is now possible to add recipes as steps which basically gives this functionality, together with markdown this should suffice
