### ISSUE TITLE
Typo that will cause reverse proxy failure

### ISSUE THREAD

**Issue by lbarnett83** [vabene1111/recipes#611]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.15.2

### Bug description
In the documentation for authentication, there is a typo that will cause a reverse proxy to fail.

Current text:

```  # Required to allow user to logout of authentication from within Recipes
  # Ensure the <auth_endpoint> below is changed to actual the authentication url
  location /accounts/logout/ {
    return 301 http://<auth_endpoint>/logout
  }
```

Update text:
```  # Required to allow user to logout of authentication from within Recipes
  # Ensure the <auth_endpoint> below is changed to actual the authentication url
  location /accounts/logout/ {
    return 301 http://<auth_endpoint>/logout;
  }
```

Please note the added `;` at the end of the return 301 instruction.

Thanks for the great software

**Comment by vabene1111** [comment]
fixed in #616
