### ISSUE TITLE
Import from OpenEats

### ISSUE THREAD

**Issue by thechickenmoo** [vabene1111/recipes#628]
I've been running an openeats instance for my family recipes. (https://github.com/open-eats/OpenEats)

The Developer seems to have stopped developing openeats and I like the look and feel of the Tandoor Recipes system after setting up a quick test instance. 
I love the import function and was able to use it on a number of external recipe sites, but get errors when trying to use it on my openeats instance.  (Malformed Data)

I really don't want to have to manually copy/paste the recipes if I don't have to. 

Here's an example page on my instance:
https://openeats.thechickenmoo.com/recipe/logsagna

**Comment by vabene1111** [comment]
Thanks for the feedback, i would definitly like to support open eats. 

As you know the plattform better: Is there any way to export data from the interface ? 

If not which database systems are used, maybe one could write a small script to dump the database to an importable format. 

If you have some sample data that would be aweseome (the link indeed does not provide any structured data)

**Comment by thechickenmoo** [comment]
I haven't found any way to export anything. I think it was on the Dev's plan but not implemented and that was in 2019. 
Most of the data is in an instance of mariadb. I keep copies of the dumps fairly often as my backup method but that's about the extent of my knowledge in that direction. Would something like that serve?

**Comment by vabene1111** [comment]
Ok that information definitly helps. I see two options here

- build a custom scraper that can import from the web pages (one recipe at a time)
- export the database as a CSV file or something similar and build an importer for that

if you want you can email me a dump of your database or a partial one so i can take a look, you can email it to info@tandoor.dev

**Comment by vabene1111** [comment]
@thechickenmoo i am working on building the importer but the open eats setup is giving me lots of troubles. Can you provide me with some sample data using the dumpdata command like this: `dumpdata recipe ingredient` 

if you followed the openeats default setup this should work using `docker-compose -f docker-prod.yml run --rm --entrypoint 'sh' api ./manage.py dumpdata recipe ingredient` the output is a long json string that can be piped into a file.

Feel free to send it to me at info@tandoor.dev

**Comment by vabene1111** [comment]
The importer is included in the latest development build, if you send me some data i can implement additional features.
