### ISSUE TITLE
recipe calculator fails when using "0.5" units.

### ISSUE THREAD

**Issue by Tangogr** [vabene1111/recipes#63]
If there is "half" unit in the recipe, using "0.5", the quantity calculator fails.

### Step 1:

(0.5 units, 1 person)

![image](https://user-images.githubusercontent.com/9417423/80601446-1e516180-8a2e-11ea-98a6-e8257eb6582d.png)

### Step 2:

(1 unit 2 persons)

![image](https://user-images.githubusercontent.com/9417423/80601564-4640c500-8a2e-11ea-9942-ba99bed35bc3.png)

### Step 3:

(2 units, 3 persons)

**Wrong: It should be 1.5 units**

![image](https://user-images.githubusercontent.com/9417423/80601726-78eabd80-8a2e-11ea-89f6-f7851a6d1866.png)

And so on. 

If you return to 1 again, the 0.5 dissapear, and keeps displaying 1 (it should be 0.5, like in "step 1" above.

![image](https://user-images.githubusercontent.com/9417423/80602050-eeef2480-8a2e-11ea-901f-3d9ba9afa329.png)

**Comment by vabene1111** [comment]
fixed in the next release, it was a rounding error which i didn't notice before, thanks for reporting
