### ISSUE TITLE
Add configuration hints for docker compose 

### ISSUE THREAD

**Issue by LeducH** [vabene1111/recipes#635]
**Is your feature request related to a problem? Please describe.**
I do not know what `edit it accordingly` means 

**Describe the solution you'd like**
All fields that need to be filled in should be mentioned and explained 

**Describe alternatives you've considered**
use an other project 

**Additional context**

https://docs.tandoor.dev/install/docker/

**Comment by vabene1111** [comment]
if you download the .env file you will see that each option in there is described (what it does and which options are supported).

There will likely be a separate page in the docs explaining in more detail what each option does but i haven't gotten around to doing this. If you have any special questions for any of the options just let me know and i will try to answer them
