### ISSUE TITLE
When importing a recipe, new tags are always created

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#645]
### Version
Version: 0.16.0

### Bug description
When importing a recipe, new tags are always created, even if the box `Import all keywords, not only the ones already existing` is unticked.

### How to reproduce:

- Import `https://www.allrecipes.com/recipe/284548/classic-chocolate-ice-cream-sandwich/`
- Three tags are found and will be created if not existent

**Comment by vabene1111** [comment]
thats probably something that was forgotten in the importer rework i guess we should add some tests for that as well

**Comment by Forceu** [comment]
The bug appears to be reintroduced in version 0.17.0

**Comment by vabene1111** [comment]
I don't remember changing anything there but I will take a look and probably also write a test for this..
