### ISSUE TITLE
Worker timeout when trying to save imported recipe

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#647]
### Version
Version: 0.16.0

### Bug description
When trying to import the recipe from `https://www.allrecipes.com/recipe/284548/classic-chocolate-ice-cream-sandwich/` and then saving the recipe, the worker times out and the saving fails. Below is the server output. Switching to debug did unfortunately not add any additional output. I was able to reproduce this problem multiple times.

> 0 None vegetable oil cooking spray
> 0.5 cup all-purpose flour
> 1 tablespoon all-purpose flour
> 0.25 teaspoon kosher salt
> 0.25 teaspoon baking soda
> 0.3333333333333333 cup sifted Dutch-process cocoa powder
> 3 tablespoons unsalted butter
> 0.25 cup white sugar
> 2 tablespoons light brown sugar
> 0.5 teaspoon pure vanilla extract
> 0.3333333333333333 cup whole milk
> 0.0 scoops vanilla ice cream
> [2021-06-03 17:17:07 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6)
> [2021-06-03 19:17:07 +0200] [6] [INFO] Worker exiting (pid: 6)
> [2021-06-03 17:17:07 +0000] [7] [INFO] Booting worker with pid: 7

**Comment by vabene1111** [comment]
very interesting, that does not seem that complex recipe.

I have just importet the same recipe into the demo and it worked without problems.

Can you try the import again, it might have been the website just not responding at that moment ..

**Comment by Forceu** [comment]
The timeout happens when _saving_ the recipe, after it had already been scrapped. I assume at that point there is no further communication with the origin URL? I can reliably reproduce the problem (still happening), so if there is a way to gather more logs for this case, let me know how

**Comment by vabene1111** [comment]
When saving the image is requests which might be a problem, other thatn that you are correct in that there is no further external connection. I was able to fully import on the demo db

Some questions that might help identify the issue
1. What platfform are you using, is there a CPU spike or something OS related that is unusual when importing
2. which database backend are you using 
3. Are you in a network that might be blocked by some websites (some websites for example block datacenter IPs for crawlers/media downloads)

**Comment by Forceu** [comment]
I am using Tandoor in a Podman container on a KVM running Ubuntu 20.04. There is no CPU spike during the timeout and I am using Postgres. The network is not blocked or filtered in any way.

Interestingly enough it is working now. 10 minutes ago I tried it and it was still timing out...

**Comment by vabene1111** [comment]
Interesting 🤔 most times issues like this witht the importer are related to network variations, maybe some cdn decedid you needed a break or whatever .. 

I will close this for now but if it happens again let me know
