### ISSUE TITLE
Sever error 500 when trying to merge ingredients

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#648]
### Version
Version: 0.16.0

### Bug description
When trying to merge two ingredients, a server error 500 appears. Unfortunately I could not gather further logs.

**Comment by vabene1111** [comment]
Interesting, i had a similar issue but i thought i fixed that in 0.16.0

Dont you know how to gather more logs or is your setup in such a way that you cant ?

if you use docker compose you can do `docker-comose logs -f` to see the logs

**Comment by Forceu** [comment]
I am not using docker compose, but when running the container with the `docker start -a`, it did not give me any output, even with debug on. Is there any other way to get more logs?

**Comment by vabene1111** [comment]
Hmm that is intereseing. Maybe there are no logs .. 

If you want and are comfortable with database you could send me a dump of the cookbook_foods table. if you dont want to post it publicly feel free to send it to info@tandoor.dev

**Comment by Forceu** [comment]
Thanks, I sent you an email with the DB dump :)

**Comment by quamok** [comment]
I'm also experiencing Error 500 when trying to remove a recipe from a book. I'm running Unraid, and the container logs don't show anything special.

**Comment by vabene1111** [comment]
please open a seperate issue for this as they are most likely not related to each other

**Comment by Forceu** [comment]
I was able to get the logs, this is the error:

```
ERROR:django.request:Internal Server Error: /edit/ingredient/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/recipes/cookbook/views/edit.py", line 295, in edit_ingredients
    old_unit.delete()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/base.py", line 953, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Unit' because they are referenced through protected foreign keys: 'Ingredient.unit'.", {<Ingredient: 1.0000000000000000 tablespoon all-purpose flour>, <Ingredient: 1.0000000000000000 tablespoon all-purpose flour>, <Ingredient: 1.0000000000000000 tablespoon all-purpose flour>, <Ingredient: 1.0000000000000000 tablespoon all-purpose flour>, <Ingredient: 1.0000000000000000 tablespoon all-purpose flour>, <Ingredient: 1.0000000000000000 tablespoon all-purpose flour>, <Ingredient: 1.0000000000000000 tablespoon finely grated Parmigiano-Reggiano cheese>, <Ingredient: 1.0000000000000000 tablespoon all-purpose flour>})
```

**Comment by vabene1111** [comment]
that is interesting, it should remove the old unit from all ingredients. Thanks for the log, i will look into it

**Comment by vabene1111** [comment]
ok so the issue was that the ingredient did no longer belong to any recipe (and with that not to any space). Since it was not part of any space it did not pass the tenant validation in the merging block so the unit was not removed/merged on the ingredient. Will be fixed in the next update

**Comment by Forceu** [comment]
Great to hear you found the problem! Maybe it would be a good idea to check after a recipe deletion if any units are not used in other recipes and delete them?

**Comment by vabene1111** [comment]
Yes and no... In this case it was actually the ingredient that caused the issue. Maybe ingredients should auto delete if detached but steps could exist on their own and maybe even be linked to multiple recipes. I will need to look into this.
