### ISSUE TITLE
Initial login

### ISSUE THREAD

**Issue by StayfrostySE** [vabene1111/recipes#65]
Hello world :)

I just want to give recipes a try but can't get 'compose' to work but... Pulling the container from hub.docker.com and then running it works without a hitch.

When I try to log in I have no credentials to supply. And since I haven't created a 'superuser' I have no idea what the default credentials are.

So my questions are...
Is there a 'default user' if I just run the container?
Do I have to run docker-compose?

Cheers from Sweden.

**Comment by vabene1111** [comment]
Hello Stayforsty. There is no default user. If you dont run it trough compose you can use the `docker exec` command to execute into the container (not sure of the exact syntax and it also depends on your setup). navigate to the root directory of the application (should be `/opt/recipes` and run `python3 manage.py createsuperuser`. Then just follow the steps. 

If you need any further assistance feel free to ask. Also feel free to open an issue describing your problems with docker compose as other people might struggle with the same things things. Maybe i can make it easier or improve on the documentation.

**Comment by vabene1111** [comment]
due to inactivity i will mark this as solved, if further assistance is needed feel free to reopen it.
