### ISSUE TITLE
Secret_Key warning although variable set

### ISSUE THREAD

**Issue by Tuphal** [vabene1111/recipes#650]
## Issue
I get the warning that my secret_key is not set, though it is set:
![grafik](https://user-images.githubusercontent.com/42291781/120786792-ecfb6d00-c52e-11eb-8f1f-998f36f5f1cb.png)

![grafik](https://user-images.githubusercontent.com/42291781/120786875-069cb480-c52f-11eb-9d88-c35cba871b26.png)

Does this secret needs to have a certain length?

## Setup Info
Version: 0.16.0
OS: Docker on Synology

Other relevant information regarding your problem (proxies, firewalls, etc.)

**Comment by vabene1111** [comment]
it just checks if if the environment variable exists `secret_key = False if os.getenv('SECRET_KEY') else True`

Does the rest of your configuration work (DB settings etc.) ?

**Comment by Tuphal** [comment]
I found the issue.
I had a space at the end of the env-variable :/

sorry for bothering

**Comment by vabene1111** [comment]
no worries, glad it worked and also good to know that it catches these types of issues
