### ISSUE TITLE
Constant Need to Re-Setup Superuser

### ISSUE THREAD

**Issue by Eschguy** [vabene1111/recipes#652]
### Bug description
After a server reboot, superuser needs to be set up again before gaining access.

**Comment by vabene1111** [comment]
that sounds like the database is reset every time but to help you with that i need at least some of the information that is asked for in the issue template.

**Comment by quamok** [comment]
by any chances are you using Unraid? Also, after setting up the superuser again, do you gain access to the data or the database is cleared?

**Comment by Eschguy** [comment]
After migrating over to my Proxmox box, the issue stopped. Sorry I can't follow up with any more.
