### ISSUE TITLE
[Bug] Cannot create shopping list from meal planner

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#662]
### Version
0.16.1, running in docker on port `7001`.

### Bug description
1. Create a meal plan, i.e. add some recipes to some days (URL: `host:7001/plan`)
2. Either:
    * Click on the Shopping cart of the specific days
    * or click on the added recipes and chose "add to shopping list" in the popup dialogue
3. The shopping list on the same page now lists the selected recipes
4. **Bug**: A click on "Open shopping list" leads to an empty shopping list ("no recipes selected", ingredients list empty) (URL: `host:7001/shopping/?r=[[object%20Object],4]&r=[[object%20Object],2]`)

Manually adding recipes (e.g. opening a recipe and adding it to the shopping list) works (URL: `host:7001/shopping/?r=[2,2]`).

Looks like the requests from the meal planner are currently malformed (`[object%20Object]` instead of the recipe ID)?

**Comment by vabene1111** [comment]
yes i think i already know what broke. Will get this fixed asap
