### ISSUE TITLE
Dedicated URL button to the original recipe

### ISSUE THREAD

**Issue by Wesleyl89** [vabene1111/recipes#668]
When you import a recipe from a website it will paste a 'Imported from https://....." on the bottom of the instructions. I love that I can always go to the original recipe, but to have a dedicated button to the URL would be even cleaner in my opinion.

**Comment by vabene1111** [comment]
Thanks for the feedback. Not entirely sure what i think about it but i will leave it open for now.

**Comment by philip-n** [comment]
*Related to https://github.com/vabene1111/recipes/issues/424 (store URL in separate field)*

**Comment by vabene1111** [comment]
good catch, there are so many great ideas in this repository that i constantly forget about some, thanks!

**Comment by MaxJa4** [comment]
Maybe it would help to use additional tags for the respective section of the system.
Like "Recipe Editing", "Recipe Import", "Recipe View",... so you can easily filter for it when working on a specific area :)

**Comment by vabene1111** [comment]
interesting idea 🤔 i usually just go trough them every now and then and close old duplicates. but i will keep this in mind :)

**Comment by MaxJa4** [comment]
I use Jira a lot at work with thousands of tickets (per project) :D it's very useful for keeping an overview with many tickets/issues.
