### ISSUE TITLE
[Minor] Allow to delete the image of a recipe

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#670]
**Is your feature request related to a problem? Please describe.**
When editing a recipe, there is the option to add a new image, but no way to delete the existing one.

**Describe the solution you'd like**
Some button / icon / ... that allows to remove the current image.

**Describe alternatives you've considered**
Uploading a blank image.

**Comment by vabene1111** [comment]
haha interesting .. i was always annoyed that android would not let you delete images from contacts and now i forgot it in my own application. 

Will implement something when reworking the edit view (the image upload in General need improvement)
