### ISSUE TITLE
[Minor] Tablet: Cannot access meal popup in meal planner 

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#671]
### Version
Version: 0.16.1

### Bug description
On an Android-Tablet with Chrome 90.0.4430.210, clicking on a planned meal does not open the popup. On PC and phone (latter with the same chrome version) it works fine.

*I don't think this really needs a fix, and I don't think it is even a problem of Tandoor; just wanted to leave this here as FYI.*

**Comment by vabene1111** [comment]
meal plan is currently being refactored, if this still happens in the new version please report again but is uses completely new function so should probably be fixed
