### ISSUE TITLE
Cannot combine two specific ingredients as desired (because one is referenced by a foreign key)

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#672]
### Version
Version: 0.16.1

### Bug description
Trying to combine two specific foods on the "unit and food" page results in an server error 500. Log see below, one of the foods seems to be referenced by a foreign key.

![Other_Error_500](https://user-images.githubusercontent.com/3903619/121237569-785e6080-c897-11eb-9ad5-4e719aabeb06.png)

Concrete case: Had `egg` and `egg(s)`
* Tried to combine into `egg(s)` --> server error.
* Tried to combine into `egg` (the one with the foreign key) --> success.

As a workaround, I combined into `egg` and then renamed it.

*Also, the error message could be more informative (similar to https://github.com/vabene1111/recipes/issues/669)*

```
ERROR:django.request:Internal Server Error: /edit/ingredient/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/recipes/cookbook/views/edit.py", line 311, in edit_ingredients
    old_food.delete()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/base.py", line 953, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Food' because they are referenced through protected foreign keys: 'Ingredient.food'.", {<Ingredient: 1.0000000000000000 None Ei>})
```

**Comment by vabene1111** [comment]
this should have been fixed in version 0.16.2 

let me know if that is not the case and thanks for reporting

**Comment by smilerz** [comment]
@philip-n - I'm refactoring how merges work right now - can you share enough specifics that I can create a test case to test for this condition?

**Comment by philip-n** [comment]
Well, I can certainly try.

The steps I took:
* Import some ~40 recipes
* For each recipe, try to name ingredients consistently right during import
* Create a shopping list, find that there's both `egg` and `egg(s)` listed
* Try to merge them, stumble upon the error above, create this issue

Unfortunately I cannot tell you the actual action that caused the error. As I now merged both (see original post), I'm afraid I do not have the original configuration at hand any more.

What more information can I provide?

**Comment by smilerz** [comment]
> What more information can I provide?
ideally it would be the minimum recipe(s) that could be created to create the condition.  thanks though!
@vabene1111 I'm assuming you ran into this - can you point me in the right direction?

**Comment by vabene1111** [comment]
The issue was related to an ingredient that was deperated from a recipe and thereby lost its space. I need to migrate that so that the space is saved on every ingredient. But again, the core issue should already be fixed in 0.16.2, just need to verify this

**Comment by philip-n** [comment]
Alright, thanks! Will try to verify at some point.

**Comment by smilerz** [comment]
> The issue was related to an ingredient that was deperated from a recipe and thereby lost its space. I need to migrate that so that the space is saved on every ingredient. But again, the core issue should already be fixed in 0.16.2, just need to verify this

so, not anything specific with the merge function on food?

**Comment by vabene1111** [comment]
no, it just currently needs to allow merging foods that do not belong to a space. I want to migrate that but haven't gotten around to it

**Comment by vabene1111** [comment]
closing for now, reopen if not fixed please
