### ISSUE TITLE
Implement a 5 stars rating system

### ISSUE THREAD

**Issue by quamok** [vabene1111/recipes#678]
**Is your feature request related to a problem? Please describe.**
It's not possible to quickly see if the recipe is rated high, medium or low.

**Describe the solution you'd like**
a 5 stars rating system, displayed just below the tags on the main page would be ideal to quickly see popular recipes. The rating could be applied when editing the recipe, or on the main page, or both.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by vabene1111** [comment]
there is actually already a rating system trough the "log cooking" functionality. The new search does not display it yet but i am working on that. The search will also hopefully one day be able to sort by and filter for ratings. 

Not the highest priority for me though as i tend to simply delete bad recipes 😂
