### ISSUE TITLE
Increase the max file upload size for Nginx

### ISSUE THREAD

**Issue by itsmegb** [vabene1111/recipes#679]
https://github.com/vabene1111/recipes/blob/f7d85bb4b8710fd4fb04c87bcb24bb1400d2cad7/nginx/conf.d/Recipes.conf#L5

When performing imports from other recipe applications, the exported data can be quite large if it includes many recipes and images.

Currently the max file size limit is only 16MB which is quite restrictive, can this be increased to accomodate for larger imports?

As an example, i've exported 124 recipes from Recettetek and that is currently 17.5MB.

**Comment by vabene1111** [comment]
you can change that by just opening your volume on your file system and changing the value. But you are completly right in that the default needs to be much larger.

**Comment by itsmegb** [comment]
Ah that would make sense.

I'm using one of the docker-compose examples from the docs and they mount the nginx conf.d volume into the nginx container as read only. Didn't even cross my mind when i was looking at it!

**Comment by vabene1111** [comment]
no worries, i dont really like the setup this way anyway but haven't had the time to improve it, glad the solution works for you for now.
