### ISSUE TITLE
Allow listing all recipes that use a certain ingredient or unit

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#681]
**Is your feature request related to a problem? Please describe.**
During import, one sometimes starts with one convention and later wants to switch to another one. E.g. you initially enter `lentils` as the ingredient and use the comment field for the color, then later decide that you'd rather have `red lentils` and `brown lentils` as different ingredients.

Now it would be great to be able to directly see which recipes already use `lentils`, in order to adapt them.

Same thing for incorrect units - at least one of my recipes seems to use `tomato` as unit, as I obviously missed this during import :innocent: 

**Describe the solution you'd like**
On the ingredients page, provide a list of all recipes that use this ingredient.

Optimally, offer a way to fix up units as well.

**Describe alternatives you've considered**
Manually iterating over all recipes. Not my favorite solution, though.

**Comment by vabene1111** [comment]
Can you try going to the search page and using the advanced search/ new search layout to filter for ingredients there ? 

IN the new layout (can be enabled via preferences) you can even specifiy if you want to search for recipes containing both or only a single ingredient. 

What currently cant be searched for is units but here you usually just know which ones are wrong and can use the merger to delete them.

Also @smilerz is working on a very cool rework for the keywords which will later be applied to units and foods as well. Here you will be able to see all recipes using a certain keyword (and later unit/food)

Please feel free to close this issue if it is resolved by this

**Comment by smilerz** [comment]
@vabene1111 beat me to commenting.

here is a preview of what the new pages will look like:
![image](https://user-images.githubusercontent.com/1808639/121393383-e6e20380-c915-11eb-86ec-4b9ea738ff7e.png)

**Comment by philip-n** [comment]
Thanks for the quick replies! I'm feeling kind of guilty for flooding you guys with issues for the last couple days, but am amazed by your awesome reaction times :clap: 

For the bug itself: The advanced search solves my current problem for the ingredients, thanks!

However, from a "new user" PoV, I think it would be more natural to navigate to the ingredient page and find a way to list the recipes there. As I understand @smilerz is working on this (?), I'll close here.

**Comment by vabene1111** [comment]
no worries, each issue is valid because if you need to ask how something works we did not do a good enough job explaining it trough the UIs. So you issues help us understand where improvements need to happen and what needs to be more clear.

You understood correctly that the ffeature is already wip so this issue can be closed
