### ISSUE TITLE
Email setup for Docker/unraid 

### ISSUE THREAD

**Issue by faspina** [vabene1111/recipes#683]
## Issue
Would like to take advantage of email, but can't find the email server settings 

## Setup Info
Version: latest docker 
OS: Unraid

Other relevant information regarding your problem (proxies, firewalls, etc.)

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
env content
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
docker-compose.yml content
```

### Logs
If you feel like there is anything interesting please post the output of `docker-compose logs` at
container startup and when the issue happens.

**Comment by vabene1111** [comment]
please take a look at https://github.com/vabene1111/recipes/blob/develop/.env.template there all options are documented. A dedicated docs page will follow hopefully soon. 

How you set those env vars depends on your setup but usually in some GUI on unraid i think and in the .env in other setups (i do not know if the unraid setup needs an update to support the new variables)

**Comment by faspina** [comment]
I added these to the docker setting in UNRAID .  Went to my user and added a email. Then hit the re-send verification, it said it went out but I did not see in the logs that it did anything and I never got the email. 

EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_HOST_USER= <gmail email>
EMAIL_HOST_PASSWORD=<gmail password>
EMAIL_USE_TLS=1
DEFAULT_FROM_EMAIL= < gmail email> 
ACCOUNT_EMAIL_SUBJECT_PREFIX= [Recipes]

**Comment by faspina** [comment]
Setting the email_ environment variables in the docker setting on unraid worked. I should have checked that, thank you!

**Comment by vabene1111** [comment]
no worries, glad it worked
