### ISSUE TITLE
Clear separation of scheduled / recently viewed recipes on front page

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#690]
**Is your feature request related to a problem? Please describe.**
When viewing the "front page" (a.k.a. search page), I expected to see a (paginated) list of all recipes, each shown once. However, some were shown multiple times on the same page, and some were shown on both first page and second page.

Some time later, I realized that additionally to listing all recipes, each page shows the recipes "scheduled for today" and "recently viewed" as very first recipes.

**Describe the solution you'd like**
Combination of the following:
a) update the UI so that it gets clear that the first recipes are shown for "special reasons"
b) make these sections collapsible and remember the setting per user
c) potentially: only show these on the first page (and not on page 2, 3, ... of the recipe list)

**Describe alternatives you've considered**
Move the "recently viewed" recipes to a different page altogether.

**Comment by vabene1111** [comment]
all of those features should be implemented in the new search 

1. there is a setting to enable recently viewed/ meal plan recipes in the search
2. there is a little footer on the card that shows why its showing
3. since the new search is an "inifite scroll" it should only show those recipes once

there are still some small issues with the system but it should work fine overall. Feel free to give it a try and let me know if you like it, you can enable the new search in the prefrences .

**Comment by philip-n** [comment]
Thanks! Then I'd like to split this issue in two parts.

**BUG**
I'm on v0.16.1, custom port 7001. 

The behaviour I see is:
* Search is paginated (no infinite scroll) for all three search modes (small, large, new)
* The checkbox "show recently viewed recipes" in the settings
  * does affect `small` and `large`
  * does not affect `new` - there are always 2 or 3 recipes shown with the "recently viewed" decorator, independent of the checkbox state

Now personally, I like the `recently viewed` feature, but I'd love to not have it in the search.

**Feature Request**
Create a new page for discovering recipes. This page shows multiple panels with cards of one topic (see https://www.netflix.com/de/browse/genre/839338 for what I'm trying to describe). In a certain way, all panels are search result views. Potential topics:
* recently viewed
* not logged for a long time
* logged most often
* highest star rating
* user-defined tag, recipes shown in random order (e.g. if I have a tag called `lunch`, I can create a panel that shows random recipes for `lunch`)
* user-defined ingredient, again in random order (gives me suggestions which of my 73 `potato` recipes I might cook, *without* having the one named `AAA mashed potatoes` always listed first and `ZZZ grilled potatoes` always a loong scroll away, and `MMM potato-whatever` always in the middle in scroll-over-land)
* recipes that are quick (total time under user-defined amount, e.g. under 30 min)
* ...

In a further step, there might be a settings page where users can define which panel they want to see and to configure them.

**Comment by vabene1111** [comment]
ok we need to pick this apart or i will never be able to do this

1. please update to 0.16.2 which fixes some issues (e.g. includes infinite scroll)
2. the setting in the preferences only effects the old search which is confusing but the new search has its how settings (which are stored locally to allow for example the search on your phone to be configured differently from your desktop).
3. The "special" views if we want to call them that are a good idea, some of them i also already had some are new. I will link it in the search rework issue and likely move it to a separate feature request at some point when i have time for it.
4. the new search still has a small bug with the recently viewed recipies things not returning the correct number of results, that will be fixed at some point (see #556)

**Comment by vabene1111** [comment]
closing for now, if you feel like i have missed something please open comment or open a new issue with just that specific problem .
