### ISSUE TITLE
Automatically delete food, units and amounts not associated with any recipes

### ISSUE THREAD

**Issue by quamok** [vabene1111/recipes#701]
**Is your feature request related to a problem? Please describe.**
After importing from another source (NC Cookbook in my case), sometimes the importer incorrectly imports incorrect data in the "units", "food" and "ingredients" fields, which is OK because you are not a magician (the importer works quite well). However, after a manual clean up of the recipes, a lot of ingredients and units aren't associated with any recipes anymore, which creates a lot of clutter when autocompleting (I now have 2800 ingredients, which is clearly wrong).

**Describe the solution you'd like**
when a food, unit or ingredient isn't associated anyone with any recipe, an option to activate an automatic deletion would make sense

**Describe alternatives you've considered**
manual clean up, but there's a risk of deleting still associated units and ingredients and mess up existing recipes.

**Additional context**
none

![IMG_20210610_214412](https://user-images.githubusercontent.com/24906799/121976156-39c21d80-cd51-11eb-9867-ecf1d9f55869.jpg)
![tandoor](https://user-images.githubusercontent.com/24906799/121976166-3cbd0e00-cd51-11eb-9b04-3515589e7dd1.png)

**Comment by vabene1111** [comment]
yes this needs to happen at some point (for me see also #642 )

**Comment by smilerz** [comment]
I hesitate to do any auto-deleting, especially as the food/keywords get reworked.  It will not be unusual to have empty foods as containers for other foods.

I'd suggest a management page to make finding/managing them easier.

**Comment by quamok** [comment]
Maybe them add a flag on the management page indicating that the ingredient is not linked to any recipe? That would make clean up much more efficient.

**Comment by vabene1111** [comment]
i think similerz is right. Once the pages have been reworked there will be some management buttons to quickly update/delete lots of foods. 

This will also include things like shopping list only ingredients or maybe even some more complex queries. 

i had planned to make a migration and just delete them but that no longer seems appropriate 

what i also want to implement is an "auto merge" feature where a unit is matched against existing units and if it fulfills some rules it will be merged automatically when importing or creating a recipe

**Comment by quamok** [comment]
Is there any way for users to know which ingredients aren't linked to any recipes? I've checked at the DB level, and I didn't see any link between recipes and ingredients (correct me if I'm wrong). A simple SQL query could then have been used to check ingredients with no associated recipes.

Otherwise, thank you for looking into this. I may have to resort to either a (hopefully non destructive) manual cleaning process, or just leave the bad ingredients there by fear of "breaking" the existing recipes.

**Comment by smilerz** [comment]
@quamok - I'd encourage you to use the existing 'merge' form on units and ingredients to clean up the unwanted items, that way you don't need to worry about whether or not there are associated recipes.  This functionality will be greatly improved in future versions.
![image](https://user-images.githubusercontent.com/1808639/122927281-57354f80-d32e-11eb-890a-7980eaef55b2.png)

**Comment by vabene1111** [comment]
ok so several things

1. Ingredients and recipes relate to each other trough two many to many relations. I will need to put an ER diagram somewhere but basically 1 Recipe can have many steps, each step can have many ingredients and each ingredient consists of food, unit, amount and note. It is planned to allow steps to exist in multiple recipes.
2. There is a page that lets you merge ingredients and units. you will have to do it one by one but that is bascially a safe delete (rewriting all references)

So bascially if you do not want to use the feature shown by @smilerz above you will have to write a query that joins foods and ingredients and check if no ingredient exists. There are no ingredients without recipes because a migration in 0.16.x deleted them all (on pourpuse)

**Comment by smilerz** [comment]
can be closed once #865 is merged

**Comment by vabene1111** [comment]
@smilerz thanks for the link, we should probably add a filter to the generic pages "not used anywhere" so people can easily delete those units/foods/keywords if they want
