### ISSUE TITLE
Error when trying to create new recipe

### ISSUE THREAD

**Issue by 0utl4w** [vabene1111/recipes#714]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.16.6

### Bug description
I want to create a new recipe. I insert a name and when I want to go on I get Error 500.
[error_log.txt](https://github.com/vabene1111/recipes/files/6680631/error_log.txt)

**Comment by vabene1111** [comment]
Ooops I forgot something with the last update, sorry for that. Fix is coming asap

**Comment by Kaibu** [comment]
Fixed with https://github.com/vabene1111/recipes/commit/7f57e7ab56ea0a71a2efe44b66328989f79cccba
