### ISSUE TITLE
Recipe picture from import is not saved anymore

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#717]
### Version
Version: 0.16.6

### Bug description
After upgrading from 0.16.2 to 0.16.6, pictures from an URL import are not saved anymore. They are displayed during the import, but once I click on save recipe, they are not shown on the main recipe anymore and need to be uploaded again.

**Comment by vabene1111** [comment]
oops i forgot a BytesIO Cast, fixed in the latest release (out in about one hour)
