### ISSUE TITLE
Suggestion: Meal Planning [Layout]

### ISSUE THREAD

**Issue by gehrleib** [vabene1111/recipes#72]
Perhaps it would look nicer if the dates were rows and the meal was in columns, i.e.

(blank) | Breakfast | Lunch | Dinner
------------ | ------------- | ------------- | -------------
Sunday, April 20 |  |  |  Meatloaf
Monday, April 21 | Eggs Benedict |  |  
Tuesday, April 22 |  |  |  
Wednesday, April 23 | Pancakes |  |  
Thursday, April 24 |  |  |  
Friday, April 25 |  |  |  Chicken Pot Pie
Saturday, April 26 |  |  |  

You could also lose the year? Maybe list it once above the table.

**Comment by vabene1111** [comment]
Thank you for your ideas, meal planning is very WIP, will take your ideas into account when further working on it

**Comment by therealschimmi** [comment]
How about some customisation options for the meal plan? I never plan ahead what to have for breakfast or dinner so I would like to have the option to switch off planing for those meals for better overview

**Comment by vabene1111** [comment]
yes that was also already discussed in some prior issue (that i might have closed since). I think i am slowly getting a feel of what people want from the meal planning feature so i might soon be able to really work on it.

**Comment by vabene1111** [comment]
merged issue into #84
