### ISSUE TITLE
offical mariadb support

### ISSUE THREAD

**Issue by BobWs** [vabene1111/recipes#73]
Hi,
Any chance you will support Mariadb (MySQL databases)? Most of my docker image I’m using Mariadb I find it a better database then Postgres. (Personal opinion)

**Comment by vabene1111** [comment]
the application should support any database that django supports to in theory it should also work with maria db. I think you will need `mysqlclient` as an additional dependency so you might have to build the image yourself, apart from that its only a config change. 

You will however loose support for the trigram similarity search which is only available for postgres. Maybe i could add support for mysql out of the box, possibly with an image build version that also has mysql client installed, apart from that it should only be the database driver that would need to be read from an environment variable in the settings

**Comment by vabene1111** [comment]
Please see here for basic instructions on how to use maria DB https://github.com/vabene1111/recipes/discussions/246

Due to my limited time i cannot at the moment officially support mysql (as that would mean that i need to test it as well) but it should work
