### ISSUE TITLE
Weblate registration not possible

### ISSUE THREAD

**Issue by MaxJa4** [vabene1111/recipes#730]
I tried to register for the Tandoor Weblate.
I got the confirmation mail and it prompted me to enter my desired password.
When confirming, a 502 Bad Gateway error occurred.
Resetting the password doesn't work either.

I still get the "your password has been changed" mails from it but I can't use it to login ("Wrong password").

**Comment by vabene1111** [comment]
thanks for letting me know, i will take a look tomorrow, maybe something broke when i changed mail servers and updated the instance 🤔

**Comment by vabene1111** [comment]
ok seems to have been an issue in the version or during update, restarting and updating fixed it. If you need any help feel free to let me know and thanks for contributing

**Comment by MaxJa4** [comment]
Thanks! It's working now and I translated most of the new space and resource stuff.

**Comment by vabene1111** [comment]
awesome, thank you very much 👍
