### ISSUE TITLE
Cannot create new recipe

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#733]
### Version
Version: 0.16.6

### Bug description
1. Cookbook > New recipe
2. Enter arbitrary title, press the "save" button
3. Error 500

![Bildschirmfoto von 2021-06-24 22-16-06](https://user-images.githubusercontent.com/3903619/123334973-1dd62d00-d544-11eb-91b0-7afb6b52d62f.png)

I think this worked fine with the 0.16.2, but am not sure if I had added a recipe using this route at all (maybe I only imported recipes from the web).

I can still import from the web, so I assume it's not a problem with my setup.

There is no error in the logs, just the call itself:

```
172.20.0.4 - - [24/Jun/2021:22:16:04 +0200] "POST /new/recipe/ HTTP/1.0" 500 145 "https://subdomain.myurl.xy/new/recipe/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

**Comment by philip-n** [comment]
Ah, just saw that 0.16.7 already contains a fix. Should have checked earlier...

**Comment by vabene1111** [comment]
no worries, thanks for reporting 👍
