### ISSUE TITLE
Introduce a "draft"-flag for recipes (true on new recipes, toggleable by user)

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#735]
**Is your feature request related to a problem? Please describe.**
**A** Importing a recipe can take some minutes (check that the ingredient match, split into steps, maybe translate from other language). If I'm interrupted in the process, I have to remember which recipe I need to finish.

**B** For some technical reason, creating a recipe goes wrong and the recipe is created internally, but cannot edited by the user (that's what happened to me in https://github.com/vabene1111/recipes/issues/733 - each attempt to create a recipe resulted in a 500 server error, *but* created an empty recipe with the title I had chosen in the database).

**Describe the solution you'd like**
Introduce a draft / WiP flag. Always enable the flag on creation of a new recipe. Near the "save" button, offer a checkbox that allows the user to manually toggle the flag.

Additionally, offer some overview of all recipes in "draft" status.

**Describe alternatives you've considered**
Manually checking the latest recipes via the admin panel. Then searching for the according names in order to edit (or in my case: delete) them.

**Comment by vabene1111** [comment]
thanks for the idea.

Have you considered using a Keyword for this ? It would help for use case A and use case B should definitely not happen so it does not really need a fix (other than better testing).

Also the new search shows recently created recipes first

**Comment by vabene1111** [comment]
so i think keywords do the job just fine, closing this for the lack of an answer
