### ISSUE TITLE
Please dont hard code container names

### ISSUE THREAD

**Issue by timdonovanuk** [vabene1111/recipes#736]
`django.db.utils.OperationalError: could not translate host name "db_recipes" to address: Name does not resolve`

Looking for the database on localhost:port should suffice surely.

My understanding this project is really called tandoor, and I like to keep my docker container names descriptive (db_recipes renamed to tandoor_db). Please allow this flexibility if possible.

**Comment by vabene1111** [comment]
simply change the environment variable `POSTGRES_HOST` to whatever you named the container. Same goes for the nginx configuration file where `web_recipes `points to the application container :) 

If you need any additional help let me know.
