### ISSUE TITLE
Import -> File & Text aren't links

### ISSUE THREAD

**Issue by timdonovanuk** [vabene1111/recipes#738]
### Version
Version:  Current Version: 0.16.7

### Bug description
I saw that "Tandoor allows you to import PDF and image files from local storage" but these two options are not available to click:

![image](https://user-images.githubusercontent.com/8156439/123545017-f0f56600-d74d-11eb-901d-aa062ac771fe.png)

Just checking if it's not in the release yet?

Many thanks :)

**Comment by vabene1111** [comment]
these two options are meant for future text and file based imports with OCR and all that fancy stuff but they are not yet implemented thus they are greyed out for the moment. We could remove the links all togerther, that would propably be more straight forward ...
