### ISSUE TITLE
web user setup 

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#74]
https://www.reddit.com/r/selfhosted/comments/gr815y/comment/fs3ifoa

Add a first time setup online thingy so people without terminal access can create userers

**Comment by koch17** [comment]
Hi,
I am the guy from reddit. I just saw you have released version 0.8 and installed it, but when I open the page, it is exactly the same as it was before with only log in and no sign up, am I missing something?

**Comment by vabene1111** [comment]
oh i forgot to implement the automatic redirect, sry, i will add that with the next update. 
Right now you can go to yourdomain.com/setup to open the setup page manually. 

Feedback would be very welcome :)

**Comment by koch17** [comment]
It went smooth, was able to create a user. There is just one problem, there is no add a new recipe button anywhere, through trial and error I was able to find that domain/new/recipe leads to the page to create a new recipe and I was able to add few recipes. Could you add this button with the next update?

**Comment by vabene1111** [comment]
there is one but i have to admit that it might not be placed very intuitively. It is located on the three dots button next to the search. 

EDIT: Apparently the button is broken along with the tooltips #89  due to some javascript error  most likley introduced by #75. Will be fixed in the next few hours, sry for the inconvenience, it is not typical that so many mistakes happen in such a short time :/

**Comment by koch17** [comment]
Considering how young the project is and how it got some more attention recently with so many opened issues, you are doing a great job, so no need to apologize.

**Comment by vabene1111** [comment]
thank you very much. The fixed version was just released, it will take about an hour for the build script to release all build flavors (due to libxml building quite slowly), then everything should work. 

Make sure to read the instructions in the releases as a PR in march introduced an error which needs some manual attention to properly fix.
