### ISSUE TITLE
gunicorn fails to start during manual install

### ISSUE THREAD

**Issue by Cromagnonaut** [vabene1111/recipes#741]
## Issue
I tried to install recipes on a Debian container during the past week, tried several fresh installs, but I am always stuck at the same error. Google wasn't much help, because I do not really know what to search for... First experience with Django/Python, so I do not really know what I'm doing, but I am eager to learn (sorry...). I also tried to start it in a venv and normally, but no luck.

Gunicorn fails to start while starting manually. While doing a manual install I get
```
AttributeError: module 'bind' has no attribute 'application'
```
after starting gunicorn manually for testing. Before this I got
```
ModuleNotFoundError: No module named 'bind'
```
which I solved by simply installing it via apt (not sure if this is the right way)

Full log from starting gunicorn:
```
gunicorn bind unix:/home/tandoor/python-enviroments/tandoor/recipes/recipes.sock recipes.wsgi:application
[2021-06-29 19:12:50 +0200] [30794] [INFO] Starting gunicorn 20.1.0
[2021-06-29 19:12:50 +0200] [30794] [INFO] Listening at: http://127.0.0.1:8000 (30794)
[2021-06-29 19:12:50 +0200] [30794] [INFO] Using worker: sync
[2021-06-29 19:12:50 +0200] [30795] [INFO] Booting worker with pid: 30795
[2021-06-29 19:12:50 +0200] [30795] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/tandoor/python-environments/tandoor/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/tandoor/python-environments/tandoor/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/tandoor/python-environments/tandoor/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/tandoor/python-environments/tandoor/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/tandoor/python-environments/tandoor/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/tandoor/python-environments/tandoor/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/tandoor/python-environments/tandoor/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bind'
[2021-06-29 19:12:50 +0200] [30795] [INFO] Worker exiting (pid: 30795)
[2021-06-29 19:12:50 +0200] [30794] [INFO] Shutting down: Master
[2021-06-29 19:12:50 +0200] [30794] [INFO] Reason: Worker failed to boot.

```

## Setup Info
Version: (can be found on the system page since v0.8.4)
OS: Debian 10 Buster

### `.env`
```                                                                                                                                  
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=1

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=

# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=Europe/Berlin

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=password
POSTGRES_DB=djangodb

# database connection string, when used overrides other database settings.
# format might vary depending on backend
# DATABASE_URL = engine://username:password@host:port/dbname

# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# Default for user setting sticky navbar
# STICKY_NAV_PREF_DEFAULT=1

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# S3 Media settings: store mediafiles in s3 or any compatible storage backend (e.g. minio)
# as long as S3_ACCESS_KEY is not set S3 features are disabled
# S3_ACCESS_KEY=
# S3_SECRET_ACCESS_KEY=
# S3_BUCKET_NAME=
# S3_REGION_NAME= # default none, set your region might be required
# S3_QUERYSTRING_AUTH=1 # default true, set to 0 to serve media from a public bucket without signed urls
# S3_QUERYSTRING_EXPIRE=3600 # number of seconds querystring are valid for
# S3_ENDPOINT_URL= # when using a custom endpoint like minio

# Email Settings, see https://docs.djangoproject.com/en/3.2/ref/settings/#email-host
# Required for email confirmation and password reset (automatically activates if host is set)
# EMAIL_HOST=
# EMAIL_PORT=
# EMAIL_HOST_USER=
# EMAIL_HOST_PASSWORD=
# EMAIL_USE_TLS=0
# EMAIL_USE_SSL=0
# DEFAULT_FROM_EMAIL= # email sender address (default 'webmaster@localhost')
# ACCOUNT_EMAIL_SUBJECT_PREFIX= # prefix used for account related emails (default "[Tandoor Recipes] ")

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0

# Default settings for spaces, apply per space and can be changed in the admin view
# SPACE_DEFAULT_MAX_RECIPES=0 # 0=unlimited recipes
# SPACE_DEFAULT_MAX_USERS=0 # 0=unlimited users per space
# SPACE_DEFAULT_MAX_FILES=0 # Maximum file storage for space in MB. 0 for unlimited, -1 to disable file upload.
# SPACE_DEFAULT_ALLOW_SHARING=1 # Allow users to share recipes with public links


```

**Comment by vabene1111** [comment]
First of all dont worry for asking. The manual install is used rarely and there might be shortcomings in the docs or i might have broken something at some point and did not notice because i do not maintain a manual install. Even if its your fault then analyzing it might help us improve the documentation so everyone always wins :)

May i ask did you already solve this issue by running the apt-install and this ticket here is just so i can update the docs or do you still have an issue with the manual install, i do not 100% understand that from your issue ?

If you still have an issue could you please show me the rought directory structure and the gunicorn start command (do you run it as a service, if so please provide me with the service config) ?

You can also try, just for debugging, to run `python manage.py runserver` from the application root directory to see if djangos development server works. It will ignore all your environment variables but you will know if you have installed all required packages appropriatly

**Comment by Cromagnonaut** [comment]
Thank you for your prompt and kind answer! I am very happy to help!

> May i ask did you already solve this issue by running the apt-install and this ticket here is just so i can update the docs or do >you still have an issue with the manual install, i do not 100% understand that from your issue ?

Unfortunately, this did not solve my issue. But it fixed the `ModuleNotFoundError: No module named 'bind'` error.

Today I tried setup a new, fresh venv, and I have a feeling that I might have fixed a few things (not sure how tho, but I think it was related to mixed up python versions...).

The django development server is working now.

```
python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 01, 2021 - 08:43:05
Django version 3.2.4, using settings 'recipes.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
contents of my application root-folder:
```
total 159
drwxr-xr-x 12 tandoor tandoor    29 Jul  1 08:42 .
drwxr-xr-x  7 tandoor tandoor     7 Jul  1 08:38 ..
-rw-r--r--  1 tandoor tandoor   169 Jul  1 08:38 .dockerignore
-rw-r--r--  1 tandoor tandoor  5616 Jul  1 08:40 .env
-rw-r--r--  1 tandoor tandoor  5161 Jul  1 08:38 .env.template
drwxr-xr-x  8 tandoor tandoor    13 Jul  1 08:38 .git
drwxr-xr-x  4 tandoor tandoor     5 Jul  1 08:38 .github
-rw-r--r--  1 tandoor tandoor   940 Jul  1 08:38 .gitignore
drwxr-xr-x  5 tandoor tandoor     8 Jul  1 08:38 .idea
-rw-r--r--  1 tandoor tandoor  1049 Jul  1 08:38 .pre-commit-config.yaml
-rw-r--r--  1 tandoor tandoor  2246 Jul  1 08:38 CONTRIBUTERS.md
-rw-r--r--  1 tandoor tandoor   840 Jul  1 08:38 Dockerfile
-rw-r--r--  1 tandoor tandoor 36742 Jul  1 08:38 LICENSE.md
-rw-r--r--  1 tandoor tandoor  4534 Jul  1 08:38 README.md
-rw-r--r--  1 tandoor tandoor   517 Jul  1 08:38 SECURITY.md
-rw-r--r--  1 tandoor tandoor   309 Jul  1 08:38 boot.sh
drwxr-xr-x 14 tandoor tandoor    23 Jul  1 08:40 cookbook
drwxr-xr-x  6 tandoor tandoor    13 Jul  1 08:38 docs
-rw-r--r--  1 tandoor tandoor   184 Jul  1 08:38 makemessages.cmd
-rwxr-xr-x  1 tandoor tandoor   539 Jul  1 08:38 manage.py
-rw-r--r--  1 tandoor tandoor  1169 Jul  1 08:38 mkdocs.yml
drwxr-xr-x  3 tandoor tandoor     3 Jul  1 08:38 nginx
drwxr-xr-x  3 tandoor tandoor     4 Jul  1 08:38 node_modules
-rw-r--r--  1 tandoor tandoor    95 Jul  1 08:38 pytest.ini
drwxr-xr-x  4 tandoor tandoor    10 Jul  1 08:40 recipes
-rw-r--r--  1 tandoor tandoor   869 Jul  1 08:38 requirements.txt
drwxr-xr-x 20 tandoor tandoor    21 Jul  1 08:42 staticfiles
drwxr-xr-x  3 tandoor tandoor    11 Jul  1 08:38 vue

```


I tried to setup gunicorn as as service last week, but because it was not working, and `systemctl` is hard to debug for me, I tried to start it manually (start command after the service config file).

```
[Unit]
Description=gunicorn daemon for recipes
After=network.target

[Service]
Type=simple
Restart=on-failure
RestartSec=3
Group=www-data
WorkingDirectory=/home/tandoor/python-environments/tandoor/recipes
EnvironmentFile=/home/tandoor/python-enviroments/tandoor/recipes/.env
ExecStart=/home/tandoor/python-enviroments/tandoor/recipes/bin/gunicorn --error-logfile /tmp/gunicorn_err.log --log-$


[Install]
WantedBy=multi-user.target
```
Manual start command I tried for gunicorn (from application root folder within an venv):
```gunicorn --error-logfile /tmp/gunicorn_err.log --log-level debug --capture-output --bind unix://home/tandoor/python-environments/tandoor/recipes/recipes.sock recipes.wsgi:application```

Contents of the `/tmp/gunicorn_err.log`
```
[2021-07-01 08:50:30 +0200] [6848] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['unix://home/tandoor/python-environments/tandoor/recipes/recipes.sock']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/tandoor/python-environments/tandoor/recipes
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /tmp/gunicorn_err.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: recipes.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f5917ec91f0>
  on_reload: <function OnReload.on_reload at 0x7f5917ec9310>
  when_ready: <function WhenReady.when_ready at 0x7f5917ec9430>
  pre_fork: <function Prefork.pre_fork at 0x7f5917ec9550>
  post_fork: <function Postfork.post_fork at 0x7f5917ec9670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f5917ec9790>
  worker_int: <function WorkerInt.worker_int at 0x7f5917ec98b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f5917ec99d0>
  pre_exec: <function PreExec.pre_exec at 0x7f5917ec9af0>
  pre_request: <function PreRequest.pre_request at 0x7f5917ec9c10>
  post_request: <function PostRequest.post_request at 0x7f5917ec9ca0>
  child_exit: <function ChildExit.child_exit at 0x7f5917ec9dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f5917ec9ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f5917ed9040>
  on_exit: <function OnExit.on_exit at 0x7f5917ed9160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2021-07-01 08:50:30 +0200] [6848] [INFO] Starting gunicorn 20.1.0
[2021-07-01 08:50:30 +0200] [6848] [DEBUG] connection to home/tandoor/python-environments/tandoor/recipes/recipes.sock failed: [Errno 2] No such file or directory
[2021-07-01 08:50:30 +0200] [6848] [ERROR] Retrying in 1 second.
[2021-07-01 08:50:31 +0200] [6848] [DEBUG] connection to home/tandoor/python-environments/tandoor/recipes/recipes.sock failed: [Errno 2] No such file or directory
[2021-07-01 08:50:31 +0200] [6848] [ERROR] Retrying in 1 second.
[2021-07-01 08:50:32 +0200] [6848] [DEBUG] connection to home/tandoor/python-environments/tandoor/recipes/recipes.sock failed: [Errno 2] No such file or directory
[2021-07-01 08:50:32 +0200] [6848] [ERROR] Retrying in 1 second.
[2021-07-01 08:50:33 +0200] [6848] [DEBUG] connection to home/tandoor/python-environments/tandoor/recipes/recipes.sock failed: [Errno 2] No such file or directory
[2021-07-01 08:50:33 +0200] [6848] [ERROR] Retrying in 1 second.
[2021-07-01 08:50:34 +0200] [6848] [DEBUG] connection to home/tandoor/python-environments/tandoor/recipes/recipes.sock failed: [Errno 2] No such file or directory
[2021-07-01 08:50:34 +0200] [6848] [ERROR] Retrying in 1 second.
[2021-07-01 08:50:35 +0200] [6848] [ERROR] Can't connect to home/tandoor/python-environments/tandoor/recipes/recipes.sock
```

**Comment by vabene1111** [comment]
Ok i have serval ideas/notes

1. debugging systemctl works with `journalctl`, if you want to filter and have live output use `journalctl -f | grep gunicorn` or maybe instead of gunicorn your service name
2. I think the venv is no toaded in the service and i honestly dont know how to do that
3. your bind looks like this `--bind unix://home/tandoor/python-environments/tandoor/recipes/recipes.sock` but the example looks like this `--bind unix:/media/data/recipes/recipes.sock`. the `//` is likely the source of your problem

**Comment by Cromagnonaut** [comment]
Sorry for the delay...
Your tips were very helpful. Debugging with `journalctl` helped a great deal. So, the good news first: I got the web interface working! As soon as I read your post, I saw the typo. Not only the `\\` caused the error. Half awake, I named the containing folder `python-environments`, and in all of the config files `python-enviroments`...

Starting gunicorn manually works now, but not with `systemd`. Now I get "permission denied" for the working directory. I have already tried with another user/group ind the gunicorn.service config, but no luck so far. My guess is the venv, as you stated...
I will try to do a fresh install in another container without a venv next.

I think my next hurdle will be the connection to a remote nginx proxy., as I have one central reverse proxy for my services. Do you got any resources or tips on that?

The `journalctl` error log:
```
Jul 06 18:48:28 lxc-tandoor systemd[1]: gunicorn_recipes.service: Service RestartSec=3s expired, scheduling restart.
Jul 06 18:48:28 lxc-tandoor systemd[1]: gunicorn_recipes.service: Scheduled restart job, restart counter is at 29035.
Jul 06 18:48:28 lxc-tandoor systemd[1]: Stopped gunicorn daemon for recipes.
Jul 06 18:48:28 lxc-tandoor systemd[1]: Started gunicorn daemon for recipes.
Jul 06 18:48:28 lxc-tandoor systemd[1740]: gunicorn_recipes.service: Failed to execute command: Permission denied
Jul 06 18:48:28 lxc-tandoor systemd[1740]: gunicorn_recipes.service: Failed at step EXEC spawning /home/tandoor/python-environments/tandoor/recipes: Permission denied
Jul 06 18:48:28 lxc-tandoor systemd[1]: gunicorn_recipes.service: Main process exited, code=exited, status=203/EXEC
Jul 06 18:48:28 lxc-tandoor systemd[1]: gunicorn_recipes.service: Failed with result 'exit-code'.
```

**Comment by vabene1111** [comment]
ok so i have the following ideas (although i am a bit rusty with manual setups)

- create/run the systemd service as the same user used to setup the folder/python environement etc.
- remember to add the environment file to the gunicorn service file
- remember to load the environment and activate the venv (probably in reversed order) whenenver runing migrations etc.
- for the reverse proxy you can either simply bind to the port which should be straight forward even from a remote machine (if you change gunicorn to expose a port instead of a socket) or bind to that socket which is also not to hard but works only with the proxy on the same machine `server unix:/your/path/gunicorn.sock `

**Comment by Cromagnonaut** [comment]
Okay, so now I got nearly everything working. I spun up a new Debian container and did everything from scratch. With your tips in mind and bit of searching, everything worked like a charm first try. For anyone having trouble with the manual setup: because I tried to setup the application without a `venv` first, which didn't work, two different gunicorn versions got mixed up. `which gunicorn` pointed to `...\.local\bin\gunicorn`. This path could not be used to start the application. Setting everything up in a virtual environment without a local version of the dependencies did the trick.
I also have now configured the `systemd` service and can now expose a port or socket and open the webinterface in my browser via the ip, exposed via nginx (on the same machine). I will post all relevant config files, when everything is working for future readers.

However, the issue with a centralized nginx reverse proxy is still open. My goal is to have the nginx reverse proxy with the ssl certficates in one container with the ip 127.0.0.1 and recipes on 127.0.0.2 for example. The config for the remote nginx currently looks like this, which is obviously wrong, and states a `502` error.
```
server {
 2     listen 8002;
 3     #access_log /var/log/nginx/access.log;
 4     #error_log /var/log/nginx/error.log;
 5
 6     # serve media files
 7     location /static {
 8         alias /home/tandoor/pyenvs/tandoor/recipes/staticfiles;
 9     }
10
11     location /media {
12         alias /home/tandoor/pyenvs/tandoor/recipes/mediafiles;
13     }
14
15     location / {
16         proxy_pass http://192.168.55.206:8000;
17     }
18 }
19
```
This bit confuses me. 
```
 6     # serve media files
 7     location /static {
 8         alias /home/tandoor/pyenvs/tandoor/recipes/staticfiles;
 9     }
10
11     location /media {
12         alias /home/tandoor/pyenvs/tandoor/recipes/mediafiles;
13     }
``` 
Since these files are on `127.0.0.2`, Nginx  cannot access them. Can i pass these files to the remote machine, or how should this be done?
I now this can be done, but again I really don't know what to search for... 
This post helped a great deal: [https://stackoverflow.com/questions/53904055/forwarding-nginx-port-to-gunicorn-instance](url)

Thanks again for your help and patience with a bloody beginner ;)

**Comment by vabene1111** [comment]
ok so sorry for the late answer.

Since nginx really does not impose much overhead i strongly recommend running an nginx service on the same machine as your gunicorn service with all files locally present. This will bundle everything it gets from gunicorn together with media and static files and expose one single ip which the remote nginx service can than forward to.

if everything is done in a private network you could even terminate your ssl at the ingress nginx server and then run the backend nginx as http only. If you do this make sure to forward all http headers from the ingress nginx to the application nodes as otherwise many things break

**Comment by Cromagnonaut** [comment]
Okay, got you. I had a feeling that two nginx instances on different machines is the correct way but it felt weird somehow, so I tried it this morning anyway. Now I got a 502! :) 
Can't figure out why it does not connect to the machine.

The nginx config on my local machine looks like this now. I suppose this is what you meant by exosing a single ip?
```
server {
    listen 8002;
    #access_log /var/log/nginx/access.log;
    #error_log /var/log/nginx/error.log;

    # serve media files
    location /static {
        alias /home/tandoor/pyenvs/tandoor/recipes/staticfiles;
    }

    location /media {
        alias /home/tandoor/pyenvs/tandoor/recipes/mediafiles;
    }

    location / {
        proxy_pass http://192.168.55.206:8000;
    }
}
```
And the config on the remote reverse proxy (added ssl already, but it doesn't matter):
```
server {

        listen 80;

        listen 443 ssl;
        ssl_certificate "/etc/letsencrypt/live/example.domain.com/fullchain.pem";
        ssl_certificate_key "/etc/letsencrypt/live/example.domain.com/privkey.pem";

        server_name example.domain.com;


        location / {

                proxy_pass http://192.168.55.206:8002;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }

}


# Redirect all HTTP requests to HTTPS
server {
    if ($host = example.domain.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
        listen [::]:80;

    server_name example.domain.com;
    return 404;
}
```

**Comment by vabene1111** [comment]
can you try using the following on your local nginx instance ? I am not sure if routing trough the external ip of the machine works or not.

```
location / {
        proxy_pass http://127.0.0.1:8000;
    }
```
If this does not help can you verify where the error occurs by visiting the ips one by one ? First gunicorn, then the local nginx than the remote ?

**Comment by Cromagnonaut** [comment]
Ok, late response again, but I wanted to test everything thoroughly beforehand. Good news, I got everything working now! 

It was, again, my own fault. I tried to verfify where the communication between the hosts stops and when I discovered that my domain for tandoor pointed to another webservice I had set up, it dawned on me. Dumb as I am, I forgot to create the symbolic link to enable the site in my remote nginx instance. So the 502 error was actually caused by the other webservice, which a backend was offline at the time...
After creating, the page was working internally and externally. But the pictures where gone. Tried to add the headers, and setting the `MEDIA_URL=https://example.com/media/` but no luck. But @auanasgheps mentioned in #452 that nginx should point directly to the tandoor web container not nginx, which did the trick! Now it is, strangely, working like a charm without setting the headers and setting the MEDIA_URL. But I don't quite understand how, I always thought the local nginx sits in front of everything. Maybe someone can explain that to me?

Anyway, this was great learning experience and I would like to thank you very much for investing your time to help me! Is it possible to give something back? I tried to look into translating, but https://translate.tandoor.dev/ seems to be offline...
Another idea was to write a short guide like the documentation, but with added comments for possible pitfalls for beginners like myself....

**Comment by vabene1111** [comment]
So first of all you are already giving a lot back by simply being friendly and liking this project. I have been very lucky the last few years to have kind and helpful people like you using this application and this has really motivated me to keep working on it. 

Secondly i got the translation system back up and running, it seems to be a little to much for the small vps its running on but it will need to do for now 😂 

There will also be a github sponsors in a few weeks but that again will be entirely optional. 

Thanks for staying friendly and respectful and whenever you have another questions feel free to ask!

P.S.: regarding the media files, i guess there was some directory not mounted correctly or nginx config path not correct as the local nginx server with the appropriate routes should be able to serve all files. if this ever breaks in the future let me know and i will see if i can help
