### ISSUE TITLE
Privacy: Remove remote Google fonts, jquery, assets

### ISSUE THREAD

**Issue by snogrammer** [vabene1111/recipes#75]
Thank you for the opensource development and easy-to-use selfhosted app! 

One thing that jumped out as soon as I got the app set up was that it is using remote Google fonts that include trackers which jumps out as a security and privacy concern. The fonts can be downloaded and used as local assets. Google is a major reason that many people selfhost things to avoid being tracked/spied on.

Jquery also seems to be hosted from Cloudflare.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/13201143/83357950-fdca3f00-a32c-11ea-83cc-b2db30451a3c.png">

**Comment by vabene1111** [comment]
hmm i am a very privacy focused person myself so this should definitly be fixed .. since this website is meant for small deployments anyway it should not have any performance implications so no reason to not include it in the static assets.

**Comment by vabene1111** [comment]
ok so i have just pushed some commits (7b17a1acfa4ccf43682c27cf0804202f0992916e and 6aedba09f3e8b36f67bbceaf05617dbae06d26e4) to remove all external CDN dependencies. What i could not find was a dependency on google fonts. I remember playing around with fonts a while ago but i think i removed it. I also installed privacy badger to test it and could not find a page that loads google fonts.

Can you specify on what page you were on when you saw the google fonts warning ? Also if you want you can use the `recipes:develop` image to test the latest development build if you want.

**Comment by snogrammer** [comment]
Thank you for looking into that! I was creating a new recipe when I noticed privacy badger notifications. I'll try to test it out tomorrow.

**Comment by vabene1111** [comment]
closing this for now, if any new problems arise feel free to open a new issue
