### ISSUE TITLE
recipe cannot be added to cookbook

### ISSUE THREAD

**Issue by DFS-90** [vabene1111/recipes#765]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.16.7

### Bug description
Adding a recipe to an existing cookbook is impossible as no cookbook can be found.
The window asking for the cookbook says "list is empty".

<img width="415" alt="Error cookbook" src="https://user-images.githubusercontent.com/87578070/126043185-d71e2952-c2f9-4d3e-ac8b-53413a9099c3.png">

**Comment by vabene1111** [comment]
on my instances adding to an existing cookbook works so i cant reproduce your issue. 

Can you open the browser development tools (on chrome its F12) or rickt klick inspect element. There should be a tab named console and there might be some errors.

You can also set the environment variable DEBUG=1 for the server application and post the logs that are shown when running `docker-compose logs -f`

**Comment by charlesoblack** [comment]
This sounds like a case of not having created a cookbook in the first place to me. Under "Utensils > Books" you can create a new book, and then add recipes to said book.

**Comment by vabene1111** [comment]
i thought so too but he said "to an existing" so maybe there is some kind of issue 🤔 but yea, please verify you have a cookbook

**Comment by smilerz** [comment]
> i thought so too but he said "to an existing" so maybe there is some kind of issue 🤔 but yea, please verify you have a cookbook

If this is really the case - should add a feature request to create a book from this view.  Same for shopping list.

**Comment by vabene1111** [comment]
yes this should definitely be added .. this comes from the old django multiselect times but now that it is a proper vue component adding tagging support should be quite easy.

**Comment by venohm69** [comment]
I'm having this same issue with a manual install using mysql and apache2 proxy.
I have created a book called test successfully and I can see it under Utensils -> Books.
But, when I view a recipe and select Add to Book, I get the list is empty.
I have not seen any errors in the browser console (Firefox) nor have I seen any errors in the tandoor log with debug level enabled.

**Comment by DFS-90** [comment]
Sorry for my late response.
My cookbook was created first; in fact, I also got that error with a manual install.
I "solved" the problem by using the Docker method...

**Comment by vabene1111** [comment]
that is very interesting 🤔 there should not be any difference in the behavior of this particular function depending on the installation method. 

I will try to somehow reproduce this issue, if i cant i might ask additional questions

**Comment by venohm69** [comment]
I used Ansible to do the build on a base install of Debian.  I'd be happy to share anything I can that might help.

**Comment by vabene1111** [comment]
ok so the view used some old functions which i properly never tested on a manual setup and which might have had problems with the CSRF protection system or something similar. I have updated the modal to use the new standard api client which should yield more consistent results. I have also implemented tagging support so you can create  a new book directly from the modal and you can now manage the books a recipe is already member of using the modal. 

All changes will be released with the next update

**Comment by venohm69** [comment]
Just wanted to let you know that I finally got around to upgrading to 0.16.8 and I verified that this issue is resolved with 0.16.8 for me.  I can now add recipes to books.  Thank you so very much for you work on this application and for taking the time to work on this issue.

**Comment by vabene1111** [comment]
awesome, glad you like it and everything is working now
