### ISSUE TITLE
Wrong fractions displayed for certain decimal values

### ISSUE THREAD

**Issue by charlesoblack** [vabene1111/recipes#775]
### Version

Version: 0.16.7, ref f531249

### Bug description

When inputting certain decimal values, the fractional version displayed is sometimes incorrect. For example:

![image](https://user-images.githubusercontent.com/18634426/126918820-1cd9933f-afd4-4bd0-8b6f-a2d90468db52.png)

for the input:

![image](https://user-images.githubusercontent.com/18634426/126918838-244ce6de-cd2c-4439-887f-8a9fc7f91e40.png)

(which I just inputted without the trailing 0's)

It seems the affected values are the decimals `0.1`, `0.9`, which get rounded to `1/9` and `9/9 = 1` respectively (the latter just gets added, and does not display as a fraction).

**Comment by vabene1111** [comment]
thanks for the detailed issue, i will look into this. Tandoor has some internal rounding mechanisms which might have failed.

**Comment by vabene1111** [comment]
ok that was both an easy fix and a relatively stupid mistake 😂 should be fixed in the next version

**Comment by charlesoblack** [comment]
A classic! Thanks so much for all your work! :)
