### ISSUE TITLE
Inconsistent spacing in recipes in search view

### ISSUE THREAD

**Issue by charlesoblack** [vabene1111/recipes#776]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.16.7, ref f531249

### Bug description

There is inconsistent spacing in the search view between recipes that have and don't have preparation/waiting times listed:

![image](https://user-images.githubusercontent.com/18634426/126919341-4af976d3-b81d-4690-b60c-ebe327e1f4ee.png)

which doesn't look as nice as if they were all "squished" together like the shepherd's pie/carrot cake in the middle of the image. :P

**Comment by vabene1111** [comment]
yes this is definitely not looking good 😂 i will see that it is fixed.

Also feel free to try out the new search layout and if you have any feedback let me know, the layout you are using will be deprecated at some point.

**Comment by charlesoblack** [comment]
If the (default) layout that I'm using is going to be deprecated, then I wouldn't worry about it :)

**Comment by vabene1111** [comment]
na dont worry, the old one is still supported and will be for some time, i want to make sure that any benefit the old layout had is also available in the new layout.

**Comment by vabene1111** [comment]
fixed in next update
