### ISSUE TITLE
Shopping list

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#78]
When generating a shopping list from a recipe where the ingredients are separated by headers, the headers will be included in the export.
Also: Is it possible to export the list to some shopping list app e.g. "shoplist" on mobile?

**Comment by vabene1111** [comment]
the first is definitly a bug, thanks for pointing that out! The second depends on the app. Right now the format allows the list to be copy pasted into google keep where then control boxes can be enabled and in anything supporting markdown. 

If you tell me what format you need for the app you like i can most likely add that.

**Comment by therealschimmi** [comment]
We use a shared shopping list in the iOS Reminders app. Haven't figured out what format is required for that though.

**Comment by vabene1111** [comment]
ok then i will close this issue for now as the bug is fixed. I dont have an iOS device so i cant test what format is needed there, as soon as you know that feel free to open another issue.
