### ISSUE TITLE
move an ingredient to another step

### ISSUE THREAD

**Issue by benoni280** [vabene1111/recipes#780]
When a recipe is 1 step or an ingredient is added to the wrong step, you have to create the ingredient in the other step en delete the ingredient in the previous step

It would be handy if you can select an ingredient and move or duplicate in another step

**Comment by vabene1111** [comment]
you can actually do that. just drag and drop it into the new area. If the new step does not have any ingredients yet its sometimes a little hard to find the correct place but it should work

![2021-07-28_13-48-00-%pn](https://user-images.githubusercontent.com/6819595/127317296-ea261af9-131e-46c9-a523-6c3ccb609020.gif)

**Comment by benoni280** [comment]
Oh wow!
stupid that i didnt try that!

Many thnaks for giving this feedback!

love the app!

**Comment by vabene1111** [comment]
no worries, the user interface sadly is not as intuitive as i would like, dont hesitate to ask questions, they always indicate places that need improvement.

Also thanks for the nice feedback, if you have any wishes or issues let me know.
