### ISSUE TITLE
search terms persist 

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#783]
Search terms are stored in the cookie - when starting a new session the search starts with old query.  These should timeout or be cleared with the session.

**Comment by vabene1111** [comment]
yes, i thought about that too but could not decide on a good time limit or session ...

what do you think, 8 hours ? if you for example search a recipe in the morning and come back a little later ? or too much, better something like 4 hours ?

**Comment by smilerz** [comment]
when in doubt make it a setting.  I don't actually like it persisting at all.

**Comment by vabene1111** [comment]
the persistence is required to some degree as it saves the page you are on .. but i see your point, i will look into this.

**Comment by vabene1111** [comment]
i have for now configured it so that it only persists for 4 hours, maybe some things will need to be splitted in the future or maybe things like the page must actually be stored in the url or somewhere else
