### ISSUE TITLE
Deleting related records

### ISSUE THREAD

**Issue by zhorvath83** [vabene1111/recipes#810]
### Version
Version: 0.16.8

### Bug description
- When I delete a recipe's step from the UI the cookbook_step_ingredients records aren't deleted.
- When I delete a recipe the cookbook_step records aren't deleted.

It causes no error but could they be deleted in the future for data cleansing purposes?

**Comment by vabene1111** [comment]
yes this is a problem with the way django rest framework handles deletion of records or to be more percise how my relations are set up. 

I think i could probably use signals for this ..

closing this as a duplicate of #701
