### ISSUE TITLE
Having one tandoor image with nginx and unicorn

### ISSUE THREAD

**Issue by choss** [vabene1111/recipes#811]
**Is your feature request related to a problem? Please describe.**
I personally would like to have tandoor in one container with all best practices intact and not have a separate container for nginx. I'd like the application be self contained in a selfhosted environment. I also cannot use docker compose as the images are managed via a configuration software like ansible, salt, Terraform. 

**Describe the solution you'd like**
I'd like a container preconfigured with all things needed to run the application. Perhaps even based on 
https://github.com/tiangolo/uwsgi-nginx-docker

**Describe alternatives you've considered**
I've considered building it myself like that for my private installation. 
I've also considered just letting gunicorn serve the static files.

I would like to have feedback if this idea is appreciated by the community or developer. 

**Additional context**
Please comment if something like this should be done or not.

**Comment by vabene1111** [comment]
thanks for the feedback. As far as i can tell most dockerized applications run with the application, web server and database separated into different containers. As this seems to be at least a very common practice (not sure if actually a best practice) i kinda want to stick to this pattern. 

I do understand the appeal and simplicity given by such a solution and it would definitely make many things easier and maybe even more secure.

If you want you can easily create a repo that just pulls all things together and build a all in one container, i can also link this as an unofficial way of installing tandoor but at this point i am not sure if i want to provide this as an official way of installation.

**Comment by choss** [comment]
Thanks for coming back to me!

Also I totally understand the reasoning. When I create something I'll post a link to this here.

Actually the docker best practice is to do one thing in a container. The internet disagrees on what a thing is...

Database I always would recommend to keep separate. For other things, there are examples like this project here, where every sub component is a own container. Or examples where just the whole software (minus database) is one container.

**Comment by vabene1111** [comment]
i totally understand your point and this is definitely something i will reconsider when time comes. if you need any help with a one container solution let me know
