### ISSUE TITLE
Shopping list

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#82]
So I figured I can use the iOS shortcut app to create a simple "script" that will add all the lines of the clipboard to the Reminders app. So i copy from recipes without markdown and then run the "script". Two things I noticed:
- Each line has a leading "Space"
- At the end of the list theres an empty line that's giving me an error message when trying to process with the "script". Mind changing this?

**Comment by therealschimmi** [comment]
How about adding customisation options to the "copy to clipboard" button?

**Comment by vabene1111** [comment]
i can remove the spaces no problem, what do you mean by customization options ? like custom javascript that you want to run before the copy is executed ?

**Comment by vabene1111** [comment]
so i have removed the spaces in front and added a different line break operator to the end of each line `&#13;&#10;`. I hope your script works with that as some kind of line break is required and since windows/mac/ios/unix all use different line endings they might not work for everyone.

**Comment by vabene1111** [comment]
i will close this issue, please create a separate issue about what kind of customization you might want added to the copy to clipboard button (sry about the extra work but separate issues are just easier to use/track for me)
