### ISSUE TITLE
Detail page for Books

### ISSUE THREAD

**Issue by phillipthelen** [vabene1111/recipes#821]
**Describe the solution you'd like**
It would be good if books had a detail page that you could open to view all recipes in the cookbook. As well as to then access the edit and delete options similarly to how they are on the recipe pages.

If this is a feature that others would like to see implemented as well, I would be interested in taking that on.

**Comment by vabene1111** [comment]
the whole books page will be rewritten to use the new front end components. This will also include some kind of viewer to have a quick and a more in depth overview of the recipes contained in a book

**Comment by vabene1111** [comment]
@Kaibu is working on the refactor :)

**Comment by Kaibu** [comment]
Mostly done, just missing user sharing management

**Comment by vabene1111** [comment]
sharing done
