### ISSUE TITLE
Option to use multiple steps without assigning ingredients to individual steps

### ISSUE THREAD

**Issue by phillipthelen** [vabene1111/recipes#822]
When adding/importing recipes it would be helpful to have a way to use the steps feature, since that renders the individual steps nicely, without then having the ingredients assigned to individual steps. Right now (at least I think it works that way) when you only have one step, it hides the ingredients list for the step and only shows the combined ingredient list at the top. Having this way of rendering also available for multiple steps would be good.

One option for implementing this could be a checkbox/flag for each step with "Show ingredients next to instructions" so that  it can be toggled on/off for each step.

**Comment by vabene1111** [comment]
there is already an open issue for this somewhere if i remember correctly. I think what we agreed on there was the exact soultion you propose: allow to have the ingredients on all steps but also have an option to disable this behavior. 

closing this as duplicate even though i dont know the original right now, but thanks for the feedback
