### ISSUE TITLE
Aliases for units and food

### ISSUE THREAD

**Issue by phillipthelen** [vabene1111/recipes#823]
**Is your feature request related to a problem? Please describe.**
When importing recipes from different sources, sometimes "Tablespoons" and sometimes "Tbsp" is used.

**Describe the solution you'd like**
Since there is no universal way to write some units, maybe there could be a way to configure "aliases" for units and maybe even food. That way when importing a recipe, "Tablespoons" could automatically be corrected to "Tbsp" if that is what is configured. While this is obviously not a huge issue, it does allow for more consistency within a users recipe list. It is also good for the shopping list feature when that combines multiple ingredients together adding their amount together.

**Comment by vabene1111** [comment]
yes this is definitely planned and something i wanted to to for a long time. Not sure yet if i want to use aliases or write some kind of rule system to automatically apply certain changes whenever a recipe is imported. 

But there will be some kind of solution

**Comment by phillipthelen** [comment]
I noticed that this already has an issue. Sorry I didn't check for that before. #167

**Comment by vabene1111** [comment]
no worries, closing this for the other one
