### ISSUE TITLE
MultipleObjectsReturned exception creating a new Food from Edit Recipe

### ISSUE THREAD

**Issue by raleeper** [vabene1111/recipes#833]
I am just starting to explore the code in the 'develop' branch. Fresh clone, empty sqlite database. If there are no foods in the database, creating a food during Edit Recipe works. Creating a second food for the same recipe appears to work, but that ingredient line gets linked to the first/only food in the database. If I use the admin tools to add my second food, I can subsequently use that food in the recipe. But then trying to create a third food from Edit Recipe fails with
`cookbook.models.Food.MultipleObjectsReturned: get() returned more than one Food -- it returned 2!`

I think the problem is in the `create `method of `FoodSerializer`. For some reason the name of the new food isn't being used in the get part of get_or_create and the entire foods table is returned. 

Creating a new Unit works correctly.  I notice that `UnitSerializer.create` says: 
```
obj, created = Unit.objects.get_or_create(name=validated_data['name'].strip(), space=self.context['request'].space)
```
compared to `FoodSerializer.create` which says:
```
        validated_data['name'] = validated_data['name'].strip()
        validated_data['space'] = self.context['request'].space
        obj, created = Food.objects.get_or_create(validated_data)
```
I don't know enough about Django yet to know why that makes a difference.

**Comment by vabene1111** [comment]
perfect, just merged #839 and tested the issue described here and everything seems to work.

No hotfix will be released as the issue only existed on develop
