### ISSUE TITLE
Meal Planning

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#84]
work on improving meal planning has started on `feature/meal-planning`. The plan is to have a nice interactive javascript frontend with drag and drop and all the other fancy features of non reloading javascript pages.

- [x] verify security implications of CORS_ALLOW_ALL 
- [x] create shopping list from day/week/meals
- [x] improve layout
- [x] api auth and user filtering
- [x] i cal export

previous issues regarding meal planning #20 #72

**Comment by Ombrelin** [comment]
Hello,
as an enhancement proposal, it would be nice to have an ical link for the meal planning in order to add it to the phone/computer calendar app !

Thank you for this great app ;)
