### ISSUE TITLE
Importer Checklist

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#844]
- [ ] check all importer types after FTS merge
- [x] verify persistence of certain object attributes of integration class

**Comment by smilerz** [comment]
@vabene1111 if you can add an example export of each integration (maybe in tests/other/test_data? or tests/other/integration_data?) I might be able to help with the test cases for those.

which object attributes are you looking to preserve?

**Comment by vabene1111** [comment]
i have a personal folder with examples but i was hesitant for now to commit it to the repository. In general i am unsure how best to handle tests that use larger amounts of data and data that might be copyright protected and cant be publicly shown. 

Maybe i could create a FTP server somewhere with credentials managed trough github actions but that would mean that those tests dont work locally ...

The second point was because i noticed that the `ignored_recipes` variable was not reset between importer runs, it appears that the object is not actually destroyed between runs and persists some data which needs to be looked into (this is likely just standard behavior of python but since i never really learned it i need to look into it 😂 )

**Comment by smilerz** [comment]
> i have a personal folder with examples but i was hesitant for now to commit it to the repository. In general i am unsure how best to handle tests that use larger amounts of data and data that might be copyright protected and cant be publicly shown.
Oh good point!  That probably applies to the existing tests too.  Should probably obfuscate all of the actual content on those.

**Comment by vabene1111** [comment]
ok tested all importers and fixed some issues
