### ISSUE TITLE
Search page empty on first load

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#845]
something is broken, results only show after refresh or reset

**Comment by smilerz** [comment]
I noticed that too - I think its fixed on the food PR.

**Comment by vabene1111** [comment]
food did not fix it but fixed it now, must have been broken at some point

**Comment by smilerz** [comment]
> food did not fix it but fixed it now, must have been broken at some point

what was it?

**Comment by vabene1111** [comment]
the refresh line was commented out with the comment "done by cookie load" i think trough the variable watchers but since that did not seem to work anymore i just added it back in manually. This whole delayed cookie loading thingy is a big mystery will at some point investigate this behavior properly
