### ISSUE TITLE
After import, no tags are applied

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#851]
### Version
Version:  0.16.8 (latest)

### Bug description

Probably related to #645. Once you import a recipe from an URL and add an existing tag during the import, the tag is not actually saved. In order to add the tag, the recipe has to be edited again.

**Comment by vabene1111** [comment]
i just tested both on my local (sqlite) and testin (postgres) setup and both import recipes just fine with a newly added keyword also being added to the recipe. Both instances are on develop so there might have been changes but i dont remember making any to this particular function. 

I will close this for now, please test again aftert the next version is released, if the issue still happens for you we will need to figure out whats differently on your setup.
