### ISSUE TITLE
Empty recipes after Nextcloud import

### ISSUE THREAD

**Issue by vfauth** [vabene1111/recipes#862]
### Version
Version: 0.16.8

### Bug description
I tried to import my recipes from Nextcloud. The import itself succeeded, but all recipes are empty and "/" was appended to the recipe name, as if Tandoor interpreted them as directories:
![image](https://user-images.githubusercontent.com/32266846/132123310-17c04f23-62d4-4f26-a9d0-0637aeac9c55.png)
Here's the layout of my Nextcloud recipes directory (I have 35 recipes in total, some of them without pictures):
```
# tree
.
├── Amaretti
│   ├── full.jpg
│   ├── recipe.json
│   ├── thumb.jpg
│   └── thumb16.jpg
├── Blanquette de veau
│   ├── full.jpg
│   ├── recipe.json
│   ├── thumb.jpg
│   └── thumb16.jpg
├── Bounty
│   └── recipe.json
```

**Comment by vabene1111** [comment]
maybe nextcloud changed the format or i broke something in one of the updates. Will investigate the issue and let you know when it works again.

**Comment by vfauth** [comment]
I think the format has been the same for some time now, so that would be surprising (but ofc I may be wrong).

Anyway, it's not a critical issue, take your time, and thank you for Tandoor!

For reference, I have Nextcloud 22.1.1 with Cookbook 0.9.2.

**Comment by vabene1111** [comment]
ok so i just tested with two of my old test exports and my current nextcloud export and all of them worked. Do you think you could send me your export (or part of it) so i can test if i get it working. If you dont want to post it here you can also send it to me via email info@tandoor.dev

If not please post all available information about your setup including setting `DEBUG=1` in `.env` and posting the log outputs during the import

**Comment by vabene1111** [comment]
closing due to missing feedback, please reopen if additional data can be provided and issue is still present
