### ISSUE TITLE
Remove/Hide menu from navigation bar

### ISSUE THREAD

**Issue by mustafaarif** [vabene1111/recipes#864]
Thanks for the great work.

I have two questions;
- Is there any possibility of optionally removing "Storage Data" from navigation bar?
- Does the license allow to change the logo from Tandoor to something different for personal use only?

**Comment by vabene1111** [comment]
thanks for the kind words :)

You are allowed to and can change both the logo and the navigation by editing the source files. This however must probably be done with every update as they will override those changes (except if you install manually).

The navigation is already planned to be reworked to a more useful one, it hasn't changed for a long time and is much overdue for a refactor, this will probably be released in the coming weeks. The logo can probably be made customizable for a future version but for not this is not a priority so you will need to find some way for yourself to change that, maybe with a github repo building a custom container from this one changing the assets in the build process.
