### ISSUE TITLE
Allow ingredients to be added from web interface rather than Django Admin Panel

### ISSUE THREAD

**Issue by mustafaarif** [vabene1111/recipes#868]
Hello,

I am using tandoor for last few days. I introduced it to my wife and she loved most of the features, however since she is not a tech savvy person, there are few things which I think can stop new user to get on board - one of them is adding ingredients through Django admin portal. In user role, the user shouldn't have to worry to go to Admin panel and add information. Is it something planned or looked into?

Thanks
Mustafa

**Comment by vabene1111** [comment]
Ingredients (or the technical modal name is foods, at least thats what i think you mean) can simply be create when editing a recipe. 

1. create a new recipe
2. a default step is automatically added
3. click the plus button to insert a new ingredient
4. there select the amount and type in whatever unit and food you want, if they dont exist yet they are automatically created. Other than that there is an overview page for foods, units and keywords where each of them can be created manually
