### ISSUE TITLE
Invite existing users into space / share recipe book across spaces

### ISSUE THREAD

**Issue by Giraffaman** [vabene1111/recipes#888]
## Issue
I'm trying to use Tandoor with one other user in the household and have yet failed to achieve either of the following:
- as far as I can see I can only invite new members into my space. I was looking for a way to add the already existing second user to my space. Entering their mail address into the "invite member" field gives an error like "mail address already in use" which makes sense. I have searched through the django admin menu and I see that I could put either of us into the same space (and then re-assign recipes) but I have not see a way to sort of "open up" my space to them.
- that gave me the idea to create a recipe book which would then be open to both users, but that also does not seem to work. When creating the book in the UI, I can only share it with users from my space, i.e. only myself. When I create the book directly in the database, I _can_ mark both users in the "shared" field, but the other user still does not see my book. My guess is that's because the book is still bound to either my space or theirs, with no obvious way to share the book across spaces.

Am I missing something or is the ability to share stuff between users across spaces something that's not an intended feature? It's fine for both of us to stick to our own spaces, but it would be nice to have the possibility of sharing recipes e.g. via a shared recipe book.

## Setup Info
Version: (can be found on the system page since v0.8.4)
0.16.8

OS: e.g. Ubuntu 20.02
Docker running on Debian Buster

Other relevant information regarding your problem (proxies, firewalls, etc.)

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
env content
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
docker-compose.yml content
```

### Logs
If you feel like there is anything interesting please post the output of `docker-compose logs` at
container startup and when the issue happens.

**Comment by vabene1111** [comment]
i am sorry for not documenting this well enough. 

The easiest way to achieve what you want is to go to the django admin, user preferences and then set the space to your space. other than that you could create an invite link without an email address, copy it manually from the space management page and give it to the second user who can than just click it to join your space. 

Inter space sharing is a feature that is planned for the future but not yet implemented, please let me know if this resolves your issue.

**Comment by Giraffaman** [comment]
sorry for my late reply. Tried passing on the invite link but she gets an error that she's already member of a space and cannot join another one.
I tested putting her into my space in the django admin interface but we got used to having our own spaces and will just keep using it that way. Since we're just two users in the same household there's no need for us to share the recipes beyond just having them on-screen when cooking, so for us it's all good.

Good to hear that space sharing is a planned feature though, as I can see that being very useful feature. Thanks for your time to get back to me.

**Comment by vabene1111** [comment]
are you sure you want to keep it this way? I can definitely guide you trough merging those two spaces or maybe even create a management command for that as having two spaces sounds a little annoying at least to me. 

feel free to message me and i can see what i can work out for you if you want your spaces merged.
