### ISSUE TITLE
Add link to translations

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#904]
Add a link to the main menu to the weblate site https://translate.tandoor.dev/projects/tandoor/.

![image](https://user-images.githubusercontent.com/1808639/133450715-b49ccf27-1465-431c-80c9-4856ea360f61.png)

**Comment by wisdomkhan** [comment]
Hello! I would like to work on this issue. Can you describe what is to be done exactly?

**Comment by vabene1111** [comment]
Hi, simply go to base.html, find the right drop down menu and add a link to the translation page translate.tandoor.dev probably next to GitHub. Text could be something like help translate or translate tandoor

**Comment by wisdomkhan** [comment]
On it right away.

**Comment by vabene1111** [comment]
We have font awesome 5 free just choose one you feel fitting

**Comment by wisdomkhan** [comment]
To test it, may I clone the repo and 'py manage.py runserver' ?

**Comment by vabene1111** [comment]
You can see how to locally test the application here https://docs.tandoor.dev/contribute/

**Comment by wisdomkhan** [comment]
I have opened a PR. Please check it.
