### ISSUE TITLE
Default Search Settings

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#906]
Create button to set recommended search settings.
- must detect DB type and load appropriately

These are the settings for the fullest features on postgres
![image](https://user-images.githubusercontent.com/1808639/133455101-d4bfe701-f3e8-49fa-bf1f-f323685f615e.png)

These settings are faster on postgres.
![image](https://user-images.githubusercontent.com/1808639/133455351-7ccff0f1-ae50-49f5-98ae-64ddeef161ff.png)

**Comment by vabene1111** [comment]
added some default settings via miration/defaults, buttons for different presets will be added later today or this week
