### ISSUE TITLE
Invited User cannot login

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#913]
### Version
latest beta 9/22/2021

### Bug description
1) Create invite link
2) Follow invite link
3) Complete account setup screen
get 500 error

Attempted to go to Admin screen and create preferences for user - also generates 500 error.

**Comment by smilerz** [comment]
Account seems to be successfully created - can successfully login, however get "no space" landing page.

**Comment by vabene1111** [comment]
can you tell me which settings you used when creating the invite link and maybe also post the log outputs ? I just tested invite links on my local test and on my personal instance and both worked just fine.

**Comment by smilerz** [comment]
Nothing was logged on the backend - I'll redo the test with debug mode on.

**Comment by vabene1111** [comment]
thanks 👍

**Comment by smilerz** [comment]
bug is in PR #860 (nginx config for mounting recipe at subfolder) and resolved with 32a6282
