### ISSUE TITLE
import recipes with different steps

### ISSUE THREAD

**Issue by lukino188** [vabene1111/recipes#914]
Hi, i love this app but i have a request if we compare to the others when we import a recipe they recreate different steps automatic on description... if possible to implement this feature here?

Thanks!

**Comment by vabene1111** [comment]
what do you mean by this ? some websites do offer steps natively in their data but many don't. Do you want those websites to create individual steps on import ? 

This also raises the question: Steps in tandoor are a little "further aparat"/more distinct than just numbered lists (which many pages treat as steps) so does it make sense to split those lists into what tandoor uses as steps or does it maybe make sense to just put proper line breaks or lists between steps so that they can be differentiated but are not completely pulled apart

**Comment by smilerz** [comment]
possible duplicate with #476

**Comment by lukino188** [comment]
yep, exactly the problem is that everytime i import something i need to fix the description... all the recipes i imported the description is difficult to read due no line breaks (with other recipe managment this problem is solved with steps), i think would be great that it will at least splits into different line breaks/paragraph.

Thanks!

**Comment by vabene1111** [comment]
by description you dont actually mean the field "description" but the field "instructions" (in the main editor body next to/below the ingredients correct ? 

I noticed this too, will take a look at how this can be improved with some automatic detection of paragraphs/line breaks

**Comment by lukino188** [comment]
yep, correct! 

Thanks so much!

Probably i need to open a new thread anyway
If you can, eventually in future, add a feature "Sub Recipes" (for example when we add a new recipe sometimes you need to link to another recipe already created previously. Could be implemented with a dropbox showing all recipes on the database.
Thanks!

**Comment by vabene1111** [comment]
This is already implemented in two different ways
- you can link recipes to ingredients (so they show a link in the ingredient list, you do so on the food management page)
- you can change the type of a step to be "recipe" and select a recipe to be shown

hope this helps :)

**Comment by lukino188** [comment]
Thanks so much, i had time and write some recipes. 

last info/idea then i will open eventually a new thread.

I would like to know if can be implement when we add a new sub recipes have a box with a number of portion of that subrecipe (sometimes one recipe need only half of that ect.)
When we add a photo at the recipe i cant attach any photo from url. is it possible to add a photo even from url?


Thanks so much!

**Comment by vabene1111** [comment]
sub recipe: there is an open issue somewhere for sub recipe portions, thats something i missed when implementing the feature and that will likely follow in the next update
photo: you can use markdown syntax `![alt text](url)` to insert photos into descriptions. There is a files feature which is not very polished that will integrate with this

**Comment by vabene1111** [comment]
ok so i have fixed the importer to apply a double space to line ends so that markdown actually renders the line breaks. This should fix this for now. We can look into how splitting recipes into actually different steps if they are given from the website in the future
