### ISSUE TITLE
recipe edit image not shown directly after save

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#93]
when saving a new image into a recipe the reloaded page does not directly show the image as added thus does not allow resetting or viewing it

**Comment by samr28** [comment]
Also having this issue. Is there a temporary workaround?

**Comment by vabene1111** [comment]
just reload the page once and the image will show up. I guess its not really a standard usecase to delete the image right after upload so it shouldn't be a big problem or is it ?

**Comment by samr28** [comment]
Oh my issue must be different then. After uploading an image (jpg), it can't show the image and displays the alt text. For some reason, when I check the image link, it goes to a png file instead which can't be found. Should I create a separate issue for this or is there something I'm doing wrong here?

**Comment by vabene1111** [comment]
yes please, there is an automatic conversion since i compress the images on upload (in order to save disk space). I thought i fixed this a while ago but would be great if you could open an issue. 

If you want also upload the image, if not please provide provide exactly what kind of image fails.

**Comment by benoni280** [comment]
Hi, i seem to have a similar issue.
the picture doesn't load while the PNG is available on the server and the link is the same.

**Comment by vabene1111** [comment]
this also seems to be related to your setup and the recent migration with image serving. Please open a new issue with your setup info (.env, docker-compose.yml) so i can help you with that.
