### ISSUE TITLE
system page version check

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#94]
to be able to check the version the container first needs to know its current version. For this the build script needs to add the tag or a build timestamp or similar to the image.

**Comment by therealschimmi** [comment]
how do updates work with docker containers? Does it make sense to include update functionality within the webinterface?

**Comment by vabene1111** [comment]
since i allow many forms of installation (manual. kubernets, docker image, docker self-build) i dont think it makes sense building any kind of integrated updating solution. Also never really seen any dockerized project do that, most have these kinds of features trough some kind of outside managent tool.
