### ISSUE TITLE
Quick option to add pictures, add list of special utensils

### ISSUE THREAD

**Issue by bitbooster** [vabene1111/recipes#946]
Hello,
I'm starting to use Tandoor as my digital cookbook, and when starting to add my recipes I miss:
- a simple option to add pictures in the recipes steps (at least an option to attach files at the end of an instruction step)
- next to the ingredients, a space for a list of special requirements, e.g. a large oven dish, or a planetary mixer, or such, that shouldn't be exported into the shopping list.

**Comment by vabene1111** [comment]
Thank you for the feedback.

Files in steps (and thus images) are already supported, the dialog to add them will be improved with the next release so its easier to manage them (currently only available by appending /files/ to the url)

There is also a plan to add a dedicated "tools" list for each recipe, this will likely be included in the next release.

Both features are planned for the release after the one coming today.
