### ISSUE TITLE
Foods with linked recipes - Not linking

### ISSUE THREAD

**Issue by PureLoneWolf** [vabene1111/recipes#957]
### Version
Version:  0.17.1 (In an Unraid Docker)

### Bug description
Hi all

I am not sure when the issue was introduced (I wasn't paying attention on 0.17 unfortunately), although it was definitely working prior to 0.17.  I have Foods that link out to their own recipe.  They normally provide a clickable link from within the Recipe they are listed as ingredients in.  

The links aren't appearing at the moment.  I tried to re-edit the food in the backend to confirm the recipe they are connected to, but the link still doesn't appear on the Recipe page.

Many thanks, as always :)

**Comment by vabene1111** [comment]
ok this was indeed an api change, issue is fixed, release will likely follow today or on saturday. If you want it faster you can use the beta image but be warned if you use the manual setup you might need to install frontend dependencies yourself since this will also change in the next update.
