### ISSUE TITLE
0.17.2 Ignores STATIC_URL when generating static files

### ISSUE THREAD

**Issue by eljef** [vabene1111/recipes#972]
### Version
Version: 0.17.2

### Bug description
When using STATIC_URL that is not default, in combination with 0.17.2, files are not being prefixed with the STATIC_URL.

My STATIC_URL is set to "/tandoor/static".
When loading Tandoor, loading static assets will fail when navigating away from the first logged in page.

v0.17.2
```
GET https://<domain>/static/vue/js/chunk-vendors.js 404
GET https://<domain>/static/vue/css/chunk-vendors.css 404
GET https://<domain>/static/vue/js/recipe_view.js 404
GET https://<domain>/static/vue/css/recipe_view.css 404
```

v0.17.1
```
GET https://<domain>/tandoor/static/vue/css/chunk-vendors.eeb255433fa0.css 200
GET https://<domain>/tandoor/static/vue/css/recipe_view.cb0bf1a69861.css 200
```

When looking at the generated static files for 0.17.2, all urls are hard-coded with "/static/vue/...". When inspecting generated static files for 0.17.1, all urls correctly prefixed. ie "/tandoor/static/..."

I've also verified that SCRIPT_NAME and JS_REVERSE_SCRIPT_PREFIX are set correctly. This has no effect on the outcome.

**Comment by eljef** [comment]
Yes I do. It is set to "/tandoor". I tried removing it as well, with no effect.

Removing it in 0.17.1 results in `Error whilst registering service worker DOMException: The operation is insecure.` in the console.

**Comment by eljef** [comment]
@vabene1111 The beta image works. Do you have a commit that fixes this?

**Comment by eljef** [comment]
I just saw 6949e17a33a781a0b69fdb8fe5cca239c0f16fe8
Seems to be working as expected now. Thanks for your work.

**Comment by vabene1111** [comment]
Awesome, you can also use the release image, we updated yesterday.

Thanks for the help debugging and sorry for the inconvenience.
