### ISSUE TITLE
Superadmin user access

### ISSUE THREAD

**Issue by Erwyn** [vabene1111/recipes#99]
Hi there,

First, thanks for the good work.

I installed recipes using the plain docker-compose, I have a caddy proxy in front of it. I created the first user through the interface as intended, but then I wanted to add another user. So I went to the "Admin" section but it says that although I’m logged as "MyUserName" I’m not authorized to access this page. 

Are there other credentials I should be aware of ?

**Comment by vabene1111** [comment]
oh that is not good, i thought setting super user would be enough but apparently staff permission is also required. I will release a fix for this in 5 minutes. For you you have two options now:

1. Delete the database (if you haven't done anything yet) and run the setup again
2. create a new superuser manually trough the command line (command given in instructions) and use that user to give your old user the "Staff" permission

If you need any help with that feel free to ask and sry for the inconvenience.

**Comment by Erwyn** [comment]
Thanks for the quick answer ! Well I will simply delete everything that will be the easiest, I’m checking it’s working, and if so, I’ll close the issue.

**Comment by Erwyn** [comment]
it solved it. Thank you very much !
